### ISSUE TITLE
Missing bar for values

### ISSUE THREAD

**Issue by aminmc** [jerairrest/react-chartjs-2#106]
Hello there

I have a simple horizontal bar chart with the dataset values [3, 4, 4, 3, 3] however I only see the bars for values 4 and 4.  I've attached a screen shot of the chart I'm seeing
<img width="1145" alt="screen shot 2017-02-27 at 15 01 29" src="https://cloud.githubusercontent.com/assets/290639/23366258/047b2cac-fcfe-11e6-999b-bfc5129fee98.png">
 
I'm using the following configuration

```javascript
var data = {
            labels: [
                "One star",
                "Two star",
                ....],
            datasets: [
                {
                    label: 'Ratings',
                    backgroundColor: 'rgba(24, 168, 159, 0.4)',
                    borderColor: 'rgba(0,0,0,0)',
                    hoverBackgroundColor: 'rgba(24, 168, 159, 0.9)',
                    hoverBorderColor: 'rgba(24, 168, 159, 1)',
                    data: [3, 4, 4, 3, 3]
                }
            ]
        };
```

Has anyone see this before?

**Comment by AdeelK93** [comment]
I don't see anything wrong with the snippet you provided, could you post a full example of your react code?

**Comment by dgana** [comment]
yes im facing similar issue

**Comment by alphakennyn** [comment]
any update? I'm having similar issue

**Comment by AdeelK93** [comment]
Do you have a code example demonstrating the issue? Would help with debugging

**Comment by pkellner** [comment]
The example is in your own example doc. I posted a new issue on this not seeing it here originally . http://jerairrest.github.io/react-chartjs-2/

**Comment by OmarZayed77** [comment]
I had the same issue and it was resolved by adding (stacked: true) to xAxis and yAxis (for example as shown below) inside the options object.
![image](https://user-images.githubusercontent.com/48209805/66277176-eb316000-e89a-11e9-81ff-0f479f0b853a.png)

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
