### ISSUE TITLE
xAxes: Stacked doesn't appear to work

### ISSUE THREAD

**Issue by timwis** [jerairrest/react-chartjs-2#108]
It appears that setting `scales.xAxes[0].stacked = true` in the `options` does not have an effect in `react-chartjs-2`, even though it works as expected in vanilla Chart.js.

```javascript
      scales: {
        xAxes: [{
          stacked: true
        }]
      }
```

Demo: https://www.webpackbin.com/bins/-KeYdil1aIYyXyNOoybq
The result _should_ be that the bars are stacked on top of one another.

Any idea why it doesn't work?

**Comment by AdeelK93** [comment]
I think you need to be setting yAxes to stacked, is this what you had in mind? https://www.webpackbin.com/bins/-KelYmVr_lJpR3TkI56B

**Comment by timwis** [comment]
@AdeelK93 actually no -- I'd like the "filtered" values to lay _over_ the "total" values rather than on top of them. This will give the appearance of "filtering the total amounts." For an example, click on the pie chart in [this visualization](http://vizw.it/?gist=51db593dc0537d1a3f05) and see what happens to the bar charts.

**Comment by AdeelK93** [comment]
Wouldn't the total be the sum of all the components? E.g. a stacked chart would be filtered + not filtered = total, giving you the correct heights for the bars. It's a clever visualization, and that's how I would go about implementing it in react chartjs.

I haven't seen any support for overlayed bar charts in vanilla chart.js so far, only stacked bar charts

**Comment by timwis** [comment]
@AdeelK93 actually, Chart.js did support this functionality, which is one of the main reasons I explored the library further. But it seems like v2.5 introduced a regression breaking this functionality.

Example of the desired functionality using Chart.js v2.4:
https://www.webpackbin.com/bins/-KfBFWirodI6k6U1b-bx

I'll post this issue in the Chart.js repository.

**Comment by AdeelK93** [comment]
Glad you were able to hunt down the root cause! Did not know you could stack bar charts like that

**Comment by kumarharsh** [comment]
Since the root issue is solved in Chartjs, this issue can be closed?

**Comment by jerairrest** [comment]
I believe it can be now. :) If there's still troubles please reopen
