### ISSUE TITLE
Typescript: "has no exported member 'defaults'"

### ISSUE THREAD

**Issue by fabioberger** [jerairrest/react-chartjs-2#110]
Hi there,

When importing 'defaults' from `react-chartjs-2`:

```ts
import {defaults, Line} from 'react-chartjs-2';
```

I get the following Typescript error:

```
Module /.../react-chartjs-2/index has no exported member 'defaults'
```

Looking at the project's `index.d.ts`, it does not include the `defaults` export. Was this done intentionally?

Thanks

**Comment by jerairrest** [comment]
It probably was over looked. :) If you want to add that declaration that would be swell.
