### ISSUE TITLE
Sizing issue when placed in a flexbox

### ISSUE THREAD

**Issue by justinmasse** [jerairrest/react-chartjs-2#111]
Finding that when charts are placed in a flexbox they are using the window size rather then the divs(flexbox) size. Any way around this?

**Comment by Robinnnnn** [comment]
The charts also seem to move around on their own upon window resizing. Very mysterious.

**Comment by yss14** [comment]
Had the same problem with flexible div height. Solved it by wrapping the chart in a static div.
```
<div style={{ width: 300, height: 300 }}>
    <Doughnut data={data} width={250} height={300} options={{ maintainAspectRatio: false }} />
 </div>
```

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
