### ISSUE TITLE
Add a point to line chart

### ISSUE THREAD

**Issue by RuiSa** [jerairrest/react-chartjs-2#112]
hey, is there any way of adding a point, given an x and y values, to a line chart?
Thanks, Rui

**Comment by AdeelK93** [comment]
Something like a scatter line? http://www.chartjs.org/docs/#line-chart-scatter-line-charts

**Comment by RuiSa** [comment]
What I need is to add a point to the chart in the image below. Didn't manage to get it working with scatter line. Do you have any suggestion @AdeelK93 ?

![ex](https://cloud.githubusercontent.com/assets/4196425/24153855/727a4e4a-0e47-11e7-99da-fb7c637a11e5.png)

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
