### ISSUE TITLE
Unable to dynamically add/remove series

### ISSUE THREAD

**Issue by 3ll3d00d** [jerairrest/react-chartjs-2#114]
NB: This might be the same issue as #90 

I have a chart that allows the user to add/remove series, each series has a unique id and the user can change the series on screen at will without rerendering the page. If I set `redraw` then everything works fine, if not then the chart rapidly gets confused and either doesn't update or renders the wrong series.

This seems like it is due to `memoizeDataProps` in that it compares lists by indexes rather than via some id (so that it knows exactly which dataset to add/remove). 

Is there a key property I'm missing that would allow this to work or is this not possible with the current implementation?

**Comment by imperium2335** [comment]
+1

**Comment by 3ll3d00d** [comment]
#116 provides an implementation of this, seems to work fine for my setup

**Comment by BenLorantfy** [comment]
If anyone comes across this wondering why their multiple datasets are combing into one, make sure the label is set on your datasets and that they're unique.
