### ISSUE TITLE
Add legend to parts of doughnutchart

### ISSUE THREAD

**Issue by Endorel** [jerairrest/react-chartjs-2#117]
Hi!

I'm working with the doughnutchart and I was wondering if there was any way to implement a legend that is attached to the corresponding part in the doughnutchart? Example:

<img width="86" alt="legend_example" src="https://cloud.githubusercontent.com/assets/16289839/24149976/adc57608-0e44-11e7-895d-03d4dbc65505.PNG">

I am open to any suggestions on how to achieve this. Thanks!

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
