### ISSUE TITLE
Change default font family

### ISSUE THREAD

**Issue by Farahzadi** [jerairrest/react-chartjs-2#122]
how to change default fontFamily

**Comment by miguelperes** [comment]
I think you have to import the **defaults** object: 
`import { defaults } from 'react-chartjs-2'` 

and then set the **fontFamily** attribute: 
`defaults.global.defaultFontColor = 'Arial'`

**Comment by tylersnyder** [comment]
Just to clarify, there was a typo @miguelperes's answer, which I believe should be:

`defaults.global.defaultFontFamily = 'your-font-family'`

**Comment by miguelperes** [comment]
Oh, you're right @tylersnyder! I'm going to edit that so no one gets confused!

**Comment by jerairrest** [comment]
Thanks guys, closing this issue.

**Comment by launchriot** [comment]
do you have to import and set defaults in every component you include the chart in, or can you do it globally?

**Comment by paulcredmond** [comment]
Where do you add `defaults.global.defaultFontFamily = 'your-font-family'`?

I added at the top of the component but it's not working for me.

**Comment by mohsenmahoski** [comment]
its worked for me:


    import React, { Component } from 'react';
    import {Line} from 'react-chartjs-2';
    import { defaults } from 'react-chartjs-2'
    import 'chartjs-plugin-datalabels';


    defaults.global.defaultColor = 'yourColor';
    defaults.global.defaultFontColor = 'yourColor';
    defaults.global.defaultFontFamily = 'yourFont';
    ....

    export class LineChart extends Component {
  
      render() {
        console.log(defaults);
        const {datasets,height} = this.props;
        const data = {
          labels: ['label1', 'label2', 'label3', 'label4', 'label5', 
                     'label6','label7','label8','label9','label10','label11','label12'],
          datasets:datasets
        };
        const options = {
              plugins: {
                datalabels: {
                    display: true,
                    color: '#FFF',
                    borderRadius:10,
                    backgroundColor: function(context) {
                    return context.dataset.backgroundColor;
                    },
                    align	: 'center',
                    textAlign:'center',
                    font: {
                       weight: 'bold'
                    },
                }}
          }
         return (
              <Line options={options} data={data} height={height} />
         );
       }
     }

     export default LineChart;


and you can see all `defaults` properties in console by `console.log(defaults);` and change anything you want. ;))

**Comment by paulcredmond** [comment]
Thanks @mohsenmahoski we got it working.

**Comment by crlsmtzprds** [comment]
> I think you have to import the **defaults** object: `import { defaults } from 'react-chartjs-2'`
> 
> and then set the **fontFamily** attribute: `defaults.global.defaultFontFamily = 'Arial'`

For react-chartjs-2@^4.0.1 defaults change to chart.js library:

`import { defaults } from 'chart.js';`

and  `"defaults.global.defaultFontFamily"` prop change to  `"defaults.font.family" ` prop

**Comment by adeleke5140** [comment]
I have an issue with importing defaults.
It says `react-chartjs-2 has no exported member 'defaults'`

**Comment by crlsmtzprds** [comment]
> I have an issue with importing defaults. It says `react-chartjs-2 has no exported member 'defaults'`

See my comment... you need import **defaults** member from **chart.js** and not from **react-chartjs-2**
