### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'element['offset'+dimension]')

### ISSUE THREAD

**Issue by arronhunt** [jerairrest/react-chartjs-2#124]
Title says it all, getting that error with a simple script.

    import React from 'react';
    import { Bar } from 'react-chartjs-2';

    data = { ... }

    const Component = () => (
        <div>
            <Bar data={data} />
        </div>
    )

**Comment by AdamWagner** [comment]
Also experiencing this. Will let you know if I find a solution.

**Comment by AdamWagner** [comment]
Check your dependencies, especially if you had a pre 2.0 version of chart.js installed. That was my issue.

**Comment by iboxgithub** [comment]
Thanks a lot, it was my issue too because I had a pre 2.0 version of chart.js that remained in my package.json. Just updating the lib is enough --> don't forget to restart your server if you run locally (npm start)
From my point of view this issue could be closed 👍
