### ISSUE TITLE
Sometimes doughnut pies are dissapeared after updating to the final version

### ISSUE THREAD

**Issue by alrms** [jerairrest/react-chartjs-2#136]
Hello everyone, i'm dealing with an issue after updating my react-chartjs-2. When my component is rendering i see something like this:
![screenshot 15](https://cloud.githubusercontent.com/assets/28054369/26390439/385b6436-4067-11e7-8268-d359a0dd50ae.png)

Inside the boxes three pies should be rendered but i see nothing as you can see

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
