### ISSUE TITLE
Update to latest chart.js

### ISSUE THREAD

**Issue by Elviron** [jerairrest/react-chartjs-2#144]
Could you update to the latest version, so we get all the nice features!

**Comment by davidmason** [comment]
@Elviron you can probably just use chart.js@2.6.0 with the current version and have it work. Looking at the breaking changes in [their releases](https://github.com/chartjs/Chart.js/releases), nothing in there looks like it would obviously break `react-chartjs-2`.

I have done this and so far have not noticed any issues (just making one line chart though).

**Comment by jerairrest** [comment]
Chart.js is a peer dependancy so you can use whatever version you would like with this package.

**Comment by jerairrest** [comment]
@Elviron I'm closing this for now. If you're still having troubles let me know!
