### ISSUE TITLE
Disabling hover is not working

### ISSUE THREAD

**Issue by osnysantos** [jerairrest/react-chartjs-2#147]
I'm using latest version of react-chart-2 (2.1.0) and chartjs (2.6.0) and even setting this:

``hover: { mode: false },``

The function `onComplete` of animation is always begin triggered, I thought it won't be a problem as they said is fixed since v2.5. Please take a look: https://github.com/chartjs/Chart.js/issues/3181

**Comment by Ancinek** [comment]
Same here :( Does not seem to work

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
