### ISSUE TITLE
highlighting a line on the chart programmatically

### ISSUE THREAD

**Issue by varunagg45** [jerairrest/react-chartjs-2#153]
I am looking for a way to highlight a line on the chart, can you guys please point me to an example that does that?

**Comment by kumarharsh** [comment]
What do you mean by "highlight"?

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
