### ISSUE TITLE
Testing with jest / enzyme / jsdom - Failed to create chart: can't acquire context from the given item

### ISSUE THREAD

**Issue by csi-lk** [jerairrest/react-chartjs-2#155]
Using the DoughnutChart example

doughnutChart.js
```
import React from 'react'
import { Doughnut } from 'react-chartjs-2'

const data = {
  labels: [
    'Red',
    'Green',
    'Yellow',
  ],
  datasets: [{
    data: [
      300,
      50,
      100,
    ],
    backgroundColor: [
      '#FF6384',
      '#36A2EB',
      '#FFCE56',
    ],
    hoverBackgroundColor: [
      '#FF6384',
      '#36A2EB',
      '#FFCE56',
    ],
  }],
}

const DoughnutChart = props => (
  <div className="chart-wrapper">
    <Doughnut
      data={data}
    />
  </div>
)

export default DoughnutChart
```
doughnutChart.spec.js
```
import React from 'react'

import DoughnutChart from './doughnutChart'

it('Renders a DoughnutChart', () => {
  const wrapper = mount(
    <DoughnutChart />,
  )
  expect(wrapper).toMatchSnapshot()
})
```

**Error**
```
Failed to create chart: can't acquire context from the given item
      
      at CustomConsole.Object.<anonymous>.console.error (tools/jestSetup.js:37:9)
      at Chart.construct (node_modules/chart.js/src/core/core.controller.js:116:13)
      at new Chart (node_modules/chart.js/src/core/core.js:7:8)
      at ChartComponent.renderChart (node_modules/react-chartjs-2/lib/index.js:259:29)
      at ChartComponent.componentDidMount (node_modules/react-chartjs-2/lib/index.js:81:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:209:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:319:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:91:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:200:24)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/elements/doughnutChart/doughnutChart.spec.js:6:17)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
```

**Comment by rafaelmmathias** [comment]
i'm getting the same error

**Comment by Si1kIfY** [comment]
Workaround is to mock out the chart for enzyme mounting

```
    jest.mock('react-chartjs-2', () => ({
      Doughnut: () => null,
    }))
```

**Comment by paterninaisf** [comment]
Hey, if you use `enzime` library you can do this.
` const wrapper = shallow(<DoughnutChart />, { lifecycleExperimental: true });`
//here any assert or expect

**Comment by Parziphal** [comment]
In my case the solution provided by csi-lk wasn't working because `jest.mock()` must be outside the `describe()` function (for those using `describe`). Parhaps that's obvious but it wasn't for me.

**Comment by CWSites** [comment]
@csi-lk's solution worked for me, be sure to put it in your `setup-jest.js` file.

**Comment by schlattk** [comment]
@csi-lk @CWSites can't get that to work with create react app and enzyme - can you show an example of the setup-jest.js file and where it's located?

**Comment by schlattk** [comment]
ok thanks that's what I had as well but doesn't have any effect, however I got it to work now by putting the line 
jest.mock('react-chartjs-2', () => ({ Line: () => null })) 
on top of the test file as per cheshire137

**Comment by CWSites** [comment]
@schlattk do you have the `setup-jest.js` file setup properly in your `package.json` similar to this.

```
  "jest": {
    "setupFiles": [
      "./shim.js",
      "./setup-jest.js"
    ]
```

**Comment by schlattk** [comment]
Hi, yes but apparently setup files are not supported in create react app - according to the error message in terminal, it works fine in any case though!

**Comment by CWSites** [comment]
@schlattk I see, I'm using https://github.com/timarney/react-app-rewired so that's probably where the difference is. Glad it's working for you! @csi-lk I believe this can be closed, unless you're wanting @jerairrest to build this into `react-chartjs-2`?

**Comment by rajatchugh2431** [comment]
I am having an issue every line inside draw function is not covered in the test coverage .See the attached photo you will find those highlighted lines there.
I am using following dependencies

"devDependencies": {
"@babel/plugin-proposal-class-properties": "^7.7.4",
"@babel/plugin-transform-react-jsx": "^7.7.7",
"@babel/preset-env": "^7.7.7",
"@babel/preset-react": "^7.7.4",
"axios-mock-adapter": "^1.17.0",
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.2",
"jest-dom": "^4.0.0",
"node-sass": "^4.11.0",
"react": "^16.12.0",
"react-test-render": "^1.1.2"
}
I am having an issue every line inside draw function is not covered in the test coverage .See the attached photo you will find those highlighted lines there.
I am using following dependencies

"devDependencies": {
"@babel/plugin-proposal-class-properties": "^7.7.4",
"@babel/plugin-transform-react-jsx": "^7.7.7",
"@babel/preset-env": "^7.7.7",
"@babel/preset-react": "^7.7.4",
"axios-mock-adapter": "^1.17.0",
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.2",
"jest-dom": "^4.0.0",
"node-sass": "^4.11.0",
"react": "^16.12.0",
"react-test-render": "^1.1.2"
}
![uploadgit](https://user-images.githubusercontent.com/38530799/72787790-99002900-3c56-11ea-867d-9cc1ed47f6f7.png)

**Comment by DPK101** [comment]
@rajatchugh2431 Are you able to get the test coverage of highlighted lines from your 'draw' function?

**Comment by imsangram** [comment]
> @schlattk do you have the `setup-jest.js` file setup properly in your `package.json` similar to this.
> 
> ```
>   "jest": {
>     "setupFiles": [
>       "./shim.js",
>       "./setup-jest.js"
>     ]
> ```
I was trying to to use in CRA app but it didn't allow me.
You can directly add following piece of code in 'src/setupTests.js' file. No need to configure jest config. 

```
import React, { Component } from 'react';

jest.mock('react-chartjs-2', () => ({
  Bar: () => null, // add any additional chart types here
  Line: () => null
}));
```

**Comment by sgavathe** [comment]
The issue with this mock is 
```
jest.mock('react-chartjs-2', () => ({
  Bar: () => null, // add any additional chart types here
  Line: () => null
}));
```

   you can't then test against canvas, it won't render canvas inside your screen container!

     const canvas = screen.getByTestId('testdiv').querySelector('canvas') ;
     expect(canvas).toBeInTheDocument();

**Comment by joe-choi-dev** [comment]
I had the same issue with @sgavathe 
After looking at their test-setup -- https://github.com/reactchartjs/react-chartjs-2/blob/master/test/setup.js

I just had to add, to eliminate the console errors while also rendering canvas in my jest tests
```
import 'jest-canvas-mock';

class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
}

window.ResizeObserver = ResizeObserver;
```

**Comment by dbak-alt** [comment]
how to mock clicking a point in chartjs ?

**Comment by MaximeKoitsalu** [comment]
@joe-choi-dev Thanks for sharing, I had exactly the same issue.

**Comment by aimad-majdou** [comment]
@joe-choi-dev That didn't eliminate the console errors on my case, I added those same lines to my test-setup.

**Comment by aimad-majdou** [comment]
Anyone has a solution for this issue without using:

```
jest.mock('react-chartjs-2', () => ({
  Doughnut: () => null,
}));
```

Because by doing that we can't test against the canvas as @sgavathe mentioned.

**Comment by lissettdm** [comment]
This can be fixed by installing `canvas` as dev dependency in your project. 

"jsdom includes support for using the [canvas](https://www.npmjs.com/package/canvas) package to extend any <canvas> elements with the canvas API. To make this work, you need to include canvas as a dependency in your project, as a peer of jsdom. If jsdom can find the canvas package, it will use it, but if it's not present, then `<canvas>` elements will behave like `<div>`".  Taken from here -> https://github.com/jsdom/jsdom#canvas-support

**Comment by sgavathe** [comment]
You can mock your charts further by doing something like this. 

```
jest.mock('react-chartjs-2', () => ({
    Bar: (props:any) => {
        expect(props.type).toBe('horizontalBar');
         return <div>Bar Chart</div>
    },
    Line: (props:any) => {    
        expect(props.type).toBe('line');        
        return <div>Line Chart</div>
    }
}));
```

**Comment by DCosti** [comment]
Hi! I am facing the same issue. I am currently using latest versions of `react-chartjs-2` and `chartjs`. I tried the fix suggested  by @joe-choi-dev but didn't work for me.
Do you guys have a fix for this issue?
Thanks!

**Comment by shannonhochkins** [comment]
If you're attaching a reference element to the chartjs component the above will not work directly as it's a functional component, you'll need to return a fake component forwarding the ref

If you're using in your component like so:

```
   const barRef = useRef(null);
    <Bar ref={barRef} ... />
```
Then you'll need to adjust the mock:
```
jest.mock('react-chartjs-2', () => {
  const { forwardRef } = require('react');
  const Line = forwardRef(props => <div {...props}></div>);
  const Bar = forwardRef(props => <div {...props}></div>);
  return {
    Line,
    Bar,
  };
});
```

**Comment by SalahAdDin** [comment]
> Hi! I am facing the same issue. I am currently using the latest versions of `react-chartjs-2` and `chartjs`. I tried the fix suggested by @joe-choi-dev and the one suggested by @lissettdm but didn't work for me. Do you guys have a fix for this issue? Thanks!

It is also not working for me.

**Comment by Jordan-Pillai** [comment]
I have a BarChart component as follows:

` const BarChart = ({ data, options }: BarProps) => {
  const chartRef = useRef<ChartJS<"bar"> | null>(null);

  return (
    <Bar
      options={options}
      data={data}
      ref={chartRef}
      onClick={(event) => {
        const { current: chart } = chartRef;

        if (!chart) return;

        const dataset = getDatasetAtEvent(chart, event);
        const element = getElementAtEvent(chart, event);
        const elements = getElementsAtEvent(chart, event);

        // eslint-disable-next-line no-console
        console.info(dataset, element, elements);
      }}
    />
  );
};

export default BarChart;
`

I am trying to write unit tests for it however I keep getting the following error message when running the test

 **Failed to create chart: can't acquire context from the given item**

I can't use the suggestion of

`
jest.mock('react-chartjs-2', () => ({
  Bar: () => null
}));
`

because it doesn't render the canvas element

**Comment by 927tanmay** [comment]
> I am having an issue every line inside draw function is not covered in the test coverage .See the attached photo you will find those highlighted lines there. I am using following dependencies
> 
> "devDependencies": { "@babel/plugin-proposal-class-properties": "^7.7.4", "@babel/plugin-transform-react-jsx": "^7.7.7", "@babel/preset-env": "^7.7.7", "@babel/preset-react": "^7.7.4", "axios-mock-adapter": "^1.17.0", "enzyme": "^3.11.0", "enzyme-adapter-react-16": "^1.15.2", "jest-dom": "^4.0.0", "node-sass": "^4.11.0", "react": "^16.12.0", "react-test-render": "^1.1.2" }
> 
> ![uploadgit](https://user-images.githubusercontent.com/38530799/72787790-99002900-3c56-11ea-867d-9cc1ed47f6f7.png)

@rajatchugh2431 were you able to find any solution for the same?

**Comment by DCosti** [comment]
Hi @Harinath60 . No, I didn't find any solution. I tried one of the solutions described above but didn't worked for me

**Comment by josephdicdican** [comment]
> I had the same issue with @sgavathe After looking at their test-setup -- https://github.com/reactchartjs/react-chartjs-2/blob/master/test/setup.js
> 
> I just had to add the code below to eliminate the console errors while also rendering canvas in my jest tests
> 
> ```
> import 'jest-canvas-mock';
> 
> class ResizeObserver {
>   observe() {}
>   unobserve() {}
>   disconnect() {}
> }
> 
> window.ResizeObserver = ResizeObserver;
> ```

This solved our issue with testing react-chartjs-2. We are using vitest. So we needed the vitest version. 
```
yarn add --dev vitest-canvas-mock
```
And appended in our setup.js file
![image](https://user-images.githubusercontent.com/15903512/217447705-089de1fa-cddb-4ede-8fbc-59bcacdb4a71.png)

Now our test is successful.
![image](https://user-images.githubusercontent.com/15903512/217449624-04a1cf39-8519-484c-ba61-85fbcd5a682e.png)
![image](https://user-images.githubusercontent.com/15903512/217449341-a9248ec0-4233-4aee-9786-954e354733ed.png)
![image](https://user-images.githubusercontent.com/15903512/217449376-c5f4a4bd-07fc-413b-b011-528043412e05.png)

**Comment by SalahAdDin** [comment]
> > I had the same issue with @sgavathe After looking at their test-setup -- https://github.com/reactchartjs/react-chartjs-2/blob/master/test/setup.js
> > I just had to add the code below to eliminate the console errors while also rendering canvas in my jest tests
> > ```
> > import 'jest-canvas-mock';
> > 
> > class ResizeObserver {
> >   observe() {}
> >   unobserve() {}
> >   disconnect() {}
> > }
> > 
> > window.ResizeObserver = ResizeObserver;
> > ```
> 
> This solved our issue with testing react-chartjs-2. We are using vitest. So we needed the vitest version.
> 
> ```
> yarn add --dev vitest-canvas-mock
> ```
> 
> And appended in our setup.js file ![image](https://user-images.githubusercontent.com/15903512/217447705-089de1fa-cddb-4ede-8fbc-59bcacdb4a71.png)
> 
> Now our test is successful. ![image](https://user-images.githubusercontent.com/15903512/217449624-04a1cf39-8519-484c-ba61-85fbcd5a682e.png) ![image](https://user-images.githubusercontent.com/15903512/217449341-a9248ec0-4233-4aee-9786-954e354733ed.png) ![image](https://user-images.githubusercontent.com/15903512/217449376-c5f4a4bd-07fc-413b-b011-528043412e05.png)

**Vite** always amazes me a lot.

**Comment by nikolay-bennie** [comment]
why is this issue CLOSED?

**Comment by SalahAdDin** [comment]
> Why is this issue CLOSED?

They are tacitly indicating that we should use **vitest** XD.

**Comment by gaitat** [comment]
In order to test `react-chartjs-2` with jest and jsdom you don't need to mock the component or mock the canvas rendering. 
You can do visual regression testing of the react components.
I am using:
```
chart.js v4.4.0
react-chartjs-2 v5.2.0
jsdom v19.0.0
jsdom-screenshot v4.0.0
jest v27.4.3
jest-image-snapshot v5.2.0
@jest/globals v27.4.2
@testing-library/jest-dom v5.16.0
@testing-library/react v12.1.2
```
and in my `jest.config.js` I have:
```
testEnvironment: 'jsdom',
setupFilesAfterEnv: [
  '<rootDir>/jest.setup.afterEnv.js',
],
```
and in my `jest.setup.afterEnv.js` I have:
```
import { expect } from '@jest/globals';

import { configureToMatchImageSnapshot } from 'jest-image-snapshot';

const toMatchImageSnapshot = configureToMatchImageSnapshot({
  failureThresholdType: 'pixel',
  customSnapshotsDir: `${__dirname}/test/snapshots/`,
});

// extend Jest expect
expect.extend({ toMatchImageSnapshot });
```
With the setup above I can get an image out of the jest test of a generic `<Canvas />` component.
```
const getCanvasSnapshot = (canvas: HTMLCanvasElement, failureThreshold = 0) => {
  const image = canvas.toDataURL();
  const data = image.replace(/^data:image\/\w+;base64,/, '');
  const snapshot = Buffer.from(data, 'base64');

  expect(snapshot).toMatchImageSnapshot({ failureThreshold });
};

describe('<Canvas />', () => {
  test('render into canvas', () => {
    // @see https://medium.com/@pdx.lucasm/canvas-with-react-js-32e133c05258
    const Canvas = (props: any) => {
      const { draw, ...rest } = props;
      const canvasRef = React.useRef(null);

      React.useEffect(() => {
        const canvas = canvasRef.current as unknown as HTMLCanvasElement;
        const context = canvas.getContext('2d');
        draw(context);
      }, [draw]);

      return <canvas ref={canvasRef} {...rest} />;
    };

    const App = () => {
      const draw = (ctx: CanvasRenderingContext2D) => {
        ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
        ctx.fillStyle = '#0000ff';
        ctx.beginPath();
        ctx.arc(50, 50, 5, 0, 2 * Math.PI);
        ctx.fill();
      };

      return <Canvas draw={draw} width={100} height={100} />;
    };

    const { container } = render(<App />);

    const canvas = container.querySelector('canvas') as HTMLCanvasElement;
    getCanvasSnapshot(canvas);
  });
});
```

Extending this to `react-chartjs-2` is then simple. Couple issues that I had.
In browser mode the Chart can get its size from the parent container but when jest is running, the Chart could not get a size.
So I had to set
```
options.responsive = false; // only when jest is running
```
The setting of `options.maintainAspectRatio` was invariant to my application.

Then I had to set a width and height directly on the Chart component
```
  return (
    <Chart
      {...(isJestRunning() ? { width: '198' } : {})}
      {...(isJestRunning() ? { height: '202' } : {})}
      type="scatter"
      data={data as ChartData}
      options={options as ChartOptions}
      plugins={plugins}
    />
  );
```

Then the jest/jsdom test would produce an image. Note that `<Plot />` is just a simple wrapper around `<Chart />`.
```
describe('<Plot />', () => {
  let Wrapper: any;

  beforeEach(() => {
    window.ResizeObserver =
      window.ResizeObserver ||
      jest.fn().mockImplementation(() => ({
        disconnect: jest.fn(),
        observe: jest.fn(),
        unobserve: jest.fn(),
      }));

    // wrap the code with hooks; otherwise we get
    // Invalid hook call. Hooks can only be called inside the body of a function component. This could happen for one of the following reasons:
    Wrapper = () => (
      <Plot
        xScale={{ type: 'linear', min: 0, max: 1 }}
        yScale={{ type: 'linear', min: 0, max: 1 }}
        ...
        ...
      />
    );
  });

  afterEach(cleanup);

  test('render component', () => {
    const { container } = render(<Wrapper />);

    const canvas = container.querySelector('canvas') as HTMLCanvasElement;

    // make sure the canvas has the correct size
    expect(canvas.width).toEqual(198);
    expect(canvas.height).toEqual(202);

    // get an image of the canvas
    getCanvasSnapshot(canvas);
  });
});
```
