### ISSUE TITLE
optional dependency canvas breakes CI builds

### ISSUE THREAD

**Issue by handjunyoung** [jerairrest/react-chartjs-2#160]
After #141 , there added `canvas` package into `optionalDependencies`

However, it breakes `npm install` or `yarn install` since prerequisites (such as cario, gpp, etc) is not available in CI execution environments.

Please look into it

**Comment by jerairrest** [comment]
hmm... shouldn't canvas-prebuilt work as a fallback? Are you getting a specific error related to canvas?

**Comment by Viral-Inc** [comment]
+1

**Comment by jerairrest** [comment]
Fixed in https://github.com/jerairrest/react-chartjs-2/releases/tag/2.4.1
