### ISSUE TITLE
Tooltip title with custom font not rendering properly at first

### ISSUE THREAD

**Issue by miguelperes** [jerairrest/react-chartjs-2#161]
I have a line chart and I want to set a custom font to it (of every part of the chart, from ticks to tooltip). 

But I'm having issues with the tooltip title: the first time I hover a point in the chart, the tooltip title is showing the default font, and then in all the other attempts shows the correct one. Same thing happens every time I refresh my page: first attempt renders the title with the default font.

First time I hover a point after page refresh:
![screen shot 2017-07-11 at 12 18 36](https://user-images.githubusercontent.com/9100668/28075908-48f78ff8-6633-11e7-8ba6-ecf085720d3f.png)

All other hover attempts:
![screen shot 2017-07-11 at 12 19 35](https://user-images.githubusercontent.com/9100668/28075909-48f8f9b0-6633-11e7-8780-ad2e0eda423e.png)

However, **notice the ticks and tooltip content already show the proper font the first time**, the issue is happening only with the tooltip title!

This is how I'm setting the font, in the options object of the line chart:
```
const lineChartOptions = {
  responsive: true,
  defaultFontFamily: Chart.defaults.global.defaultFontFamily = 'fabriga',
  ...
}
```

I also tried setting specifically the tooltip title font, before defining my chart component:
```
import { defaults } from 'react-chartjs-2'
defaults.global.tooltips.titleFontFamily = 'fabriga'
```

And also tried to set it in the options object that gets passed to the chart:
```
const lineChartOptions = {
  ...
  tooltips: { titleFontFamily: 'fabriga' }
  ...
}
```

But the behavior is the same.
Anyone know the reason of this? What am I doing wrong?

**Comment by robbieyng** [comment]
I was able to set the default font for everything like so:
```
import { Doughnut, defaults } from 'react-chartjs-2';
defaults.global.defaultFontFamily = 'Architects Daughter';
```

**Comment by shaunlandau1973** [comment]
I too noticed strange font flicker artifacts but only while dev tools are open and causing cached fonts to be reloaded. With dev tools closed robbieyng's strategy does the trick.

**Comment by miguelperes** [comment]
I'm going to try it out later, and will come back to tell if that worked for me, thanks!

**Comment by miguelperes** [comment]
Unfortunately robbieyng strategy yields the same result for me: every font in my chart's canvas is correct, but when I hover a point for the first time, the tooltip title of this point renders the default font, and after that, all the other hover attempts renders the correct font.

Maybe this is happening because I'm using a custom font? But if that's the case, why all the other parts of the chart are loading the font properly?

**Comment by bgraf-zlab** [comment]
Hey all!

I had the same problem, but solved it for now by using the `FontFaceSet.onloadingdone` event handler (see https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet) to re-render the chart after all fonts are there and using `fontfaceobserver` (https://www.npmjs.com/package/fontfaceobserver) as a fallback for IE. I set a default font using the `Chart.default.[...]` settings. This seems to solve the problem in all environments I could test for now...

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
