### ISSUE TITLE
Global Chart pluginservice causing duplicate events

### ISSUE THREAD

**Issue by ericmcgregor** [jerairrest/react-chartjs-2#164]
I'm having a little difficulty understanding how i should use your gobal pluginservice.  When i register a "afterDraw" action on componentWillMount, it actually registers a unique function for every chart that gets mounted.  So, even though i may only have one chart on the screen, if i've looked at a few charts before that, it will call afterDraw multiple times.

chartjs seems to support inline plugins, however, if i try and add an 'afterdraw' to options.plugins which gets passed into your component, nothing fires. 

could you please help me understand what i'm doing wrong?  fist time using chartjs and your react wrapper.  so far so good, but this one has me stumped.

**Comment by paulcredmond** [comment]
I'm having the same problem. I'm using `beforeDraw` and the ref is being lost when I browse to a different URL and come back to the one with the charts on it.

**Comment by paulcredmond** [comment]
@ericmcgregor Did you ever find a solution?

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
