### ISSUE TITLE
Disable legends shown since last update

### ISSUE THREAD

**Issue by nicklayb** [jerairrest/react-chartjs-2#165]
Since I updated the package to it's last version, legends are shown even if they are disabled

react-chartjs-2 version : 2.5.1
chartjs options : 
```
{
    cutoutPercentage: 80,
    maintainAspectRatio: false,
    legend: {
        display: false
    },
    animation: {
        animateRotate: false
    }
}
```
I rolled back to 2.4.0 and everything is fine

**Comment by jerairrest** [comment]
Hmmm... we did add a legend props in for custom legends. Let me investigate

**Comment by jerairrest** [comment]
Oops. There's was an accidental breaking change on:

https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js#L253

If you pass your legend in as props to the chart component that should resolve your issue. 

Sorry!

**Comment by nicklayb** [comment]
Alright, it worked!
I just passed my options.legend in props to the component.

Thank you !

**Comment by emmiz** [comment]
I know this thread is closed but I was just wondering, are you going to fix this problem? The passing of legend as prop to the chart works, but I think it would be better if you could pass it as options like before.

**Comment by jerairrest** [comment]
@emmiz This is an easy fix I'll revert this shortly.

**Comment by jerairrest** [comment]
@emmiz Hmmm... not that I look at how the default props are for this package it almost makes more sense to be separate in a way. I'm really torn on this one. :/

**Comment by emmiz** [comment]
@jerairrest I understand your concern, but since the module is built upon chart.js that pass the legend as an option to the chart, I think it would be wise to follow the same approach.

**Comment by nicklayb** [comment]
As @emmiz, I think you should keep it in option, also because it’s a breaking change that doesn’t change any internal behaviour

**Comment by jerairrest** [comment]
I just released 2.5.3 that should give the ability to use either prop. https://github.com/jerairrest/react-chartjs-2/releases/tag/2.5.3

Thanks again guys for pointing this out!

**Comment by emmiz** [comment]
Super 😄 👍 Thx @jerairrest

**Comment by AkshayAnjAmerica** [comment]
sometimes legend is showing even though it is set as false. version 4.4.2.
