### ISSUE TITLE
Is it possible to expose Scatter Chart to type definition files?

### ISSUE THREAD

**Issue by tks46** [jerairrest/react-chartjs-2#170]
Thanks to react-chartjs-2,it helps me much.
i detected scatter chart  is exposed a couples day ago.
however im now working with Typescript .
is it possible to export scatter to type definition files?

i just expect something like  this 
`export class Scatter extends React.Component<ChartComponentProps, any>{}`
appears in index.d.ts

im new to typescript so please let me know if i m doing something wrong .

**Comment by jerairrest** [comment]
You are correct. I just added that in 2.5.5

https://github.com/jerairrest/react-chartjs-2/releases/tag/2.5.5

Thanks for point this out.
