### ISSUE TITLE
save the chart in PDF usinig Jspdf 

### ISSUE THREAD

**Issue by mahermagdy** [jerairrest/react-chartjs-2#171]
@jerairrest 
Hi 
 I need to save the chart in PDf file using JsPDF like the example below using JsPDF and chartJS
Example:- 
https://fiddle.jshell.net/kL68ey5z/94/

so I need the steps or the solution to extract the chart in PDF( as the image) .

**Comment by mahermagdy** [comment]
@DocX @octalmage  @mosanger @nrdobie @soska @
Hi Guys
Anyone can help me

**Comment by lucasapereira** [comment]
I need the same solution.

**Comment by octalmage** [comment]
No clue. This is just a wrapper for ChartJS, so I would check with them!

**Comment by octalmage** [comment]
https://fiddle.jshell.net/kL68ey5z/105/

**Comment by jerairrest** [comment]
Thanks @octalmage .

Closing

**Comment by Tommy92708** [comment]
Solution link is broken, can someone post the solution to this issue?

**Comment by alvinjulian** [comment]
Solution link is still broken. Could someone post the solution again? Would appreciate that 👍

**Comment by NakedFool** [comment]
+1 - i also need this solution

**Comment by arfath77** [comment]
```
import PdfConverter from 'jspdf';
import DomToImage from 'dom-to-image';

const convertToPdf = () => {
    const canvas= document.querySelector('.canvas')[0];
    const imgWidth = 190;
    const pdf = new PdfConverter('p', 'mm');
    DomToImage.toPng(canvas).then(dataURL => {
           const imgHeight = (canvas.clientHeight * imgWidth) / canvas.clientWidth;
           pdf.addImage(dataURL, 'PNG', 10, 20, imgWidth, imgHeight);
     });
     pdf.save('save.pdf');
};
```
