### ISSUE TITLE
Smaller default width

### ISSUE THREAD

**Issue by gfpacheco** [jerairrest/react-chartjs-2#172]
I have a few chart on my page, I didn't set the charts width so they could scale down with the screen width. But something was breaking on really small screens.

I struggled for 3 hours trying to find the reason until I find out that my chart was 300px wide instead of 295px and then another half an hour to find out it was being set by this lib.

I'm not sure what value it should be, but I think it shouldn't prevent the charts from becoming smaller.

**Comment by jerairrest** [comment]
Do you have a wrapping component around the chart?

**Comment by gfpacheco** [comment]
Just a simple div without any styles

**Comment by jerairrest** [comment]
If I recall correctly canvas does needs a fix width and height to start so there are default props for height and width of 150 and 300 respectively. Does turning the responsive flag on make any sort of difference?

**Comment by gfpacheco** [comment]
It doesn't since it's already on by default

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
