### ISSUE TITLE
Add React 16.0 beta as correct peer dependency

### ISSUE THREAD

**Issue by Kulfon93** [jerairrest/react-chartjs-2#175]
Hello. I'm testing how React 16.0 beta will work with my project where I use react-chartjs-2.
I noticed that there is warning about wrong peer depencency of React 16.0 beta.
![image](https://user-images.githubusercontent.com/3399141/28995178-1b49dbac-79e2-11e7-86d5-2c5f5de7dac0.png)

Let's talk about adding React 16.0 beta as correct peer dependency.

**Comment by jerairrest** [comment]
I'll do you one better and just add it in as a peer dependency. :) https://github.com/jerairrest/react-chartjs-2/releases/tag/2.5.6
