### ISSUE TITLE
Setting Axis Width

### ISSUE THREAD

**Issue by davidmcooper** [jerairrest/react-chartjs-2#177]
I've been unable to determine how to set a fixed-width for the axis label.  I'm attempting to display three separate charts.js plots, aligned vertically.  The values being rendered are on vastly different scales, causing the plots to be mis-aligned.  Is there a way to set the width of the axis to a fixed value to ensure the plots align regardless of the axis labels?

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
