### ISSUE TITLE
xAxis Tick Padding

### ISSUE THREAD

**Issue by yussinsharp** [jerairrest/react-chartjs-2#178]
I need to able to push my x-axis tick labels further away from the x-axis. I can do this on the y-axis with `padding` variable but I cannot figure out how to do it with x-axis. For the sake of speed, I did not attach the full code. If required, just ask.

![screen shot 2017-08-09 at 8 11 41 pm](https://user-images.githubusercontent.com/1894595/29152924-0b7fb54c-7d3f-11e7-8d13-426aa4ff75d8.png)

```js
const options = {
  // maintainAspectRatio: false,
  scales: {
    yAxes: [{
      ticks: {
        fontSize: 18,
        fontFamily: 'Gotham-Medium',
        fontColor: colorMap['primaryBlue'],
        maxRotation: 0.00001,
        padding: 20,
        labelOffset: 20,
        callback(value, index) {
           if (index % 2 == 0) return '';
           return value;
        },
      },
      beginAtZero: true,
      gridLines: {
        drawTicks: false,
      },
    }],

    xAxes: [{
      ticks: {
        fontSize: 18,
        fontFamily: 'Gotham-Medium',
        fontColor: colorMap['primaryBlue'],
        maxRotation: 0.00001,
        padding: 20,
        labelOffset: 20,
        callback(value, index) {
           if (index % 2 == 0) return '';
           return value;
        },
      },
      gridLines: {
        tickMarkLength: 40,
        offsetGridLines: true,
        display: true,
        drawTicks: false,
        drawOnChartArea: false,
      },

    }]
  },
};

<LineChart
  options={options}
/>
```

**Comment by SantiagoMoyano** [comment]
I've got the `padding` atribute inside `xAxes` just like you do, and it's working!

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.

**Comment by mtariverx** [comment]
It works. Thanks
