### ISSUE TITLE
React chart JS requires moment.js

### ISSUE THREAD

**Issue by MaxiMacko** [jerairrest/react-chartjs-2#179]
Hello. I've faced an issue with connecting react-chartjs-2 lib to my project. When I try to render a simple Line chart with such data:

`const testData = {
  labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
  datasets: [{
    label: '# of Votes',
    data: [12, 19, 3, 5, 2, 3],
    backgroundColor: [
      'rgba(255, 99, 132, 0.2)',
      'rgba(54, 162, 235, 0.2)',
      'rgba(255, 206, 86, 0.2)',
      'rgba(75, 192, 192, 0.2)',
      'rgba(153, 102, 255, 0.2)',
      'rgba(255, 159, 64, 0.2)'
    ],
    borderColor: [
      'rgba(255,99,132,1)',
      'rgba(54, 162, 235, 1)',
      'rgba(255, 206, 86, 1)',
      'rgba(75, 192, 192, 1)',
      'rgba(153, 102, 255, 1)',
      'rgba(255, 159, 64, 1)',
    ],
    borderWidth: 1,
  }],
};`

I receive a warning about "Module not found: Error: Can't resolve './locale' in /node_modules/moment/src/lib/locale". I don't need moment.js in my project and this warning has never occured before I started to use react-chartjs-2. How can I disable it if it possible? Thank you.

**Comment by tusbar** [comment]
Chart.js itself depends on moment – so yes, react-chartjs-2 does too.

See https://github.com/chartjs/Chart.js/issues/4303.

**Comment by jerairrest** [comment]
Good call @tusbar. Closing.
