### ISSUE TITLE
No version match found for npm:react@^16.0.0

### ISSUE THREAD

**Issue by PrimeObjects** [jerairrest/react-chartjs-2#185]
I am using 15.4.2, do I have to upgrade my react?

 "dependencies": {
    "babel-polyfill": "^6.22.0",
    "babel-runtime": "^6.22.0",
    "jspm-github": "^0.13.18",
    "jspm-registry": "^0.4.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-intl": "^2.2.3",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.2",
    "redux": "^3.6.0"
  },

**Comment by jerairrest** [comment]
Nope! We have a peer dependency of React 15 and 16 that can be found here. https://github.com/jerairrest/react-chartjs-2/blob/master/package.json#L66

**Comment by PrimeObjects** [comment]
sorry have to open this again, I ran into the error related to version of react, please see attached screenshot below.
![charts2](https://user-images.githubusercontent.com/3459952/30004515-c5adbe6a-9085-11e7-9ca1-4c7f9c110016.JPG)

Thanks
Gary
