### ISSUE TITLE
Chart does not render in IE11

### ISSUE THREAD

**Issue by frat78** [jerairrest/react-chartjs-2#189]
It works fine in all browsers except for IE.  There are no errors, the page itself loads and ajax calls are made, but the line chart simply does not render.  I am using version 2.6.2

**Comment by frat78** [comment]
I've added the necessary polyfill to get passed the object.assign error, so the page is showing no errors.  The chart simply isn't showing up in IE.

**Comment by jerairrest** [comment]
Sorry I don't have IE available to me. Does the example site work for you? http://jerairrest.github.io/react-chartjs-2/

**Comment by frat78** [comment]
The examples do work actually.  I did some more digging, and I narrowed it down to one small thing. 
 It appears as if the problem IE has is with the time scale code below in bold (Chrome, Firefox, have no issues with it):

<Line
        data={this.props.chartData}
        options={{
          scales: {
          xAxes: [{
            margin: 0,
            padding: 0,
            type: 'time',
            unit: 'day',
            unitStepSize: 1,
            ticks:{
              bounds: 'label',
              beginAtZero:true,
              minRotation: 45
            },
            **_time: {
              displayFormats: {
                 'day': 'MMM DD'
              }}_**
            }]
          },
          responsive: true,
          hover: {
            mode: 'index',
            intersect: false
          },
          tooltips: {
            position: 'average',
            caretSize: 20,
            mode: 'index',
            intersect: false,
            mode: 'label',
            callbacks: {
                label: function(tooltipItem, data) {
                    var corporation = data.datasets[tooltipItem.datasetIndex].label;
                    var valor = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];

                    // Loop through all datasets to get the actual total of the index
                    var total = 0;
                      // if (data.datasets[i].label != "Limit" && !data.datasets[i]._meta[0].hidden)
                    for (var i = 0; i < data.datasets.length; i++)
                        total += parseInt(data.datasets[i].data[tooltipItem.index].y);

                    // If it is not the last dataset, you display it as you usually do
                    if (tooltipItem.datasetIndex != data.datasets.length - 1) {
                        return corporation + " : " + valor.y;
                    } else { // .. else, you display the dataset and the total, using an array
                        return [corporation + " : " + valor.y, "Total : " + total];
                    }
                }
            }
          },
          title:{
            display:this.props.displayTitle,
            text:this.props.selectedGroup + ' Global Concurrent Users ' + this.props.timePeriod,
            fontSize:25
          ,
          legend:{
            display:this.props.displayLegend,
            position:this.props.legendPosition
          }
        }}}
      />

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
