### ISSUE TITLE
Control multiple line charts using a single legend.

### ISSUE THREAD

**Issue by danielparkk** [jerairrest/react-chartjs-2#191]
Is there any way to only render one legend on a chart, but have that legend control all the other charts on the page? This goes without saying that each chart for a certain set of data will have the same labels/fields, just different values.

I feel like I need to set a custom function for the legend onClick functionality and try and grab all the other line charts and mess with them that way, but I haven't been able to successfully reference any of the other charts.

Any ideas on how to do this?

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
