### ISSUE TITLE
[Question] Can I manually fire the chart redrawing ?

### ISSUE THREAD

**Issue by desirelabs** [jerairrest/react-chartjs-2#192]
Hello, I'm wondering if thie was possible to manually fire the chart's redrawing. Because I actually updating the state of the chart to display different data when a custom filter is selected in my app. For instance I want the chart to display only a restricted set of data when on checkbox's checked. The problem is when using redraw, it redraws the chart because the state changed, once, then a second time when the data effectively changed. I only want it to redraw when a specific state property is updated, not all of them.
Is it supposed to be possible ?
Thanks

**Comment by dbrodie122** [comment]
@desirelabs I had the same challenge.  You'll need to use componentWillRecieveProps

I solved it by setting a property in state, `shouldRedraw: false`. Then, in `componentWillReceiveProps`, do a check for the specific prop that you need the redraw to happen for.

In my case, I needed the size of the chart and the fonts to change depending on the window size.
1) Passed down the windowSize prop. I was listening for changes in a component higher in the tree.
2) In my chart component that I needed to redraw:
```
componentWillReceiveProps(nextProps){
  if(nextProps.windowSize !== this.state.windowSize){
    this.setState({shouldRedraw: true})
  } else {
   this.setState({shouldRedraw: false})
  }
}
```  
3. Then, for the redraw prop on my chart component, pass it the redraw from state.
`<Chart data={data} redraw={this.state.shouldRedraw}/>`

This way, the redraw only triggers when it receives the correct prop, and not on all state changes.

**Comment by grantglidewell** [comment]
If anyone else need this info, i took dbrodie122's solution but used an event listener in componentDidMount instead of looking for new props.

`  constructor(props) {
    super(props)
    this.state ={
      shouldRedraw: false
    }
  }
  componentDidMount() {
    window.addEventListener('resize', this.setRedraw, false)
  }
  componentWillUnmount() {
    window.removeEventListener('resize', this.setRedraw, false)
  }
  setRedraw = () => {
    return this.setState({shouldRedraw: true})
  }`

and then the same as step 3 from dbrodie122

**Comment by renetanikolova** [comment]
Btw, using redraw does not work for me - it redraws, yes, but the chart starts blinking - it is not really user-friendly. Is this only happen to me? I am thinking that it blinks because the state is changed more than once - but that is just my assumption.

**Comment by brunoandradebr** [comment]
When I use <Bar data={data} options={options} plugins={plugins} **redraw={true}** />

And inside plugins I have : 

```
beforeInit: (chart) => {
   chart.data.labels.forEach((e, i, a) => {
       if (/\n/.test(e)) {
           a[i] = e.split(/\n/)
       }
   })
}
```
This plugin breaks a line for every label that have a "\n". ex : labels : ["My label", "My\nSecond label"]

My issue is, when redraw is set to true, for every forEach plugin iteration, my whole chart is been redraw like I'm changing a state variable, and it runs animation every iteration. How to handle this the right way ? 

thanks!

**Comment by Pringels** [comment]
@brunoandradebr please open a new issue for the problem you are describing, ideally with a full code example and/or sandbox

**Comment by brunoandradebr** [comment]
@Pringels My bad! It was a problem with react hooks. My chart component were updating ever that a page component property updates, I resolved encapsulating my chart component with React.useMemo. Everything is working as espected. Thanks!

**Comment by Pringels** [comment]
Awesome :) I'm glad you came right!
