### ISSUE TITLE
Zoom and Pan

### ISSUE THREAD

**Issue by krishna444** [jerairrest/react-chartjs-2#195]
Is it possible to implement zooming and panning using this package?

**Comment by osnysantos** [comment]
Please try this issue https://github.com/jerairrest/react-chartjs-2/issues/107

**Comment by krishna444** [comment]
Thanks for the reply. Unfortunately, I followed issue #107, and there is no zoom or pan. 

```
import React from 'react';
import {Line} from 'react-chartjs-2'
import * as zoom from 'chartjs-plugin-zoom';
var options={
pan:{
    enabled:true,
    mode:'x'
 },
zoom:{
    enabled:true,
    mode:'xy'
}
}

```
The render Method:

```
render(){
    return <Line data={data} options={options} />
}
```
I am really stuck in this part.

**Comment by jerairrest** [comment]
Hey @krishna444, I just tried with the information provided and it seems to work for me. Are you getting a particular error?

**Comment by unofang** [comment]
Hi @jerairrest, I think I have the same issue with @krishna444, The terminal shows me:
W20171130-23:06:31.936(11)? (STDERR) ReferenceError: window is not defined
W20171130-23:06:31.936(11)? (STDERR)     at Object.<anonymous> (/Users/Uno/Google Drive/Working with Wei/Deakin Sports Analytics/repos/data_dashboard/deakin-sports-analytics/node_modules/hammerjs/hammer.js:2643:4)
W20171130-23:06:31.936(11)? (STDERR)     at Module._compile (module.js:612:30)
W20171130-23:06:31.936(11)? (STDERR)     at Object.Module._extensions..js (module.js:623:10)
W20171130-23:06:31.937(11)? (STDERR)     at Module.load (module.js:531:32)
W20171130-23:06:31.937(11)? (STDERR)     at tryModuleLoad (module.js:494:12)
W20171130-23:06:31.937(11)? (STDERR)     at Function.Module._load (module.js:486:3)
W20171130-23:06:31.937(11)? (STDERR)     at Module.require (module.js:556:17)
W20171130-23:06:31.937(11)? (STDERR)     at require (internal/module.js:11:18)
W20171130-23:06:31.937(11)? (STDERR)     at npmRequire (/Users/Uno/Google Drive/Working with Wei/Deakin Sports Analytics/repos/data_dashboard/deakin-sports-analytics/.meteor/local/build/programs/server/npm-require.js:133:10)
W20171130-23:06:31.937(11)? (STDERR)     at Module.useNode (packages/modules-runtime.js:687:18)

**Comment by krishna444** [comment]
Hi @jerairrest,

I was late to reply, but I still could not implement the zoom and pan in chart. I have uploaded my sample react program in my github repository 

https://github.com/krishna444/react-chart-zoom 

I have written build instructions on README.md file. Please have a look at this program, it runs but zoom and pan does not work!

**Comment by Mrostgaard** [comment]
Anyone that have gotten this to work? I have no clue what is wrong, but it doesn't work on mine either..

**Comment by waleedshkt** [comment]
@krishna444, 
Check out [this Stackoverflow issue](https://stackoverflow.com/questions/46346078/zoom-and-pan-in-react-chartjs-2)

Hope it helps.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Comment by raevillena** [comment]
I do not think there is well documented way of implementing pan and zoom with react yet. I am currently implementing it and experiencing malfunctions, unlike to the pure js. im not expert in react or whatsoever but i am currently using webpack, imported this repo, zoom plugin and hammer. hammer gets confused with wheel when the page has unfit page (there is scroll up and down). still the plugin works with chart.js in pure js. but with react. it looks like i have to disect this fork to properly implement things.
