### ISSUE TITLE
Linear xAxis can't use LinearTickOptions

### ISSUE THREAD

**Issue by ersinciftci** [jerairrest/react-chartjs-2#196]
I'm using Typescript, and created a `Line` chart with `xAxes: [{type: 'linear'}]` option, but I can't use the options in `LinearTickOptions` because by default xAxis' type is `category` so only the options in `TickOptions` is available. And since it's strongly-typed, even after setting `xAxes: [{type: 'linear'}]`, `LinearTickOptions` still isn't available to use. Any workaround?

**Comment by lee1994522** [comment]
@ersinciftci Any solution for this issue now?

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
