### ISSUE TITLE
32 labels, only 16 appear

### ISSUE THREAD

**Issue by desirelabs** [jerairrest/react-chartjs-2#199]
Hi, this is a weird behaviour : I'm having charts which updates on specific events. The datasets and labels are dynamically updated. The problem is that only half the labels appear on unknown circumstances. See below.

![capture d ecran 2017-09-27 a 15 49 17](https://user-images.githubusercontent.com/24223583/30917129-83eac44a-a39b-11e7-8440-b47704665749.png)

For instance I have to display progression of data during time. My labels are the dates which I'm formating using momentsjs. When my event tells to show only on the 32 last days, only 16 labels appear. The best part is that when inspecting, the props label are indeed 32. 

<img width="230" alt="capture d ecran 2017-09-27 a 15 51 36" src="https://user-images.githubusercontent.com/24223583/30917235-d5409e82-a39b-11e7-8a4f-6f01942bc111.png">

Am I the only one with this ? Is it on purpose ?
Thanks

**Comment by AoDev** [comment]
@desirelabs Ok found it. There is a "autoSkip" option that is enabled by default.

```
    xAxes: [
      {
        ticks: {
          autoSkip: false
        }
      }
    ]
```
I haven't investigated how to avoid overlapping. It happens with my chart but it's much better than disappearing, since it's not an arithmetic / serie scale.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
