### ISSUE TITLE
Elements and Legend options

### ISSUE THREAD

**Issue by GShockere** [jerairrest/react-chartjs-2#206]
When i changed the background color of the rectangle using the element: { rectangle: {backgroundColor: "white"}}, the elements background color changed but the color on the legend became gray. what to do to make it the same? 
![wah](https://user-images.githubusercontent.com/32511650/31324179-9f9255d2-ace2-11e7-933e-0374c5d7f830.png)

**Comment by dbrodie122** [comment]
Pass in colors with your data prop that you pass to your component.

Follow the example here:
https://github.com/jerairrest/react-chartjs-2/blob/master/example/src/components/bar.js
