### ISSUE TITLE
First and Last Points joining on re-render

### ISSUE THREAD

**Issue by sahilanguralla** [jerairrest/react-chartjs-2#209]
Hi,
I am trying to draw a line graph. The issue is, on re-render first and the last point gets joined. This looks like unexpected behavior. I have added an image of the same.
![Graph Image](https://imgur.com/download/oNR3p59 "Graph Image")

Thanks

**Comment by jerairrest** [comment]
Can you upload your dataset as well?

Thanks!

**Comment by sahilanguralla** [comment]
The dataset is dynamically generated. Below given is current graph and dataset:
![Graph](https://imgur.com/download/EmAlCdM "Graph")
> datasets = [
> &nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;"data":&nbsp;[
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;17,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"8809.22"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;18,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"7872.22"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;19,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"7479.22"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;20,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"5271.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;21,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"302.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;22,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"209.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;29,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"32965.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;2,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"24965.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;4,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"24865.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;6,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"24695.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;9,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"9423.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;11,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"8178.26"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;13,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"10495.70"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;14,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"10383.70"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"x":&nbsp;16,
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"y":&nbsp;"10383.70"
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;],
> &nbsp;&nbsp;&nbsp;&nbsp;"label":&nbsp;[],
> &nbsp;&nbsp;&nbsp;&nbsp;"fill":&nbsp;true,
> &nbsp;&nbsp;&nbsp;&nbsp;"lineTension":&nbsp;0.2,
> &nbsp;&nbsp;&nbsp;&nbsp;"backgroundColor":&nbsp;"transparent",
> &nbsp;&nbsp;&nbsp;&nbsp;"borderWidth":&nbsp;1.5,
> &nbsp;&nbsp;&nbsp;&nbsp;"borderColor":&nbsp;"#afafaf",
> &nbsp;&nbsp;&nbsp;&nbsp;"borderCapStyle":&nbsp;"round",
> &nbsp;&nbsp;&nbsp;&nbsp;"borderDash":&nbsp;[],
> &nbsp;&nbsp;&nbsp;&nbsp;"borderDashOffset":&nbsp;0,
> &nbsp;&nbsp;&nbsp;&nbsp;"borderJoinStyle":&nbsp;"round",
> &nbsp;&nbsp;&nbsp;&nbsp;"pointBackgroundColor":&nbsp;[
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#06b08a",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#06b08a",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#e21f2b",
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"#06b08a"
> &nbsp;&nbsp;&nbsp;&nbsp;],
> &nbsp;&nbsp;&nbsp;&nbsp;"pointBorderColor":&nbsp;"#fff",
> &nbsp;&nbsp;&nbsp;&nbsp;"pointBorderWidth":&nbsp;0,
> &nbsp;&nbsp;&nbsp;&nbsp;"pointHoverRadius":&nbsp;6,
> &nbsp;&nbsp;&nbsp;&nbsp;"pointHoverBorderColor":&nbsp;"rgba(220,220,220,1)",
> &nbsp;&nbsp;&nbsp;&nbsp;"pointHoverBorderWidth":&nbsp;2,
> &nbsp;&nbsp;&nbsp;&nbsp;"pointRadius":&nbsp;6,
> &nbsp;&nbsp;&nbsp;&nbsp;"pointHitRadius":&nbsp;10
> &nbsp;&nbsp;}
> ]

**Comment by sahilanguralla** [comment]
Sorry, my bad. I was appending data to old dataset before clearing it. 

BTW I have a question not related to this library. How can we (deep) clone a raw javascript object?

**Comment by jerairrest** [comment]
https://lodash.com/docs/4.17.4#cloneDeep is what you're probably looking for. :)
