### ISSUE TITLE
Range Column Chart support

### ISSUE THREAD

**Issue by elghali** [jerairrest/react-chartjs-2#211]
I am wondering if at some time the range column chart will be supported 
![capt12ure](https://user-images.githubusercontent.com/11211342/31765474-26952054-b4cd-11e7-980c-0fc13a2aa98e.PNG)

**Comment by jerairrest** [comment]
Isn't this just a bar chart with no zero axis kinda like this?

http://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by elghali** [comment]
well it's not the same, but eventually I used this solution, and set the visibility of the lowest bars to 0, so it looked like a range column chart as show above

**Comment by sarojkumar14** [comment]
can you please share sample
