### ISSUE TITLE
Can't make chart responsive

### ISSUE THREAD

**Issue by DangerZoneIO** [jerairrest/react-chartjs-2#212]
How do you make the chart responsive?
I am using webpack.

**Comment by dbrodie122** [comment]
I'm pretty sure the charts are responsive by default - are you limiting it's size with your container and css?  Can you post an example of your code?

**Comment by jerairrest** [comment]
This may also be due to Chart.js 2.7 being weird with responsive charts. https://github.com/chartjs/Chart.js/issues/4737

2.6 still works. :)

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
