### ISSUE TITLE
onLegendClick?

### ISSUE THREAD

**Issue by jbbae** [jerairrest/react-chartjs-2#213]
Hi,

I'm wondering if there's a handler for the legends. So as it is right now, if you click on a legend, it basically filters out that category from the dataset. My project requires controlling other external components in conjunction with the dataset filtering. Any suggestions?

**Comment by dbrodie122** [comment]
@nickbae91 

You can give it a click handler as part of its options object.

http://www.chartjs.org/docs/latest/configuration/legend.html

For example:
```
const alertHello = () => {
  alert('hello!');
}

const options = {
  legend: {
    onClick: alertHello
  }
}
```
Then pass the options to the component.
 `<Pie data={data} height={150} width={200} options={options}/>`

**Comment by nickbae91** [comment]
Hey @dbrodie122 thanks a ton for the response! Was swamped with work so didn't have a chance to get to this.

So it seems that your method works to define a function for the onClick event. However, this seems to override the default function within the canvas of "filtering out" the category from the chart (in my case, it's a Pie chart).

Basically, all I wanted was to retain this "filtering out the chart" functionality, as well as get access to the name/label of the legend being clicked, so I can reflect that "filtering" in other components. I tried "console.log" on the object being passed to the click event handler ("alertHello" in your example), and it didn't seem to contain that information.

I feel I'm being dumb and misunderstanding a part of the documentation, but was wondering what would best way to achieve this?

**Comment by dbrodie122** [comment]
@nickbae91 Ah I misunderstood your question, sorry about that.

If you take a look at the examples at http://jerairrest.github.io/react-chartjs-2/ , the very last one is "Legend Handlers Example."  Is that the behavior you're looking for?

This is the code for that example in examples/src/components/legend-handlers.js

I confess I haven't fiddled with it myself except to remove the `onHover` handler to make sure I could console.log the item.  It looks like you'll get access to the item index as well as the label text, so you should be able to grab those and use them to filter your data object that you're passing to the chart.

```javascript
import React from 'react';
import {Pie} from 'react-chartjs-2';

const data = {
  labels: [
    'Red',
    'Green',
    'Yellow'
  ],
  datasets: [{
    data: [300, 50, 100],
    backgroundColor: [
    '#FF6384',
    '#36A2EB',
    '#FFCE56'
    ],
    hoverBackgroundColor: [
    '#FF6384',
    '#36A2EB',
    '#FFCE56'
    ]
  }]
};

const legendOpts = {
  onClick: (e, item) => alert(`Item with text ${item.text} and index ${item.index} clicked`),
  onHover: (e, item) => alert(`Item with text ${item.text} and index ${item.index} hovered`),
};

export default React.createClass({
  displayName: 'LegendExample',

  getInitialState() {
    return {
      legend: legendOpts
    }
  },

  applyLegendSettings() {
    const { value } = this.legendOptsInput;

    try {
      const opts = JSON.parse(value);
      this.setState({
        legend: opts
      });
    } catch(e) {
      alert(e.message);
      throw Error(e);
    }
  },

  render() {
    return (
      <div>
        <h2>Legend Handlers Example</h2>
        <p>Hover over label and click</p>
        <Pie data={data} legend={this.state.legend} />
      </div>
    );
  }
})
```

**Comment by sdzharkov** [comment]
Adding on to this, is it possible to get all of the legend items instead of just an item? 

Currently, the function above returns the label you clicked on, but I'm trying to develop a feature where clicking on one label will hide all of the other labels (similar to how plotly.js does it (https://react-plotly.js-demo.getforge.io/  if you double click on a legend item, it hides all the other items)

**Comment by LorisIX** [comment]
Hi @nickbae91, did you find a solution ? I tried this code but it still doesn't work :/ I really need the solution ! :) Thank you

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
