### ISSUE TITLE
Control Pie Chart & Legend Area separately

### ISSUE THREAD

**Issue by jbbae** [jerairrest/react-chartjs-2#214]
Hi,

I am trying to make my Pie chart mobile-friendly, but using the dimension properties for the <Pie> component seems to resize the whole canvas, making the Pie chart unnecessarily small with a lot of unused white space (see image). Is it possible to make just the Pie chart bigger?

![image](https://user-images.githubusercontent.com/12439968/31860029-9214e9a8-b6d1-11e7-8bb4-7a7988f4b29d.png)

**Comment by jerairrest** [comment]
@dbrodie122 Thanks so much for the help!!! I really appreciate it.

**Comment by dbrodie122** [comment]
@jerairrest thank YOU for making this library.  It saved my job, no joke!

**Comment by narenvaishnavi** [comment]
@jerairrest I am trying to do the same using react-chartjs-2. However, for plotting Pie chart, i am getting undefined at the center of Pie chart. Can anyone help me how can we remove that?

**Comment by Pringels** [comment]
@narenvaishnavi please open a new issue with code examples and a sanbox reproducing the bug you are describing. Closing this issue for now.
