### ISSUE TITLE
Chart component resizes width but not height when parent is resized

### ISSUE THREAD

**Issue by jeghers** [jerairrest/react-chartjs-2#217]
I've tried every hack and stacktrace article offering a solution - none work so far.  I've really got to figure out this showstopping problem :-(

I have a "Card" component which gets added into a draggable dashboard-style layout component (react-grid-layout).  "CardPanel" is my wrapper around the responsive grad layout parent.  The Card can resize nicely in the CardPanel parent.  Into the Card I insert my "BarChart" (which is a wrapper class around "HorizontalBar".

Here is how the card is added to the CardPanel...

              <CardPanel initialLayouts={initialLayouts}>
                <Card key="1" close>
                  <BarChart fsInfo={fsInfo} style={{ width: '100%', height: '100%' }} />
                </Card>
                <Card key="2">
                  <span className="text">2</span>
                </Card>
                  ... etc etc
              </CardPanel>

Here is how the CardPanel wraps it's Card children (to satisfy the react-grid-layout requirements and make the cards resizable and draggable)...

        <ResponsiveReactGridLayout
          className="layout"
          compactType="vertical"
          breakpoints={{ lg: 1200, md: 800, sm: 680, xs: 480, xxs: 0 }}
          cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
          rowHeight={30}
          layouts={this.state.layouts}
          draggableHandle=".drag-handle"
          onLayoutChange={(layout, layouts) => this.onLayoutChange(layout, layouts)}
        >
          {
            React.Children.map(this.props.children, (child) => {
              if (!child.key) return;
              return (
                <div key={child.key} className={this.props.className} style={this.props.style}>
                  {child}
                </div>
              );
            })
          }
        </ResponsiveReactGridLayout>

Here is how "Card" wraps it's children (in this case, a BarChart)...

      <div id={id}>
        <div className="drag-handle">
          <hr />
          <hr />
        </div>
        {children}
        {close &&
        <i
          className={'close-button fa fa-fw fa-times-circle'}
          onClick={this.onClose}
          aria-hidden="true"
        />}
      </div>

...and finally, here is how BarChart wraps the ChartJS component...

      <div className="barChart" >
        <HorizontalBar data={data} options={options} />
      </div>

Here is the ChartJS settings of the bar chart (notice that maintainAspectRatio is false)...

```
const options = {
  legend: { display: true },
  scales: {
    xAxes: [{
      ticks: { min: 0,  max: 100, },
      stacked: true,
    }],
    yAxes: [{ barPercentage: 0.6, stacked: true, }],
  },
  elements: {
    rectangle: {
      borderWidth: 4,
      borderColor: 'rgb(255, 255, 0)',
    },
  },
  responsive: true,
  **maintainAspectRatio: false**,
};
```

The before and after screenshots show that the bar charts stretches it's width nicely, but not the height.  Also notice another Card has a simple < span > which resizes perfectly in both width and height.

Before:
![before](https://user-images.githubusercontent.com/6721949/32770078-24ed9f3c-c8d3-11e7-830e-fe6e9bfc7231.jpg)

After:
![after](https://user-images.githubusercontent.com/6721949/32770089-2c1ae45e-c8d3-11e7-85a5-0c191629f044.jpg)

Friends, I am really stumped.  I don't want to have to go hunting for another Charts package, I like this one!  Plz help me get past this tricky problem!

Thanks,
/Mark

**Comment by jerairrest** [comment]
So you're wanting the graph to fill that area? What size is the canvas in your last screenshot?

**Comment by jeghers** [comment]
At that point the card was roughly 500x300.  But regardless of the exact
size, I need the graph to fill the area both in width and height.  And,
oddly enough, the WIDTH does resize really well.  Just not the height.

**Comment by jerairrest** [comment]
hmmm... I wonder what changed between 2.6 to 2.7. I just booted up the examples with 2.7 and all the canvas sizing broke.

**Comment by jeghers** [comment]
Indeed, so this fix might be helpful to more than just me :-)

**Comment by jerairrest** [comment]
Looks like chart js broke 2.7 

https://github.com/chartjs/Chart.js/issues/4737

**Comment by jeghers** [comment]
Looking forward to a fix in the works :-)

**Comment by jerairrest** [comment]
Can you try 2.6 and see if you have the same troubles?

**Comment by jeghers** [comment]
K will do

On Nov 14, 2017 6:59 PM, "Jeremy Ayerst" <notifications@github.com> wrote:

Can you try 2.6 and see if you have the same troubles?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jerairrest/react-chartjs-2/issues/217#issuecomment-344471138>,
or mute the thread

**Comment by jeghers** [comment]
Same exact problem with 2.6

**Comment by jeghers** [comment]
The sizing started working for me when I wrapped the Bar Chart in a div that is, in turn, wrapped in and managed by the "react-measure" component (which manages the size of a child component).  Oddly enough, I didn't even feed the known width and height into the Bar Chart's props, and it still started working ... and I don't really know why!

If anyone has insights or discussion to help me understand this, please chime in.  I'll keep this issue open temporarily in hope someone will comment and help me understand this, please and thanks!

**Comment by AdrianoMoura** [comment]
What helped me was to add the option maintainAspectRatio and set as false

```
<Line data={data} options={{
 maintainAspectRatio: false
}}/>
```

**Comment by elmeister** [comment]
We use ResponsiveReactGridLayout too and resizing works fine. 
What about the underlying divs in the grid items, are they stretching fine?

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Comment by Lucasgoh-cdg** [comment]
> What helped me was to add the option maintainAspectRatio and set as false
> 
> ```
> <Line data={data} options={{
>  maintainAspectRatio: false
> }}/>
> ```
> 
> And in my case I also need to add the redraw as true
> 
> ```
> <Line data={data} redraw={true} options={{
>  maintainAspectRatio: false
> }}/>
> ```

Hi, even though I am using this, I am still having the same problem, what should I do ya? Thanks in advance
