### ISSUE TITLE
[Bug] changing datasets and returning to the first rendered doesn't work

### ISSUE THREAD

**Issue by Slind14** [jerairrest/react-chartjs-2#218]
Hi there,
currently there is a bug where when we change the datasets a few times and want to return to the initial rendered data, it won't work.

The library does modify (in some instances) the data supplied, this results in a corruption of the referenced data. E.g.

1. data=this.state.data.pageviews (displays page views)
2. data=this.state.data.sessions (displays sessions)
3. data=this.state.data.pageviews (displays sessions) => the supplied data was overwritten internally

I'm currently working around this issue by cloning the array/object before supplying. I would like to avoid this performance overhead and gotcha.

**Comment by jerairrest** [comment]
So each change is a new object? Are you able to spin up a quick example?

**Comment by Slind14** [comment]
Is there some boilerplate/codepen example I could base this off?

**Comment by jerairrest** [comment]
I sadly don't have one handy but I'll try to get one together shortly.

**Comment by jerairrest** [comment]
A code pen can be found here.

https://codepen.io/anon/pen/Nwvwjy

**Comment by Slind14** [comment]
Just a small heads up. I haven't forgotten about this, it's been a busy week. I'll see about it next week.

**Comment by tpbowden** [comment]
@jerairrest @Slind14 did you ever find a solution or workaround for this issue?

**Comment by Pringels** [comment]
Seems like duplicate of #438 - closing for now
