### ISSUE TITLE
How to center doughnut chart (half-circle) in a DIV that changes size often?

### ISSUE THREAD

**Issue by jeghers** [jerairrest/react-chartjs-2#221]
I have tried managing the width, height and centering of a half-circle doughnut chart in a DIV that is going to resize a lot.  It needs to fill the available space fully while keeping it's aspect ration AND remaining centered in the DIV both horizontally and vertically.  No matter what I do, it is never aligning well vertically, and the size often spills beyond the bottom of the DIV.  When I capture the parent DIVs width and height to forcibly set the charts size props, then the chart goes bonkers and move way way down until it's out of view.

Positioning children nicely in parents is such a hassle in HTML/CSS!  There must be a cleaner better way to do this, but I have obviously not figured it out.  Please help!

here is my render code:
```
  render() {
    const { width, height } = this.state.dimensions; // not used right now

    return (
      <Measure
        bounds
        onResize={(contentRect) => {
          this.setState({ dimensions: contentRect.bounds });
        }}
      >
        {({ measureRef }) => (
          <div
            className="doughnutChart"
            ref={measureRef}
            style={{ paddingTop: 25, paddingLeft: 5, paddingRight: 5, paddingBottom: 10 }}
          >
            <div style={{ position: 'absolute', top: 0, width: '100%', fontSize: 12 }}>Memory {width}x{height}</div>
            <Doughnut data={data} options={options} />
          </div>)
        }
      </Measure>
    );
  }
}
```
Thanks as always,
/Mark

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
