### ISSUE TITLE
Bar Chart resizes incorrectly (funky responsive issue)

### ISSUE THREAD

**Issue by davidcalhoun** [jerairrest/react-chartjs-2#222]
There's some weird behavior when resizing an app that uses Bar Charts.  This behavior can be seen right on the docs page: http://jerairrest.github.io/react-chartjs-2/

Video (click to view):

[![Alt text](https://img.youtube.com/vi/sHIhScCfK7Y/0.jpg)](https://www.youtube.com/watch?v=sHIhScCfK7Y)

Environment info:
- Chrome 62.0.3202.94 (latest)
- macOS High Sierra 10.13.1

react-chartjs-2 versions

- 2.4.0 (public docs page linked above)
- 2.6.4 - seeing something similar where the element is creating some bad feedback with `react-flexbox-grid`, starting at a normal size and then continually growing heightwise, eventually resulting in a canvas 200,000+ pixels high.  This is done without the user resizing the browser, though I think `react-flexbox-grid` is doing something behind the scenes to mutate the DOM, which `react-chartjs-2` is probably reacting responsively to.

**Comment by fozcodes** [comment]
+1

**Comment by mahdidavoodi7** [comment]
I have the same problem and I don't know what should I do

**Comment by daru23** [comment]
I have the same problem :(

**Comment by mahdidavoodi7** [comment]
@daru23 
hey I realized what should I do 
just set maintainAspectRatio True like this:
`<Bar
          data={data}
          width={100}
          height={50}
          options={{
            maintainAspectRatio: true
          }}
        />`
and it all be done

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Comment by davidcalhoun** [comment]
Sorry I didn't provide the steps to reproduce.  It's still happening right on the docs:

1. Open http://jerairrest.github.io/react-chartjs-2/
2. Scroll to **Bar Example (custom size)**
3. Expand and contract the window width.

Observed: the height of the Bar Chart continues to grow way offscreen.
Expected: the height of the Bar Chart should maintain a reasonable height.

Video (click to view):
<a href="https://www.youtube.com/watch?v=BkOiq3MExZM"><img width="859" alt="Screen Shot 2019-12-11 at 11 55 33 AM" src="https://user-images.githubusercontent.com/120596/70642406-28083300-1c0d-11ea-8a53-d8ffbc76fc12.png"></a>
