### ISSUE TITLE
Module not found: Error: Can't resolve './locale'

### ISSUE THREAD

**Issue by fsabreu** [jerairrest/react-chartjs-2#224]
Hi guys, 

I using this chart and it's awesome. But I'm getting a warning and I don't know how to resolve.

The warning: 
`[HMR] bundle has 1 warnings
client.js?102b:161 ./node_modules/chart.js/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\Users\Fellipe Abreu\Documents\Trabalhos\SM\trunk\wwwroot\public\react-boilerplate\node_modules\chart.js\node_modules\moment\src\lib\locale'
 @ ./node_modules/chart.js/node_modules/moment/src/lib/locale/locales.js 55:12-39
 @ ./node_modules/chart.js/node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/chart.js/node_modules/moment/src/moment.js
 @ ./node_modules/chart.js/src/scales/scale.time.js
 @ ./node_modules/chart.js/src/chart.js
 @ ./node_modules/react-chartjs-2/es/index.js
 @ ./app/containers/Chart/index.js
 @ ./app/containers/Chart/Loadable.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js`

Thanks

**Comment by dmaistern** [comment]
Hi,

It's an issue with moment.js and webpack. There is a whole thread about it 
https://github.com/moment/moment/issues/1435

What worked for me is the following:

> This can be worked around by aliasing 'moment' to 'moment/moment.js' (the commonjs "main") in your webpack config (resolve: { alias: { moment: 'moment/moment.js' } }).

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.

**Comment by nathanagez** [comment]
For people still having this issue, here is my solution: https://github.com/moment/moment/issues/4216?fbclid=IwAR0SJsbk863Zgl9YBA4MgLsnkh00yrVbGMYetJglFhFW3mHmM6u-AhWWfYA#issuecomment-622941952
