### ISSUE TITLE
Canvas/Ctx is null after using redraw

### ISSUE THREAD

**Issue by MartinDawson** [jerairrest/react-chartjs-2#225]
Because Redraw destroys the chart and initialises a new one, the canvas in the ref is null. How do we update this to the newly created chart reference?

To recreate it, just set redraw to true and try and access `ref.chart_instance.canvas`.

I need the canvas for generating custom tooltips as per this answer: https://stackoverflow.com/questions/44814522/custom-tooltips-with-react-chartjs-2-library

**Comment by MartinDawson** [comment]
Seems to also cause an error with chartjs `Cannot read property 'clearRect' of null`.

**Comment by bayuars** [comment]
please try to add condition:
from:
`clear: function(chart) {
        chart.ctx.clearRect(0, 0, chart.width, chart.height);
    },
`
    
to
`clear: function(chart) {
       if(t.ctx != null)
                   chart.ctx.clearRect(0, 0, chart.width, chart.height);
    },
`

i hope this will help.
thank you.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
