### ISSUE TITLE
The order of series is not maintained when updating a chart

### ISSUE THREAD

**Issue by sjurba** [jerairrest/react-chartjs-2#226]
I have a chart with multiple series which are toggled outside the chart. When I toggle an element of an then on again it is placed at the end of the dataseries array instead of its intended location. This is a problem for me as it messes up the z-index and also the legend is incorrectly ordered.

I have already looked at the code and will create a PR for this issue.

**Comment by jerairrest** [comment]
Thanks for the PR I will review soon! do you have an example of the trouble you were experiencing?

**Comment by sjurba** [comment]
I created a storybook example of the faliure and added that to the PR. Just checkout the commit without the fix to see how it fails. If you toggle 2016 of and on again, you see how the legend is ordered incorrectly and that the line is behind the bars.

**Comment by nettiopsu** [comment]
+1 
I experienced similar issue, it seems that sometimes dataset order is not respected. However it can be reset back to initial by changing some of the values in a graph (in my case all of the values are regulated within special form)

**Comment by sjurba** [comment]
@nettiopsu: did you see my PR? Can you try to checkout my fork and see if using that fixes your issue as well?

**Comment by nettiopsu** [comment]
@sjurba yay! thanks, it works now!
