### ISSUE TITLE
LaTeX (MathJax, KaTeX,..) in labels

### ISSUE THREAD

**Issue by MatejMazur** [jerairrest/react-chartjs-2#228]
In the first place: huge thanks for your effort to create this library for React. I really love it! 🥇 

But I have one problem: I can't find any guidance how to use math symbols in labels. Is this even possible? If it's not could you look into that? I need a lot of charts in scientific projects but it's a really pity that I can't use so obvious features for science.

I would be really glad if you could help me with this. :)

Edit: ..Maybe it will be better to ask directly in Chart.js issues, right?

**Comment by jerairrest** [comment]
This maybe better suited for the chart.js folks
