### ISSUE TITLE
Legend on top left

### ISSUE THREAD

**Issue by adtm** [jerairrest/react-chartjs-2#230]
How would it be possible to display the legend on the top left corner of the graph? 

Would be also good, if the legendCallback would work or there would be a proper documentation.

**Comment by gmkhussain** [comment]
Pass an **options** object in chart return structure

See code example:
```javascript
// . . .
render() {
  const options = {
        legend: {
            display: true,
            position: 'left'
        },
  };
    return (
      <div>
        <Line data={this.state.chartData} height="50" options={options} />
      </div>
    )
  }
//  . . .
```
