### ISSUE TITLE
chart_instance name should be camelCase?

### ISSUE THREAD

**Issue by benmccann** [jerairrest/react-chartjs-2#235]
@jerairrest it seems a bit odd to me that `chart_instance` uses an underscore in the name. Should we change it to `chartInstance` to be consistent with the other variable names? Or was there a reason for using the underscore?

**Comment by jerairrest** [comment]
I agree that this should be fixed. :+1:

**Comment by benmccann** [comment]
Fixed by https://github.com/jerairrest/react-chartjs-2/pull/236. Thanks!
