### ISSUE TITLE
bar chart over and over

### ISSUE THREAD

**Issue by bhenav** [jerairrest/react-chartjs-2#240]
Hi guys,
How can I do second image?

done
![image](https://user-images.githubusercontent.com/14276250/34988831-2fd8086c-fad1-11e7-810f-df1bb432510e.png)

to do
![image](https://user-images.githubusercontent.com/14276250/34988929-8f260bfc-fad1-11e7-9fda-64a12fc1a28f.png)

thanks,

**Comment by tmat06** [comment]
+1

**Comment by Pringels** [comment]
Please post a question on stackoverflow
