### ISSUE TITLE
Multiple datasets merge into one despite explicitly defining a label

### ISSUE THREAD

**Issue by boriskogan81** [jerairrest/react-chartjs-2#241]
I have the following code generating datasets :

`let dataset = {
	label: title,
	labels: data,
	fill: false,
	lineTension: 0.1,
	borderColor: colorArray()[counter],
	borderCapStyle: 'butt',
	borderJoinStyle: 'miter',
	pointBorderColor: 'rgba(75,192,192,1)',
	pointBackgroundColor: '#fff',
	pointBorderWidth: 1,
	pointHoverRadius: 6,
	pointHoverBackgroundColor: 'rgba(75,192,192,1)',
	pointHoverBorderColor: 'rgba(220,220,220,1)',
	pointHoverBorderWidth: 3,
	pointRadius: 1,
	pointHitRadius: 1,
	showLine: true,
	steppedLine: true,
	spanGaps: true,
	data: data,
	year: dataYear,
	measurement: 'state'
};`

It runs inside a loop, and title (the label property) is unique every time. I add all the datasets to an array, and pass the array to a Line object inside a data object:
```
const data = {
	labels: this.state.eventWeekArray,
	datasets: datasets
};
 <Line data={data} options={options} />
```

But all the datasets merge into one.

**Comment by bsadecki** [comment]
I'm having the same issue with a Line chart with a time series.

It's showing both datasets in the legend but only one line.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
