### ISSUE TITLE
Setting custom global defaults

### ISSUE THREAD

**Issue by launchriot** [jerairrest/react-chartjs-2#243]
Hi,

Is it possible to set my own defaults across my app and then customize minor things (like colors and labels) per instance?

I noticed you can import a default in the docs, but because I installed through NPM, I'm not going to modify your defaults. Or would the best move be to fork it if I want my own defaults?

Thanks.

**Comment by launchriot** [comment]
I ended up creating a wrapper that I called DataChart which contains defaults and generates a react-chartjs-2 component based on props.

**Comment by gezquinndesign** [comment]
Hello @launchriot - sorry to dig up closed issues but do you happen to have a copy of the DataChart component you created that I can have a look at for guidance on how to do this please?
