### ISSUE TITLE
Plugins keep their references?

### ISSUE THREAD

**Issue by knod** [jerairrest/react-chartjs-2#248]
https://github.com/knod/cliff-effects-1/tree/react-chart-plugin

Try switching the time frame from 'Yearly' to 'Monthly'. If you look at the console logs, you can see that the plugin always logs the same data, even when the component's data changes. That looks like the plugin retains its old references and doesn't use a new plugin on each re-render. Is this expected behavior? Are we building the plugin incorrectly?

I'll try to keep the branch up.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
