### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rudra0713** [jerairrest/react-chartjs-2#249]
Hi, After running npm install react-chartjs-2 chart.js --save command, I tried to render the simple Bar chart according to the documentation. But then, I encountered an error, "View config not found for the name canvas". Have I missed any installation step? Any suggestion is highly appreciated.

**Comment by Pringels** [comment]
Closing for now. Please supply a sandbox or code example with the latest versions of both libraries. If the problem persists, feel free to open a new issue.
