### ISSUE TITLE
Scattered data support without requiring labels

### ISSUE THREAD

**Issue by dmason30** [jerairrest/react-chartjs-2#25]
This was fixed in the original react-chartjs however there are a few long standing issues on that one and I was redirected here. However it doesn't appear that your library works in the same way for what i am trying to acheive.

On react-chartjs using chart.js v2 I am able to produce the below chart where I haven't specified an array of  labels and it has been able to scale the labels out based on my time.unit value;

![image](https://cloud.githubusercontent.com/assets/20278756/18270319/368f7c10-7424-11e6-813c-f027628ac0b9.png)

See end for example code that works with the react-chartjs library but produces an error with react-chartjs-2 **# which is  when you are trying to map the labels for the legend.** 

![image](https://cloud.githubusercontent.com/assets/20278756/18270633/d9fd3f80-7425-11e6-912e-c675cdc8a81f.png)
![image](https://cloud.githubusercontent.com/assets/20278756/18270651/f7d39d24-7425-11e6-9ce2-840a4382c899.png)

If I change labels field in code below to "labels: ['Dataset']". Then the chart renders but no data and y axis:

![image](https://cloud.githubusercontent.com/assets/20278756/18270700/38374938-7426-11e6-9450-757c9339de56.png)

```
    var data = {
        labels: 'Dataset',
        datasets: [{
            data: [
            { datetime: moment().hour(8).minute(0).format('X'),  rate: 1.1757},
            { datetime: moment().hour(8).minute(2).format('X'),  rate: 1.1797},
            { datetime: moment().hour(8).minute(9).format('X'),  rate: 1.1697},
            { datetime: moment().hour(8).minute(11).format('X'), rate: 1.1717},
            { datetime: moment().hour(8).minute(22).format('X'), rate: 1.1715},
            { datetime: moment().hour(8).minute(29).format('X'), rate: 1.1747},
            { datetime: moment().hour(8).minute(35).format('X'), rate: 1.1691},
            { datetime: moment().hour(8).minute(45).format('X'), rate: 1.1797},
            { datetime: moment().hour(8).minute(49).format('X'), rate: 1.1817},
            { datetime: moment().hour(9).minute(1).format('X'),  rate: 1.1857},
            { datetime: moment().hour(9).minute(12).format('X'), rate: 1.1847},
            { datetime: moment().hour(9).minute(33).format('X'), rate: 1.1877},
            { datetime: moment().hour(10).minute(0).format('X'), rate: 1.1957},
            { datetime: moment().hour(11).minute(0).format('X'), rate: 1.1857}
        ];
        }]
    };

  var options = {
        legend: {
            display:false,
        },
        // showXLabels: 10,
        responsive: true,
        maintainAspectRatio: false,
        scales: {
            xAxes: [{
                type: 'time',
                position: 'bottom',
                time: {
                    parser: 'X',
                    unit: 'hour',
                    tooltipFormat: 'LT',
                    max: moment().hour(11).minute(0).format('X'),
                    displayFormats: {
                        'hour': 'LT'
                    }

                }
            }]
         }
    };
```

**Comment by gor181** [comment]
Hello @dmason30 ,

Apologies for not reaching back before, it's a hectic time.
Will be checking this soon.

Thank you,

**Comment by gor181** [comment]
Hello @dmason30 ,

Have you checked how Mixed chart was done.
Example is at http://gor181.github.io/react-chartjs-2/
Source at https://github.com/gor181/react-chartjs-2/blob/master/example/src/components/mix.js

If it doesn't help please try to make a fiddle with just chart.js being used.

Thanks

**Comment by dmason30** [comment]
https://jsfiddle.net/qf1ff67j/

@gor181 I have managed to use the same options as above and chart.js renders fine. I'm sorry its been so long I was hoping `react-chartjs` would actually update at some point but it seems abandoned, so I am reconsidering switching to your repo.
