### ISSUE TITLE
ChartJS mutates the state

### ISSUE THREAD

**Issue by stuartsimpson** [jerairrest/react-chartjs-2#250]
After passing the chart data to the component for rendering, the chart.js graph mutates the data object and creates a recursive problem when doing a JSON.stringify to the data object.  It is easy to recreate the problem.  after the chart has rendered try and stringify the data object.

**Comment by openjck** [comment]
Can you post an simple example? I'm not a developer on this project, but I'm seeing something similar and I'm wondering if we're hitting the same issue.

**Comment by openjck** [comment]
I've put together a simple demo of this bug. See the project README for instructions for installing and running the demo:

https://github.com/openjck/bug-demo-react-chartjs-2-mutates-state

**Comment by openjck** [comment]
Any update on this?

Here's a quick workaround. If you're passing a `data` variable to react-chartjs-2, do this first:

```js
data = JSON.parse(JSON.stringify(data));
```

**Comment by stuartsimpson** [comment]
This is this the same workaround I ended up using.  I ended up holding two copies of the data one that i would keep up to date with RactJS and one that I would pass to React-Chartjs.  The issue is that react-chartjs needs to graph the chart without mutating the data.

**Comment by jerairrest** [comment]
This is a known issue with chart.js.

https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js#L125-L128

I'm not entirely sure what we can do about this since it's the core of chart.js is making this change.

**Comment by Pringels** [comment]
Closing. See: https://github.com/jerairrest/react-chartjs-2/issues/287

**Comment by Pringels** [comment]
Closing for now. IF this problem persists with the latest versions of both libraries then please feel free to reopen
