### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by farzadmf** [jerairrest/react-chartjs-2#251]
Hi,

I have the latest version installed from NPM (2.7.0), but I don't think it reflects all the changes; for example, `chart_instance` is supposed to be renamed to `chartInstace`, but I still see `chart_instance`

Also, I'm not sure how exporting the `defaults` is going to be useful in TypeScript since it's an empty object, and if we want to set a property on it, the TS compiler will complain

**Comment by ansimr** [comment]
I'm having the same issue as above, chart_instance is still used in the index.d.ts.

**Comment by jerairrest** [comment]
2.7.1 should address this issue.
