### ISSUE TITLE
Declare ID or class for chart?

### ISSUE THREAD

**Issue by chang-steven** [jerairrest/react-chartjs-2#252]
Hi,

I'm trying to give my doughnut chart an id or class so that I can style it.  I've put a wrapper around my chart, but wondering if it's possible to give a class or ID.  I tried the following, but doesn't work.

```
return (
        <div className="doughnut-wrapper">
          <h2>Activity Types</h2>
          <Doughnut
            id="doughnutChart"
            className="donut"
            data={data}
           />
        </div>
    )
```
Any thoughts?

**Comment by wgolledge** [comment]
I'm also wondering about this. 

With jQuery you could use a selector to find the parent element and then search for a canvas element within that. With vanilla JS it's not so simple.

**Comment by kellyclemons** [comment]
also wondering about this ^^^^^ using react/typescript with react-chartjs-2

**Comment by Pringels** [comment]
Closing. See: https://github.com/jerairrest/react-chartjs-2/issues/287
