### ISSUE TITLE
Width property not applied

### ISSUE THREAD

**Issue by NullCodex** [jerairrest/react-chartjs-2#254]
I tried to create a horizontal bar graph with a custom width but the width still takes up the entire page.
I'm creating the object with maintainAspectRatio set to false:
```
      <HorizontalBar data={data}
        height={200}
        width={1000}
        options={{
          maintainAspectRatio: false
      }}/>
```
It looks like the height is respected but not the width.
<img width="1205" alt="screen shot 2018-02-11 at 4 37 23 pm" src="https://user-images.githubusercontent.com/7586288/36078844-e6041356-0f49-11e8-9fd5-3f2196eaacdf.png">

**Comment by clochi** [comment]
Same thing here... i did that too and nothing happens :(

**Comment by motopete** [comment]
+1 Seeing the same thing with pie charts.

**Comment by jmariomejiap** [comment]
+1 the only solution I found was to wrap the chart up inside a <div style-{{ }}>.  the chart will adjust itself to the parent div.

**Comment by Asgator** [comment]
@jmariomejiap yes, if do it then don't show all labels

**Comment by eberkund** [comment]
I am encountering the same thing.

**Comment by GoorLavi** [comment]
me too

**Comment by Pringels** [comment]
Please provide a sandbox example reproducing your problem. If it persists with the latest versions of both chart.js and react-chartjs-2, then feel free to open a new issue.
