### ISSUE TITLE
Typescript issue on upgrade to latest

### ISSUE THREAD

**Issue by dcworldwide** [jerairrest/react-chartjs-2#255]
ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(11,49): error TS2694: Namespace '"*"' has no exported member 'ChartData'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(14,41): error TS2694: Namespace '"*"' has no exported member 'ChartData'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(17,27): error TS2694: Namespace '"*"' has no exported member 'ChartData'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(18,18): error TS2694: Namespace '"*"' has no exported member 'ChartType'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(23,20): error TS2694: Namespace '"*"' has no exported member 'ChartLegendOptions'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(25,21): error TS2694: Namespace '"*"' has no exported member 'ChartOptions'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(31,27): error TS2694: Namespace '"*"' has no exported member 'ChartData'.

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-chartjs-2/index.d.ts
(37,19): error TS2304: Cannot find name 'chartjs'.

TsConfig

```
{
  "compileOnSave": false,
  "compilerOptions": {
    // https://www.typescriptlang.org/docs/handbook/compiler-options.html
    "declaration": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": [
      "es6",
      "esnext.asynciterable",
      "dom"
    ],
    "diagnostics": false,
    "sourceMap": true,
    "jsx": "react",
    "removeComments": true,
    "outDir": "./dist",
    "pretty": true,
    "importHelpers": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": false,
    // Raise error on expressions and declarations with an implied ‘any’ type.
    "forceConsistentCasingInFileNames": true,
    // Disallow inconsistently-cased references to the same file.
    "preserveConstEnums": true
    //Do not erase const enum declarations in generated code.
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}

```

**Comment by jerairrest** [comment]
Hopefully 2.7.1 will fix this issue for you. please reopen if it does not.

**Comment by alexUXUI** [comment]
I am still getting this error
