### ISSUE TITLE
How to remove the vertical grid ?

### ISSUE THREAD

**Issue by ekobayu** [jerairrest/react-chartjs-2#259]
Hi, I try to remove the vertical line with this code but didn't work. Anyone have some suggestion ? Thanks

Code:
```
<LineExample options={{
		 scaleShowGridLines : false,
                  scaleShowVerticalLines: false,
	}}/>
```
<img width="514" alt="ss" src="https://user-images.githubusercontent.com/4278034/36892997-1b0448ca-1e39-11e8-9d07-6c0271edb2ea.png">

**Comment by jmariomejiap** [comment]
you can remove the vertical lines by setting **display: false** in inside xAxes property.
```
options={
  scales: {
    yAxes: [
      { ... },
    ],
    xAxes: [
      {
        gridLines: {
          color: '#aaa',
          borderDash: [1, 3],
        },
        display: false, // this will hide vertical lines
      },
    ],
  },
}
```

I hope this helps.

**Comment by ekobayu** [comment]
Awesome, thankss it worked @jmariomejiap

**Comment by BertrandBreton** [comment]
Perfect, Thanks a lot

**Comment by utkarsh1510** [comment]
gg

**Comment by timwsuccess81** [comment]
@utkarsh1510 You can hide the horizontal lines by adding the following to the yAxes property:

 gridLines: {
              drawOnChartArea: false
   }
