### ISSUE TITLE
How can I render two doughnut charts with two different datasets? 

### ISSUE THREAD

**Issue by rjsdnwk** [jerairrest/react-chartjs-2#263]
I want to make doughnut chart like [this](https://jsfiddle.net/moe2ggrd/152/). 

In order to achieve that I have `doughnut_chart` component like below. 

    render() {
 	  const data = {
	    datasets: 
	      {
	        data: [1, 2, 3],
	        labels: ["category1", "category2", "category3"],
	        backgroundColor: [                
	          "#79CAF2",
	          "#80DEEA",
	          "#A5D6A7",
	        ],
	        hoverBackgroundColor: [            
              "#31B2F2",
              "#00BCD4",
              "#4CAF50",
            ]
		  },
		  {
           data: [1, 2, 3, 4, 5],
	   labels: ["sub1", "sub2", "sub3", "sub4", "sub5"],
            backgroundColor: [                
              "#79CAF2",
              "#80DEEA",
              "#A5D6A7",
              "#C5E1A5",
              "#FFF59D",
            ],
            hoverBackgroundColor: [            
              "#31B2F2",
              "#00BCD4",
              "#4CAF50",
              "#8BC34A",
              "#FFEB3B",
            ]
		  },
	    ]
	  };

	  const options = {
        tooltips: {
      	  callbacks: {
        	label: function(tooltipItem, data) {
          	  var dataset = data.datasets[tooltipItem.datasetIndex];
              var index = tooltipItem.index;
              return dataset.labels[index] + ': ' + dataset.data[index];
            },
          }
        }	
	  }

      return (
	    <div className="h100per_200pix w100per margin_top_50">
	 	  <DoughnutChart data={data} options={options} ref="chart" />
	    </div>
      )
    }

However, it renders only one `doughnut_chart` for the second dataset. It does not render chart for the first dataset. Looks like below,
![screenshot from 2018-03-16 14-49-37](https://user-images.githubusercontent.com/17551692/37552293-14fb31e0-29ed-11e8-92b7-dd7f3b0b91f4.png)

How can I render two doughnut charts? any suggestions?

Thank you in advance.

**Comment by Pringels** [comment]
Please refer to the chart.js documentation
