### ISSUE TITLE
Any idea on how to create bars in bar chart as progressbar types in react-chartjs-2

### ISSUE THREAD

**Issue by anihow** [jerairrest/react-chartjs-2#265]
Want to create Bars in Bar chart as progress bar type as shown in the below image.
<img width="518" alt="pnwmw" src="https://user-images.githubusercontent.com/37570366/37645114-e7058324-2c4b-11e8-9bfe-750f230f6765.png">
image .

I have achieved till hear by using plugin attributes 
![trying1](https://user-images.githubusercontent.com/37570366/38022214-8fcf831e-329c-11e8-88cd-46b44c805221.PNG)

Any simple way like attributes to achieve the bar in barchart as in 1st image

**Comment by Pringels** [comment]
Please refer to the chart.js documentation
