### ISSUE TITLE
Doughnut tooltip jumps

### ISSUE THREAD

**Issue by nazartry** [jerairrest/react-chartjs-2#272]
Hey, I have a problem when hovering on doughnut's part, tooltips sometimes jump to some other random part

Cursor is on blue:
![image](https://user-images.githubusercontent.com/36134935/38732866-91287732-3f28-11e8-9b86-807f3b39e485.png)

**Comment by Pringels** [comment]
Please refer to the chart.js docs/issues, or open an issue on stackoverflow
