### ISSUE TITLE
Is AMD loading supported?

### ISSUE THREAD

**Issue by DigitalFlow** [jerairrest/react-chartjs-2#275]
Hey there,

I have previously used this library inside my CommonJs project and was very happy with it.
However now I need to use requireJs and AMD for another project.

As the dist folder contains an UMD release, I tried to use this for loading the library.
As it turns out however, there seem to be quite a few NodeJs objects used?

The scripts are failing with `process is not defined` in dist/react-chartjs-2.js:80 (`if (process.env.NODE_ENV !== 'production') {`).
Any chance for using with requireJs?

Thanks in advance.

Kind Regards,
Florian

Edit: As a workaround, everything seems to work when setting `window.process = { env: "production" } }` on the page. And for anyone needing to load it using requirejs: You'll have to change the `define(['exports', 'react', 'chart.js'], factory)` to `define(['exports', 'react', 'chartjs'], factory)`.
Having to rename chartjs is a known issue: https://github.com/jtblin/angular-chart.js/issues/147

@jerairrest: Do you think this workaround should be implemented in here?

**Comment by jerairrest** [comment]
Yea I just was looking this and it looks like react is included in the UMD build? Maybe? I'm open to suggestions.

**Comment by jerairrest** [comment]
This issue should be fixed by https://github.com/jerairrest/react-chartjs-2/pull/309 if you'e willing to take a look.

**Comment by DigitalFlow** [comment]
Hey @jerairrest,

I will check it and give you feedback, thanks for tackling this :)

Kind Regards,
Florian

**Comment by jerairrest** [comment]
Should be fixed in https://github.com/jerairrest/react-chartjs-2/releases/tag/2.7.4
