### ISSUE TITLE
Unusual behavior onHover/onClick of Y axis Labels on Horizontal Bar

### ISSUE THREAD

**Issue by SaiNikhilD** [jerairrest/react-chartjs-2#279]
I replaced the sample data from the story books example from [65, 59, 80, 81, 56, 55, 40] to [1000, 2000, 0, 5, 6, 8, 100] and I cannot see the tooltip for the respective bar. Can anyone explain what's causing this ?

**Comment by nicolobruno** [comment]
Are you passing tooltip in the options ?

For Example:
 
```
const options = [
  tooltips: {
      mode: 'x',
      intersect: false,
   }
];
```

**Comment by Pringels** [comment]
Please provide example/sandbox code if this issue persists.
