### ISSUE TITLE
Adjust bar thickness of individual bars

### ISSUE THREAD

**Issue by glorenzen** [jerairrest/react-chartjs-2#282]
`<Bar 
                data={ this.props.data }
                height={ 400 }
                width={ 400 }
                options={{
                    maintainAspectRatio: false,
                    layout: {
                        padding: {
                            left: 10,
                            right: 10,
                            top: 0,
                            bottom: 0
                        }
                    },
                    scales: {
                        xAxes: [
                            {
                                ticks: {
                                    autoSkip: false
                                },
                                barPercentage: 0.7
                            }
                        ],
                        yAxes: [
                            {
                                ticks: {
                                    beginAtZero: true,
                                    max: 100
                                }
                            }
                        ]
                    }
                }}`

**Comment by glorenzen93** [comment]
Here's the code I have right now, but from what I can see, there isn't a way access the individual bars for each category. Does anybody know if there is an option to adjust each bar individually?

**Comment by Pringels** [comment]
@glorenzen please refer to the chart.js documentation

**Comment by johnmiko** [comment]
@glorenzen , did you figure it out? Not clear to me from reading the documentation what to do
