### ISSUE TITLE
Namespace ''chart.js'' has no exported member 'ChartData'

### ISSUE THREAD

**Issue by FromZeroToCicero** [jerairrest/react-chartjs-2#283]
...\node_modules\react-chartjs-2\index.d.ts
(11,49): error TS
2694: Namespace ''chart.js'' has no exported member 'ChartData'.

Yesterday all was working fine, no errors, nothing...today when I opened up the project, this popped up. I saw in another issue that 2.7.1 was supposed to fix this and I have installed 2.7.2 for both react-chartjs-2 and chart.js.

![issue](https://user-images.githubusercontent.com/32496258/40099615-678db984-58e9-11e8-99fa-6732cb0a8643.png)

**Comment by artemave** [comment]
Hey @FromZeroToCicero I am seeing the same thing. Did you manage to get around this in the end?

**Comment by artemave** [comment]
Ok, my case was dumb: I had a `d.ts` file that was overwriting `chart.js` module.

**Comment by FromZeroToCicero** [comment]
I just deleted everything that was outlined with red, changed the type to any and it now works. But I don't suggest doing that, should be nice to have a fix for this :D
