### ISSUE TITLE
Adding CSS to Labels and Datas

### ISSUE THREAD

**Issue by erkinyavuz** [jerairrest/react-chartjs-2#284]
Can i add some CSS , at least bold or font height etc. to Labels and Datas in Line Chart ? Anyway to do it?
thanks in advance.

**Comment by nicolobruno** [comment]
Yes, you can customize Labels and Data in the callback in the options.

For example:
`
const options = [ 
  scales: {
    yAxes: [
      {
        ticks: {
          beginAtZero: true,
          callback: value => formatNumberDecimal(value)
        }
      }
    ],
    xAxes: [
      {
        ticks: {
          callback: value => {
            const date = value.split(' | ');
            return date[0];
          }
        }
      }
    ]
  };
];
`

`<Line
      data={date}
      options={options}
    />`
In the example I return XAxes and YAxes value formatted but you can return any value

**Comment by rafaelbiten** [comment]
I'm trying the same but apparently we can only return `string` or `string[]` from the callback.

On our case we'd like to wrap part of the label in an html tag so we can give it a different colour, ie.: `My <span>label</span>`.

Is this possible/supported?

**Comment by thiagoneves** [comment]
@rafaelbiten did you find a way to do that?

**Comment by rafaelbiten** [comment]
No, I kept researching but apparently that isn't supported, unfortunately. An option would be to take the labels out of the chart, but I don't think that's a good solution, but still an option if you really need it. If I remember well, they were working on it though. I'd have to check again. If you figure out out, please let me know, ok?

**Comment by Pringels** [comment]
Please move this to stackoverflow or the chart.js github repo
