### ISSUE TITLE
Warning: Failed prop type: The prop `data` is marked as required in `ChartComponent`, but its value is `undefined`.

### ISSUE THREAD

**Issue by alihesari** [jerairrest/react-chartjs-2#288]
Hi, I get this error in google chrom console:

> Warning: Failed prop type: The prop `data` is marked as required in `ChartComponent`, but its value is `undefined`.

I'm using chart in ReactJs:
`<Doughnut data={chart1} />`

**Comment by ohtanya** [comment]
Hey @alihesari did you ever figure this out? I'm having the same issue.

**Comment by alihesari** [comment]
@ohtanya I removed react-chartjs-2 and use https://github.com/reactjs/react-chartjs

**Comment by Ashvin09** [comment]
Put <Doughnut data={chart1} /> inside if condition

**Comment by Pringels** [comment]
You can conditionally render the Doughnut if data is present
