### ISSUE TITLE
Duplicate data 

### ISSUE THREAD

**Issue by sonhip94** [jerairrest/react-chartjs-2#290]
![image](https://user-images.githubusercontent.com/30177470/40640349-d4601218-633f-11e8-9267-251b89228778.png)
![image](https://user-images.githubusercontent.com/30177470/40640368-eb39d1b8-633f-11e8-9e81-32026d6ce095.png)
How can i fix it? please.

**Comment by jerairrest** [comment]
Can you please provide code examples of what you're having troubles with?

**Comment by Pringels** [comment]
Closing. Please create a new issue with code examples and/or a code sandbox to demonstrate the problem you are facing.
