### ISSUE TITLE
Can't use on Codepen - Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by pelenthium** [jerairrest/react-chartjs-2#291]
Hi, i try to create example on Codepen, but when I import 
https://cdnjs.cloudflare.com/ajax/libs/react-chartjs-2/2.7.2/react-chartjs-2.js
I have errors in console - 
Uncaught ReferenceError: process is not defined
    at react-chartjs-2.js:80
    at react-chartjs-2.js:4
    at react-chartjs-2.js:5

May be you know how to avoid this errors?

Codegen example - https://codepen.io/pelenthium/pen/pKJGge

**Comment by altras** [comment]
Yup, I fail to understand how to use the lib at jsfiddle as well https://jsfiddle.net/05n7hogj/3/ :/ It was very easy with previous versions

**Comment by jerairrest** [comment]
Should be fixed in https://github.com/jerairrest/react-chartjs-2/releases/tag/2.7.4
