### ISSUE TITLE
Chartjs version 2 is not available through npm?

### ISSUE THREAD

**Issue by RyanPaulMcKenna** [jerairrest/react-chartjs-2#292]
This comment was made in error.

**Comment by miczed** [comment]
Just add `"chart.js": "^2.7.2"` to your dependencies in your `package.json` file and then run `npm install`. If you just run `npm install chart.js` you'll get the 1.x version.

Maybe this should be mentioned somewhere in the docs.

**Comment by yeahoffline** [comment]
just installed chart.js and got 2.7.2

yarn add react-chartjs-2 chart.js --save
...
info Direct dependencies
├─ chart.js@2.7.2
└─ react-chartjs-2@2.7.2
info All dependencies
├─ chart.js@2.7.2
├─ chartjs-color-string@0.5.0
├─ chartjs-color@2.2.0
└─ react-chartjs-2@2.7.2
✨  Done in 8.69s.
