### ISSUE TITLE
version 2.7.2 animation break line chart 

### ISSUE THREAD

**Issue by kre1z0** [jerairrest/react-chartjs-2#293]
**Line chart data** 

`const dataSeasonality = {
            labels: labels ? labels : moment.monthsShort(),
            datasets: [
                {
                    fill: false,
                    borderColor: '#55c3ec',
                    pointBackgroundColor: '#55c3ec'
                    lineTension: 0,
                    borderWidth: 2,
                    data: values,
                    ...datasets,
                },
            ],
        };`

**Line chart options** 
`const optionsSeasonality = {
            responsive: true,
            animation: true,
            legend: {
                display: false,
            },
            tooltips: {
                bodyFontSize: 12,
                xPadding: 11,
                yPadding: 9,
                caretSize: 7,
                caretPadding: 10,
                cornerRadius: 6,
                displayColors: false,
                callbacks: {
                    label: ({ yLabel }) => {
                        const percent = round(yLabel, 1);
                        return `${percent}%`;
                    },
                    title: ([item]) => {
                        return moment.months()[item.index].capitalizeFirstLetter();
                    },
                },
            },
            // events: false,
            scales: {
                yAxes: [
                    {
                        ticks: {
                            fontSize: 9,
                            padding: 10,
                            fontColor: ticksColor,
                            maxTicksLimit: 7,
                        },
                        stacked: true,
                        gridLines: {
                            drawTicks: true,
                            zeroLineColor: '#ababab',
                            tickMarkLength: 4,
                        },
                    },
                ],
                xAxes: [
                    {
                        ticks: {
                            fontSize: 9,
                            fontColor: ticksColor,
                        },
                        gridLines: {
                            drawTicks: true,
                            zeroLineColor: '#ababab',
                            tickMarkLength: 4,
                        },
                    },
                ],
            },
            ...options,
        };`
**error console**
`core.controller.js:531 Uncaught TypeError: easingFunction is not a function
    at Chart.render (core.controller.js:531)
    at Object.callback (helpers.core.js:85)
    at Object.advance (core.animation.js:131)
    at Object.startDigest (core.animation.js:104)
    at core.animation.js:86`

**Comment by abolajibisiriyu** [comment]
Hi @kre1z0 , I also have this issue, what i did to stop error was disable animation, i haven't found a way to make the animation to work.
`animation: false` in the chart options object.
