### ISSUE TITLE
Tooltip position bug

### ISSUE THREAD

**Issue by kshysius** [jerairrest/react-chartjs-2#294]
When you fix this bug?

<img width="207" alt="screen shot 2018-06-10 at 15 05 45" src="https://user-images.githubusercontent.com/6617084/41201387-d025a47c-6cbf-11e8-9073-818780ce6826.png">

**Comment by souuu** [comment]
Any solution for this ?

**Comment by Pringels** [comment]
Please create a sandbox example with the problem you are experiencing and open a new issue if this persists.
