### ISSUE TITLE
Custom Style and object structure for Label?

### ISSUE THREAD

**Issue by MahmoudAwwad94** [jerairrest/react-chartjs-2#297]
First of all thank you so much for you guys for implement react wrapper for chartjs2.
My question can i have object as label and also can i have custom css for label so it can be something like that
<img width="507" alt="screen shot 2018-06-19 at 9 54 28 am" src="https://user-images.githubusercontent.com/24322359/41582755-20a26682-73ab-11e8-8ba5-ec953339e5d4.png">

**Comment by higginni** [comment]
Looking for a solution to this as well. Any movement on it?

**Comment by Pringels** [comment]
Please see: https://www.chartjs.org/docs/latest/configuration/legend.html#html-legends
