### ISSUE TITLE
Width not working

### ISSUE THREAD

**Issue by gordal18** [jerairrest/react-chartjs-2#298]
Hello,
<Radar width={300} height={300} data = {this.state.radar_data} options={{ maintainAspectRatio: false }}/>
I tried to set the width : 300px.
But not working.
Can you help me?

**Comment by mahyalpr** [comment]
<div style={{width: '600px'}}>
<Radar width={300} height={300} data = {this.state.radar_data} options={{ maintainAspectRatio: false }}/>
</div>
it's work
