### ISSUE TITLE
Legend onclick can not override chart onclick

### ISSUE THREAD

**Issue by luqiwang** [jerairrest/react-chartjs-2#299]
Hi, 
I want trigger legend onclick function, but when I click legend, it seems to trigger the chart onclick function to setState. Is there any way to prevent chart onclick  when click the legend. 
Thanks a lot!
`options = {legend: {
  display: true,
                    onClick: (e, item) => {console.log("Click Legend")}
                  },
                  events: ['click', 'mousemove'],
                  onClick: (e, data) => {
                     this.setState(newState)
                    }}`

**Comment by erezLieberman** [comment]
I have this issue too - any update about that?

**Comment by luqiwang** [comment]
Sorry, I cannot find one.

**Comment by Pringels** [comment]
Please refer to the chart.js docs: https://www.chartjs.org/docs/latest/configuration/legend.html#custom-on-click-actions

**Comment by KhalidOuaz** [comment]
Hello 
Button continue to be override,
i have a test here but i am still not finding a solution.
Can you help me please
https://codesandbox.io/s/gallant-archimedes-zqxre

**Comment by dpadula** [comment]
@KhalidOuaz I've found this and test it with another chart (bar chart). Maybe can help you with the behavior of legend.

  legend: {
    display: true,
    position: 'bottom',
    onClick: (e, legendItem, chart) => {
      // console.log('e', e); // EVENT
      // console.log('legendItem', legendItem); // ITEMS
      // console.log('chartRef'); // REF
      const ci = chartRef.chartInstance;
      let meta = ci.getDatasetMeta(0);
      // console.log(meta);

      // // See controller.isDatasetVisible comment
      meta.hidden = meta.hidden === null ? !ci.data.datasets[0].hidden : null;

      // // We hide a dataset ... rerender the chart
      ci.update();
    },

Cheers
