### ISSUE TITLE
Hide Lables in Line chart

### ISSUE THREAD

**Issue by ishansan38** [jerairrest/react-chartjs-2#300]
Hi, Is there a quick way to hide labels in the line chart since they make the chart look really messy, or someway we could show them vertical instead of horizontal?

Thanks for your help!

**Comment by Pringels** [comment]
@ishansan38 Please refer to the Chart.js documentation, or open and issue on their repo or stackoverflow

**Comment by Acidic9** [comment]
If anyone else comes across this, in your options you need the following:
```js
