### ISSUE TITLE
Line Chart Time Axes line goes Back. Weird. 

### ISSUE THREAD

**Issue by barryblando** [jerairrest/react-chartjs-2#301]
- Chartjs - 2.7.2
- React Chartjs 2 - 2.7.2

![2018-06-23_21-47-59](https://user-images.githubusercontent.com/5582213/41810322-2b08797c-772f-11e8-8128-5098736ffb82.png)

**Comment by khunghang16** [comment]
hi, this is my code , but it is not show labelString? help me?
const options = {
    responsive: true,
    title: {
        display: true,
        text: 'Chart.js Line Chart'
    },
    tooltips: {
        mode: 'index',
        intersect: false,
    },
    hover: {
        mode: 'nearest',
        intersect: true
    },
    scales: {
        xAxes: [{
            display: true,
            scaleLabel: {
                display: true,
                labelString: 'Month',
                lineHeight:2,
            }
        }]
    }
}
return (
            <div style={styles.content} >
                <Line data={data} option={options} />
            </div>

        )

**Comment by Pringels** [comment]
If this proeblem persists please create a sandbox reproducing your issue. (or at least post the dataset you are using)

Closing for now, as it is older than 6 months and probably not related to the react wrapper
