### ISSUE TITLE
To what extent can I style a graph component?

### ISSUE THREAD

**Issue by alexanderchoi** [jerairrest/react-chartjs-2#305]
Right now I just know how to change the height but would like to know more options such as changing the position of labels in a pie graph, changing the font, changing the on hover readout's style, etc.

**Comment by buddyp450** [comment]
Anything standard to chart.js's options can be passed in currently via the options object. However things modifying the canvas element are currently restricted as far as I can tell. Height and width are the only properties that actually make it to the canvas.

I'm not the maintainer but I'd say general questions should probably go on StackOverflow.
