### ISSUE TITLE
Cannot set multiple lineWidths to xAxes gridLines

### ISSUE THREAD

**Issue by lucasharada** [jerairrest/react-chartjs-2#313]
I'm trying to set a `lineWidth` for each `x` value. I tried to do as described on the [docs](http://www.chartjs.org/docs/latest/axes/styling.html#grid-line-configuration) (e.g. `[1,1,1,1,1,40,1,1,1,1,1,1]`), but doesn't work, making all gridLines for the `xAxis` disappear.

The same approach was used to change the color for each `x` value and it works perfectly.

Here what I tried:

```
options={{
    responsive: false,
    legend: {
        display: false,
    },
    maintainAspectRatio: false,
    scales: {
        xAxes: [{
            stacked: true,
            gridLines: {
                display: true,
                drawBorder: false,
                offsetGridLines: false
            }
        }],
        yAxes: [{
            display: true,
            stacked: true,
            ticks: {
                beginAtZero: true,
                max: datas.options.max,
                stepSize: datas.options.stepSize
            }
        }]
    }
}}
```

**Comment by Pringels** [comment]
Please refer to the Chart.js documentation
