### ISSUE TITLE
How To Make Gradient Fill Area Line Chart

### ISSUE THREAD

**Issue by sithuhlaing** [jerairrest/react-chartjs-2#315]
I would like to fill the area on line chart with this code 
`var gradientFill = ctx.createLinearGradient(500, 0, 100, 0);`
`gradientFill.addColorStop(0, "rgba(128, 182, 244, 0.6)");`
`gradientFill.addColorStop(1, "rgba(244, 144, 128, 0.6)");` but I can't know where cant i get ctx

**Comment by MacgyverMartins** [comment]
```javascript
    const data = canvas => {
      const ctx = canvas.getContext('2d');
      // your code here
    }  
```

**Comment by Pringels** [comment]
@sithuhlaing see https://github.com/jerairrest/react-chartjs-2#getting-context-for-data-generation

**Comment by vinayaknk** [comment]
Can someone please paste working example.

**Comment by nguyenhdangquang** [comment]
@vinayaknk here is solution https://github.com/jerairrest/react-chartjs-2/issues/366
