### ISSUE TITLE
"datasetKeyProvider" as a prop that returns a unique key.

### ISSUE THREAD

**Issue by sithuhlaing** [jerairrest/react-chartjs-2#317]
I crate a data set and put into the chart but after react component update, It is not update the graph and show error 
`[react-chartjs-2] Warning: Each dataset needs a unique key. By default, the "label" property on each dataset is used. Alternatively, you may provide a "datasetKeyProvider" as a prop that returns a unique key.`

**Comment by karthiksagarmv** [comment]
I was bit confused as well, but then i just followed the raw meaning of the error.
I passed a function to datasetKeyProvider that returns a unique key and warning disappeared, boom !

Like this 

`
datasetKeyProvider(){
     return Math.random();
}
<Line
        ...props
       datasetKeyProvider={this.datasetKeyProvider}
/>
`

**Comment by GisliNielsen** [comment]
This is the improper way of doing it. In your datasets you should define a variable called "label" with a unique ID.

https://github.com/jerairrest/react-chartjs-2#working-with-multiple-datasets

**Comment by SumitKumarPandey-CED** [comment]
label : Math.random(),
 
 As this works for me
