### ISSUE TITLE
Warning: Failed prop type: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by nathanburgess** [jerairrest/react-chartjs-2#318]
Attempting to use this library with no luck. When I add the following code to one of my components...
```
import { Line as LineChart } from 'react-chartjs-2'

render() {
<LineChart data={data} />
)
```

I get this error message:
> Warning: Failed prop type: Cannot read property 'line' of undefined

Has anyone come across this and figured out a solution?

I'm using:
```
        "chart.js": "^2.7.2",
        "react-chartjs-2": "^2.7.4",
```

**Comment by sameerjain** [comment]
Hello @nathanburgess have you got this sorted? I am having similar issue. Thanks

**Comment by nathanburgess** [comment]
@sameerjain I didn’t mess with it too much. The trouble of fixing it wasn’t worth it. Instead I went with ChartKick for now, which works with no problems.

**Comment by sameerjain** [comment]
Restarting node service fixed this for me, may be module doesn't compiled
well because I installed it while npm start was running. All good now.
Cheers

Keep it positive !!
Warm Regards,
Sameer Jain
+91-98281-23519
+91-98281-23510

**Comment by nathanburgess** [comment]
That didn’t work for me. I even tried deleting node_modules and clearing the cache, forcing everything to redownload and rebuild.

Thanks,
Nathan Burgess

**Comment by sameerjain** [comment]
I am using following version from both lib

> "chart.js": "^2.6.0",
> "react-chartjs-2": "^2.7.4",

**Comment by blockjon** [comment]
![image](https://user-images.githubusercontent.com/1198745/48337573-2dfda000-e618-11e8-9a48-046cbd8d9997.png)
After spending half a day trying to get this to work in a new watered down react app, I'm giving up

**Comment by gabrieltet** [comment]
I had the same problem which I fixed updating the chart.js dependency.

run `npm install chart.js@2.3.7 --save`

**Comment by jbiddulph** [comment]
I too am having this problem, please help!

**Comment by Pringels** [comment]
Please create new issues if you are still experiencing issues with the latest versions of both libraries. Include a sandbox example if possible.

Closing
