### ISSUE TITLE
Individual labels for multiple Pie chart datasets are not showing

### ISSUE THREAD

**Issue by razvanilin** [jerairrest/react-chartjs-2#320]
I have this configuration:
```
{
	"data": {
		"labels": ["true", "false"],
		"datasets": [{
			"label": "Hum Notifications",
			"data": [1913, 136],
			"borderWidth": 2,
			"hoverBorderWidth": 3,
			"borderColor": "#1a7fa0",
			"backgroundColor": ["rgba(98, 154, 41, 0.48)", "rgba(248, 231, 28, 0.53)"],
			"fill": true
		}, {
			"label": "Dataset #2",
			"data": [1973, 76],
			"borderWidth": 2,
			"hoverBorderWidth": 3,
			"backgroundColor": ["rgba(220, 97, 52, 0.8)", "rgba(74, 144, 226, 1)"],
			"fill": true
		}]
	},
	"options": {
		"maintainAspectRatio": false,
		"legend": {
			"display": true
		},
		"elements": {
			"point": {
				"radius": 0,
				"hitRadius": 8,
				"hoverRadius": 8
			}
		},
		"scales": {
			"yAxes": [{
				"ticks": {
					"beginAtZero": true
				}
			}]
		}
	}
}
```

The pie chart gets rendered correctly, but the labels that I set in each dataset are not showing up when hovering over the chart.

![screen shot 2018-08-05 at 11 02 45](https://user-images.githubusercontent.com/5342321/43684368-298ca0dc-989f-11e8-900b-78e29506f67e.png)

The tooltip should show `<label1>: true: 1913` right?

Found this SO link and it appears to be working there: https://stackoverflow.com/questions/45182635/how-to-use-two-datasets-in-chart-js-doughnut-chart

**Comment by wilrho** [comment]
Hi there,

Looks like you need to rename label to labels and put then in an array. Try this:

const data = {
    "labels": ["true", "false"],
    "datasets": [{
        "labels": ["Hum Notifications","Hum2"],
        "data": [1913, 136],
        "borderWidth": 2,
        "hoverBorderWidth": 3,
        "borderColor": "#1a7fa0",
        "backgroundColor": ["rgba(98, 154, 41, 0.48)", "rgba(248, 231, 28, 0.53)"],
        "fill": true
    }, {
        "labels": ["Dataset #2","set3"],
        "data": [1973, 76],
         "borderWidth": 2,
        "hoverBorderWidth": 3,
        "backgroundColor": ["rgba(220, 97, 52, 0.8)", "rgba(74, 144, 226, 1)"],
        "fill": true
    }]
}
