### ISSUE TITLE
random data not working properly

### ISSUE THREAD

**Issue by ghost** [jerairrest/react-chartjs-2#328]
I have integrated campaign chart which display the random data but it's not working properly some time it doesn't update the data. I have used react-chartjs2 library in my react application. Here is my codesanbox link https://codesandbox.io/s/rrlpr2nxjm

**Comment by Pringels** [comment]
@ghost this seems to be related to how you are generating the random data. The conditional you have defined does not always pick a different object key, so some intervals will indeed not return a different dataset.

Closing for now.
