### ISSUE TITLE
How can I create new custom type of chart?

### ISSUE THREAD

**Issue by Charlie91** [jerairrest/react-chartjs-2#330]
I'm trying to realize [this script ](https://codepen.io/jordanwillis/pen/jBoppb?editors=1010) in react-chartjs-2 context. 
As I understand, The main point of script above is the creating of new custom class and giving it special functionality. 
In short, I need to realise something like it
```
new Chart(ctx, {
  type: 'customChart',
  data: [] 
})
```
But it'll be better if I could do React-component with the same sense.
How can I create my own class and use it in JSX?

**Comment by Charlie91** [comment]
I've found [here](https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js) the thing I need. 
If i could use the same syntax in my code or could import ChartComponent it will be the best solution.
`  <ChartComponent
        {...this.props}
        ref={ref => this.chartInstance = ref && ref.chartInstance}
        type='bar'
      />`

**Comment by tingtingtinghuang** [comment]
@Charlie91 Hello. I am doing what you have mentioned. Have you reach your goal? Would you like to share some suggestions?
