### ISSUE TITLE
Legend styling options with large array

### ISSUE THREAD

**Issue by falcofire** [jerairrest/react-chartjs-2#339]
I am utilizing a doughnut chart for a dataset with a high volume of keys with legend position='left'. The default behavior for the legend seems to be to wrap keys into new columns. Is there any way to force a single column for the legend (ideally scrollable)?

**Comment by lucascnr** [comment]
Hi @falcofire,

I faced with this same problem. Have you found a solution for this?

**Comment by Pringels** [comment]
@falcofire please open an issue with Chart.js
