### ISSUE TITLE
How to add buttons to labels ?

### ISSUE THREAD

**Issue by souuu** [jerairrest/react-chartjs-2#342]
Hello, 
I want to add buttons to the labels on chart.
Example : 
<img width="449" alt="capture d ecran 2018-09-26 a 14 02 07" src="https://user-images.githubusercontent.com/17356470/46081671-fedcbd80-c194-11e8-9ec0-144eab61aeac.png">
Thank you !

**Comment by Pringels** [comment]
@souuu Please refer to the Chart.js documentation
