### ISSUE TITLE
How to display the legend text vertically?

### ISSUE THREAD

**Issue by spunbell** [jerairrest/react-chartjs-2#348]
I have created a Pie Chart using this package and have some labels representing my data. 

 `legend: {
                position: 'bottom',
                fullWidth: true,
                labels: {
                    boxWidth: 10
                }
  }`

I set these as my options so that the labels/legend would be below my pie chart as shown in the picture below:

![image](https://user-images.githubusercontent.com/44040683/47124251-cb400100-d231-11e8-9580-e442a0485bae.png)

How can I make my labels display vertically rather than one beside the other? Please let me know if you would like me to add any other code.

**Comment by RenSolis** [comment]
Wha is the answer?

**Comment by Prasad-YS** [comment]
if you make position: 'right' or 'left' you will get vertically in right side or left side of the chart

**Comment by Pringels** [comment]
Closing as not relevant to wrapper

**Comment by kdiaz10** [comment]
just add
var chart = nv.models.pieChart()
      .x(function(d) { return d.label })
      .y(function(d) { return d.value })          
      .legendPosition("right");
