### ISSUE TITLE
Width is backwards.

### ISSUE THREAD

**Issue by conradkay** [jerairrest/react-chartjs-2#350]
I have some code which I have here: https://github.com/conradkay/myPoll/blob/master/client/src/poll/poll.tsx
If at line 52 you change the width to for example, 100, it will be huge, but at 500, it is small.

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
