### ISSUE TITLE
How to achieve horizontal scrollable chart components in react-chart-js-2?

### ISSUE THREAD

**Issue by adithyamaheshb** [jerairrest/react-chartjs-2#355]
I am trying to create a horizontal x-axis scrollable bar chart. Are there any props or methods to achieve this? Please, help me out.

**Comment by adithyamaheshb** [comment]
Thank you, for the suggestion!!

**Comment by iamdevlinph** [comment]
@adithyamaheshb were you able to achieve this using the zoom plugin?
