### ISSUE TITLE
Hover tooltip triggers weird grouped bar chart rendering

### ISSUE THREAD

**Issue by jleongbsmTech** [jerairrest/react-chartjs-2#357]
Hi this issue was made in chartjs [issue](https://github.com/chartjs/Chart.js/issues/5898)
where they suggested to post here
## Expected Behavior

This is made with chart js and reactjs
In a grouped bar chart with multiple datasets and custom tooltip, when you hover over a group expect the tooltip to show up and the chart does not rerender
Or it should rerender with the same data
When we hover over a group the others bars dissapear and we only show the last sections' bars

## Current Behavior

On the hover it renders only the 1 of my six bar chart data sets
![2018-12-06_17 06 31](https://user-images.githubusercontent.com/36748542/49615824-88fa8c80-f963-11e8-9fb9-499e671e54e8.gif)

## Possible Solution

I noticed the redraw option for charts will destroy, recreate a new bar chart. In that moment the canvas context can be null. That maybe the source of the issue, possibll have a null check in that function.

## Steps to Reproduce (for bugs)

1.Create a stacked bar chart with following data:

```barData: {
        datasets: [
          { data: [10, 20, 30, 50], label: "zz", backgroundColor: "#4286f4" },
          { data: [30, 20, 10, 40], label: "zz", backgroundColor: "#e5f94a" },
          { data: [0, 15, 20, 30], label: "zz", backgroundColor: "#f2264c" },
        ],
        labels: ["01/12", "02/12", "03/12", "04/12"],
      },
```

2. Have options with xAxes, yAxes stacked: false

```
hover: {
          onHover: (e: any) => {
            if (e && e.target) {
              e.target.style.cursor = 'pointer';
            }
          },
        },
```

tooltips: {enabled: false} <- okay since we are testing the hover interaction
3. have a hover action trigger different bar data to trigger a react rerender
4. hover over the grouped bar chart
5.  graph render is all wonky, renders only one section

## Context

I want to draw a custom tooltip when I hover over the grouped barchart to show the points clearly.
It seems to be a weird state transition and rendering issue

## Environment

* Chart.js version: 2.7.3
* react-chartjs version: 2.7.4
* Browser name and version: latest chrome
* Link to your project: https://codesandbox.io/s/98xm62929o

**Comment by Pringels** [comment]
@jleongbsmTech you need to use unique labels for your datasets. So in the case of your example you need to replace the `zz` labels on each dataset with a label specific to each dataset:

```
          { data: [10, 20, 30, 50], label: "xz", backgroundColor: "#4286f4" },
          { data: [30, 20, 10, 40], label: "yz", backgroundColor: "#e5f94a" },
          { data: [0, 15, 20, 30], label: "zz", backgroundColor: "#f2264c" },
```

Closing for now. Please create a new issue if you still experience problems after implementing this change.
