### ISSUE TITLE
Label position cannot be set via options for Doughnut chart

### ISSUE THREAD

**Issue by sanderdewijs** [jerairrest/react-chartjs-2#361]
First off, thanks for creating this component! 

I discovered an issue where I wanted to postion the label of a doughnut chart below the chart. I first tried it via the options like this:

```
options: {
	responsive: true,
	cutoutPercentage: 50,
	legend: {
		display: true,
		position: "bottom",
		labels: {
			fontSize: 14,
		}
	}
}
```
However this had no effect on the labels. I then tried setting the labels on the global defaults like:
defaults.global.legend.position = "bottom";

That did trigger the labels to be positioned at the bottom of the charts. But still it would be better to be able to control this per graph instead of setting the position globally.

**Comment by Pringels** [comment]
Closing as not relevant to wrapper. Please open a feature request with Chart.js directly
