### ISSUE TITLE
How can I set height of chart to 100%?

### ISSUE THREAD

**Issue by alexanderchoi** [jerairrest/react-chartjs-2#362]
Currently in the documentation there is way to set the height of the chart component to a specified pixel height via 
```
<Bar
	data={data}
	height={50}
	options={{
		maintainAspectRatio: false
	}}
/>
```

How can I make it so that instead of using pixels as a value, I can set the chart height to 100% (Therefore the height of its parent container)?

**Comment by tkeesling** [comment]
Do you want a specific aspect ratio?

**Comment by tkeesling** [comment]
It will fill its parent container if the height and width are not set, null, or an empty string. In the package, the default width and height are 300 and 150 respectively so the aspect ratio _always_ maintains a 2:1 (which is a bug IMO). So try this:
```
<Bar
	data={data}
	height={null}
        width={null}
	options={{
		aspectRatio: 1,  // this would be a 1:1 aspect ratio
	}}
/>```

**Comment by kybishop** [comment]
The above didn't work for me, but the following did:

```
<Line data={data} options={{ maintainAspectRatio: false }} />
```

**Comment by SenseiCain** [comment]
You can override the default styling in CSS
`canvas { height: 100 !important }`
