### ISSUE TITLE
How to set automatic width to the bar chart

### ISSUE THREAD

**Issue by souuu** [jerairrest/react-chartjs-2#363]
Hello,
The problem is that I have too many labels sometimes (it depends on the request).
when I have more than 200 labels :
<img width="1412" alt="capture d ecran 2018-12-21 a 18 01 23" src="https://user-images.githubusercontent.com/17356470/50354930-5f3d8a00-054d-11e9-929b-f37af2a61e30.png">
only 3 labels : 
<img width="1415" alt="capture d ecran 2018-12-21 a 18 02 31" src="https://user-images.githubusercontent.com/17356470/50354940-69f81f00-054d-11e9-9541-1a8685e6b714.png">

So, I want to set automatic width to the component so it always fits all the labels ( the parent div is set to overflow-x:scroll , so there is no problem even if the width is more than 5000)

Thank you,

**Comment by eudson** [comment]
@souuu  where you able to fix this?

**Comment by souuu** [comment]
Hello,
Yes I have fixed this.
I have made a function in the component called calculateWidth()
which returns the width depending on the count of lables.
So after some tests I have defined manually what are the counts that make problems.

```
                <Bar
                    height={400}
                    width={this.calculateWidth()}
                    data={data}
                    options={options}
                />
```

```
    calculateWidth() {
        const { x } = this.props
        let length = x ? x.length : 0
        switch (true) {
            case length >= 0 && length <= 3:
                return 400
            case length >= 4 && length <= 50:
                return 1200
            case length >= 51 && length <= 100:
                return 2000
            default:
                return 5000
        }
    }
```

I am here for any question

**Comment by eudson** [comment]
Does this make the chart to be horizontal scrollable? I will give a try

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
