### ISSUE TITLE
Redux with react-chartjs-2

### ISSUE THREAD

**Issue by SHolmes6** [jerairrest/react-chartjs-2#365]
hey,
I'm using react-chartjs-2 with react-redux and everytime i get a lot of data from the server the page crashes.
I've traced it down to the data needing clone because the chart.js tries to update it without the data changing.
The only solution i found until now was to add cloneDeep to the props.data in the transformDataProp function.
Is it possible to avoid this clone in any way? tried to prevent the update in the shouldComponentUpdate function but it didn't help.

**Comment by Tankenstein** [comment]
@SHolmes6 Thank you, this error would've been hard to track down without this issue.

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
