### ISSUE TITLE
I can't set gradient color for pointBorderColor and pointBackgroundColor properties at Chart Line

### ISSUE THREAD

**Issue by MacgyverMartins** [jerairrest/react-chartjs-2#366]
I can't set background gradient to ticks points when I use Line chart.
This is my code:
```javascript
    const data = canvas => {
      const ctx = canvas.getContext('2d');;
      let gradientStroke = ctx.createLinearGradient(500, 0, 100, 0);
      gradientStroke.addColorStop(0, '#80b6f4');
      gradientStroke.addColorStop(1, '#f49080');

      return {
        // some code ...
        borderColor: gradientStroke,
        pointBorderColor: gradientStroke,
        pointBackgroundColor: gradientStroke,
        fill: false
      }
}
```
And this is the output:
<img width="752" alt="screen shot 2019-01-15 at 16 30 23" src="https://user-images.githubusercontent.com/4551671/51204716-001c2c80-18e3-11e9-9dd2-d498d6685d0a.png">

As you can see, the point background is not the same as the gradient of the line
But when I use only Chart.js lib it works fine.
Here is an exemple: https://codepen.io/MacgyverMartins/pen/GPeEvQ

What can I be doing wrong?

**Comment by SkryGun** [comment]
I have noticed that this issue is occurring when you use react-chartjs-2 with **chart.js@2.7.3**  see in this project in dependencies https://stackblitz.com/edit/react-chart-issue , If you will change to **chart.js@2.7.2** then it will work.
