### ISSUE TITLE
Align line chart at left margin in mixed chart?

### ISSUE THREAD

**Issue by souuu** [jerairrest/react-chartjs-2#367]
Hello,
When I add line chart in data, it's automatically aligned to centers according to existing bar chart.
How to align it to the left or to the right of the bar ?

Thank you.

**Comment by tkeesling** [comment]
Can you show a screen shot?

**Comment by souuu** [comment]
I want to translate them to the extreme points of the bar like this
![translate](https://user-images.githubusercontent.com/17356470/51411697-1b986900-1b69-11e9-9ef6-6bbc1f35e927.png)
But the real goal is to colorize the space between the bars like this
<img width="909" alt="capture d ecran 2019-01-18 a 21 38 39" src="https://user-images.githubusercontent.com/17356470/51411840-a6796380-1b69-11e9-8a0f-dbf5d92de379.png">

**Comment by waleedshkt** [comment]
Try playing with `maxBarThicknes` and `barThickness` to manually set the bar width in pixels as shown below: 
```
options = {
    scales: {
        xAxes: [{
            barThickness: 6,
            maxBarThickness: 8,\
        }]
    }
};
```

And then you can offset your line dataset (x values) to the left along x-axis by using half of bar's width and subtracting it from each x value of line plot
