### ISSUE TITLE
Bar component misses to show last bar in the histogram

### ISSUE THREAD

**Issue by reetak18** [jerairrest/react-chartjs-2#369]
Bar Example (custom size) in http://jerairrest.github.io/react-chartjs-2/ does not show bar for July value, although on hovering it shows data. Same issue I face when I use Bar component in my project. It does not happen always but for some histograms

**Comment by gj1118** [comment]
@reetak18 , Can you please post a screenshot ? I am facing the same issue but with Line Graphs.

**Comment by waleedshkt** [comment]
Set the following options:
```
options = {
  scales: {
    xAxes: [{
      beginAtZero: true,
    }]
  }
}
```

**Comment by yuyoux** [comment]
same

**Comment by yuyoux** [comment]
https://github.com/jerairrest/react-chartjs-2/issues/262
