### ISSUE TITLE
Mixed chart

### ISSUE THREAD

**Issue by asia653** [jerairrest/react-chartjs-2#371]
If you try to mix a bar chart into a line chart, it does not work
Mixing a line chart into a bar chart does work (as the examples show)

**Comment by JoshAudibert** [comment]
I'm having this issue as well.

**Comment by waleedshkt** [comment]
Check out the [solution](https://github.com/jerairrest/react-chartjs-2/issues/400#issuecomment-492467787) given in a similar issue

**Comment by scailbc** [comment]
Seems like a problem of Chart.js, see chartjs/Chart.js#4587.

Maybe it'r related to what they say in [chartjs docs](https://www.chartjs.org/docs/latest/charts/mixed.html):
> It's important to note that the default options for a line chart are not merged in this case. **Only the options for the default type are merged in**. In this case, that means that the default options for a bar chart are merged because that is the type specified by the type field.

**Comment by hay** [comment]
I solved this issue (combining scatter with line) by simply setting the type of the chart to line, then setting `showLine` to `false` in the 'scatter' dataset. Note that the `line` chart type also accepts data in the `x/y` format. Maybe not the most elegant solution, but it works.

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
