### ISSUE TITLE
Border's not properly applied for HorizontalBar chart

### ISSUE THREAD

**Issue by jontravaille** [jerairrest/react-chartjs-2#372]
I've been trying out HorizontalBar chart using the sample data on Chart.js documentation page, but here's what I got.
![screen shot 2019-01-31 at 12 12 03 pm](https://user-images.githubusercontent.com/31975376/52028276-c0e01380-2551-11e9-95f7-cca866e59ea7.png)

The border's applied in a same way the original (vertical) bar does - border on left, top and right but not bottom. Pretty sure this is not what HorizontalBar content is intended to be, according to the sample demonstrates(https://www.chartjs.org/samples/latest/charts/bar/horizontal.html - borders are applied on top, right, and bottom)
I don't think it's a matter of options or styles. 

Thanks!

**Comment by waleedshkt** [comment]
You can add the bottom border yourself.
[Here](https://stackoverflow.com/questions/48281600/chart-js-add-border-around-line-chart-and-yaxis-unit-title-s/50023933) is a similar issue which gets resoved by playing with y- and x-axis configuration in chart's options object.

Hope this helps

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
