### ISSUE TITLE
Bar doesn't render some data

### ISSUE THREAD

**Issue by 4protete** [jerairrest/react-chartjs-2#375]
**Actual result:** Bar doesn't render some data if the last element of the dataset is equal prevElement+1
**Expected result:** All data from the dataset are displayed on the chart

**Here you can check the result:** https://codesandbox.io/s/0m6p3ymwl

**Screenshot:**
![image](https://user-images.githubusercontent.com/26570561/52352135-baabd480-2a34-11e9-9201-a3e09e1757a2.png)

**Comment by thdk** [comment]
By default the y axes doesn't start at zero. 
Two out of three of your data have a value of 3. Look on your y axes. It start at three so you don't see any bar for those two values.

You need to add the following on the same level as 'labels' and 'datasets':

```
options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
```
