### ISSUE TITLE
how to get intersection of 2 line charts?

### ISSUE THREAD

**Issue by zilahir** [jerairrest/react-chartjs-2#376]
Hi! 

Is it possible to get 2 chart's intersection point? 

I have these 2 line charts, and I want to show a tooltips where they intersect. How can i achieve this? 

It's not obvious from the docs. 

<img width="799" alt="screen shot 2019-02-07 at 15 49 09" src="https://user-images.githubusercontent.com/6687149/52415547-f0fa5a00-2aef-11e9-936e-f570ec34c797.png">

**Comment by zilahir** [comment]
or, as alternative solution, i could show a specific tooltip always, but i need to calculate which one based on where they are intersect. this would be possible if the intersection is not?

**Comment by waleedshkt** [comment]
There is no direct solution to get the intersecting point of plots made of discrete datasets.
You can however (in your simple case) can get it using for loop. But this will only give you estimate()or can exact point):

In your case, as one line has constant y value, run for loop for other line dataset and determine when y value of other line crosses that constant line y value.
Or to go extra mile to really get the accurate intersecting point, add some math. Derive linear equations for each line and work out the x where both equations are equal :)

**Comment by Pringels** [comment]
Closing as not within scope of library's functionality
