### ISSUE TITLE
borderDash doesn't work for Bars

### ISSUE THREAD

**Issue by Shtokins** [jerairrest/react-chartjs-2#381]
It seems like borderDash doesn't work for Bar anymore. My example: 
https://codesandbox.io/s/nnwl1kp7jl
As you can see label is dashed, but Bars' borders are still solid.
What could be wrong here?..

**Comment by Pringels** [comment]
@Shtokins this library is only a react wrapper component. All chart rendering is done by Chart.js. Please open an issue there: https://github.com/chartjs/Chart.js

Closing for now
