### ISSUE TITLE
Stack bar - multi stack

### ISSUE THREAD

**Issue by andreaci** [jerairrest/react-chartjs-2#382]
New feature proposal.
Multi stack like in this picture:

![2019-02-15_15-34-02](https://user-images.githubusercontent.com/8290389/52863112-3db8e300-3137-11e9-94ed-884a13352a62.png)

I already implemented in my fork:
https://github.com/andreaci/react-chartjs-2/commit/4c1f5b04eb332e68c1f6e24fc21f76acb0636d63

to use it, just add "stack: <number>" in the dataset structure

**Comment by Pringels** [comment]
Already implemented in Chart.js itself: https://www.chartjs.org/docs/latest/charts/bar.html#stacked-bar-chart

Closing

**Comment by Konstanty** [comment]
NOTE: This isn't the same, as Chart.js only stacks EVERYTHING, not selected things like the proposal.

**Comment by Masayukiii** [comment]
Is there a good way to do it?
