### ISSUE TITLE
Draw a vertical line 

### ISSUE THREAD

**Issue by gj1118** [jerairrest/react-chartjs-2#383]
Hi , I am interested to know if I can draw a vertical line parallel to the Y axis and perpendicular to the x axis when a point is hovered, something like https://jsfiddle.net/haq5k2mw/ 

Can you please let me know how this can be achieved ?  

Thanks
Gagan

**Comment by kaungmyatlwin** [comment]
I was able to do this.

```javascript
import { Chart, Line } from 'react-chartjs-2';

...
...

componentWillMount() {
    Chart.pluginService.register({
      afterDraw: function(chart, easing) {
        if (chart.tooltip._active && chart.tooltip._active.length) {
          const activePoint = chart.controller.tooltip._active[0];
          const ctx = chart.ctx;
          const x = activePoint.tooltipPosition().x;
          const topY = chart.scales['y-axis-0'].top;
          const bottomY = chart.scales['y-axis-0'].bottom;

          ctx.save();
          ctx.beginPath();
          ctx.moveTo(x, topY);
          ctx.lineTo(x, bottomY);
          ctx.lineWidth = 2;
          ctx.strokeStyle = '#e23fa9';
          ctx.stroke();
          ctx.restore();
        }
      }
    });
}
```

Reference: https://github.com/jerairrest/react-chartjs-2#chartjs-object

**Comment by waleedshkt** [comment]
@gj1118, if you are satisfied with the above solution, you can close this issue then :)

**Comment by zebralight** [comment]
Is there a version of this that will allow me to draw a vertical line based on the index of the data point?  Much like this example: http://jsfiddle.net/dbyze2ga/14/ which I got from here: https://stackoverflow.com/questions/30256695/chart-js-drawing-an-arbitrary-vertical-line ? I can't seem to access `this.datasets` from the `draw` function as it shows in the example.

**Comment by Pringels** [comment]
Closing as not relevant to wrapper

**Comment by james-dillon** [comment]
@kaungmyatlwin Great solution, thanks! For others who are trying to use this, note that I had to put this code in the "componentWillMount()" method of the _parent_ component, not in the component that holds the Chart element. I was stumped for a while, trying to put the plugin code on the same page the react-chartjs-2 element was located. In case that's helpful to others. 

**chartpage.jsx**  // base chart webpage for my app
   getChartData();     // AJAX call to get chart data
   componentWillMount( ) {
      // _put above plugin code here_
   };
   render () {
      return (
         <MyChartComponent> // this element imports from myChartComponent.jsx, below
      );
   }

**myChartComponent.jsx**
   render() {
      return (
         <Chart type="line" data={this.state.data} ...... />    // chart element from 'react-chartjs-2'
      );
   }

` **chartpage.jsx**  // base chart webpage for my app
   getChartData();     // AJAX call to get chart data
   componentWillMount( ) {
      // _put above plugin code here_
   };
   render () {
      return (
         <MyChartComponent> // this element imports from myChartComponent.jsx, below
      );
   }

**myChartComponent.jsx**
   render() {
      return (
         <Chart type="line" data={this.state.data} ...... />    // chart element from 'react-chartjs-2'
      );
   }
`

**Comment by alina4irelabs** [comment]
I have similar variant for **react** with **type script**

```java script
import { Line } from 'react-chartjs-2';

const plugins = [
    {
      afterDraw: (chart: { tooltip?: any; scales?: any; ctx?: any }) => {
        // eslint-disable-next-line no-underscore-dangle
        if (chart.tooltip._active && chart.tooltip._active.length) {
          // find coordinates of tooltip
          const activePoint = chart.tooltip._active[0];
          const { ctx } = chart;
          const { x } = activePoint.element;
          const topY = chart.scales.y.top;
          const bottomY = chart.scales.y.bottom;

          // draw vertical line
          ctx.save();
          ctx.beginPath();
          ctx.moveTo(x, topY);
          ctx.lineTo(x, bottomY);
          ctx.lineWidth = 1;
          ctx.strokeStyle = '#1C2128';
          ctx.stroke();
          ctx.restore();
        }
      },
    },
  ];
```
component:
```java script
<Line type="line" data={data} options={options} plugins={plugins} />
```
**result:**
![Screenshot 2021-07-07 at 17 55 16](https://user-images.githubusercontent.com/80710083/124781993-86fa6f00-df4c-11eb-995b-ef507eecc7e7.png)

**Comment by mirhamasala** [comment]
Any way of solving the typing issue without having to use `any` and disable TS rules?

``` 
const plugins = [
    {
      id: "tooltipLine",
      afterDraw: (chart: { tooltip?: any; scales?: any; ctx?: any }) => {
        /* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call */
        if (chart.tooltip?.opacity === 1) {
          const { ctx } = chart;
          const { caretX } = chart.tooltip;
          const topY = chart.scales.y.top;
          const bottomY = chart.scales.y.bottom;

          ctx.save();
          ctx.setLineDash([3, 3]);
          ctx.beginPath();
          ctx.moveTo(caretX, topY - 5);
          ctx.lineTo(caretX, bottomY);
          ctx.lineWidth = 1;
          ctx.strokeStyle = getRgba(colors.white, 0.5);
          ctx.stroke();
          ctx.restore();
        }
        /* eslint-enable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call */
      },
    },
  ];
```

**Comment by mirhamasala** [comment]
If you want to [type your code](https://stackoverflow.com/questions/71411374/typescript-issue-with-custom-plugin-and-afterdraw-callback-chart-js-and-react-ch/71411811#71411811) ☝🏼

**Comment by mathikp** [comment]
@kaungmyatlwin Your code works for me. But I want to draw a dotted line instead of a normal line. Can you please help me?
