### ISSUE TITLE
npm version 2.7.5 does not contain latest changes

### ISSUE THREAD

**Issue by bdwade100** [jerairrest/react-chartjs-2#389]
Hi @jerairrest--

Thanks for including my pull request from a few days ago. Unfortunately, it doesn't look like the npm module for version 2.7.5 has the correct build files and folders (i.e., it looks like "npm run build" didn't work correctly).

Will you check?

Here's what I see when I run "npm install" for version 2.7.5:

- "dist" folder: Does not exist
- "es" folder: Contains changes to "src/index.js" from 9/23/2018 (commit = 6a005451a3)
- "lib" folder: Contains changes to "src/index.js" from 9/23/2018 (commit = 6a005451a3)
- All other folders and files are correct

However, if I revert to version 2.7.4 and run "npm install", the three folders above have the correct file contents.

Please see attached files.

Thanks,
Brad

[react-chartjs-2_2.7.4.zip](https://github.com/jerairrest/react-chartjs-2/files/3014524/react-chartjs-2_2.7.4.zip)
[react-chartjs-2_2.7.5.zip](https://github.com/jerairrest/react-chartjs-2/files/3014525/react-chartjs-2_2.7.5.zip)

**Comment by jerairrest** [comment]
Sorry about that! Try 2.7.6

**Comment by bdwade100** [comment]
Looks great. Thanks for the quick fix!
