### ISSUE TITLE
Couldn't able to get the index from x-axis label click

### ISSUE THREAD

**Issue by saranchandru** [jerairrest/react-chartjs-2#390]
Hi @jerairrest,
     Can you help to get the x-axis label click event, please?

Sample from the Chart JS library
https://codepen.io/jordanwillis/pen/gmdGGw

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
