### ISSUE TITLE
In Horizontal Bar Chart Example, Not All 7 Records Showing

### ISSUE THREAD

**Issue by pkellner** [jerairrest/react-chartjs-2#391]
In your own example, the bottom bar is missing.

Scroll down inhttp://jerairrest.github.io/react-chartjs-2/ "Horizontal Bar Example" and notice that there is no bar for July.  In my case, I had 10 bars and only the first 5 showed up.

**Comment by davie-robertson** [comment]
it needs to have beginAtZero set in the options, see https://www.chartjs.org/docs/latest/axes/cartesian/linear.html

**Comment by waleedshkt** [comment]
@pkellner, 
As @davie-robertson said, try adding the following `option` configL

```
options = {
  scales: {
    aAxes: [{
      beginAtZero: true,
    }]
  }
}
```

**Comment by rastating** [comment]
Should anyone else come across this, the above options config is incorrect. The correct options to use is:

```javascript
{
  scales: {
    xAxes: [{
      ticks: { beginAtZero: true }
    }]
  }
}
```

**Comment by Pringels** [comment]
The example code will in all likelihood be overhauled as part of the Chart.js 3 release. 

Closing this issue for now.
