### ISSUE TITLE
Unable to zoom or pan in React-chartsjs-2 charts

### ISSUE THREAD

**Issue by thetinshusasi** [jerairrest/react-chartjs-2#392]
Hi ,
I am using react-chartjs-2 in my project. 
i have also imported 
hammerjs, chartjs-plugin-zoom

However Zoom and span is  not working . Request you  to provide a working demo/ sample for this functionality and If possible could you provide an time series example.

**Comment by waleedshkt** [comment]
Check out [this Stackoverflow issue](https://stackoverflow.com/questions/46346078/zoom-and-pan-in-react-chartjs-2)

Hope it helps.
