### ISSUE TITLE
Misaligned version

### ISSUE THREAD

**Issue by cuongn265** [jerairrest/react-chartjs-2#394]
Hi, Chart.js library version are now in 2.8.0 but I found this we are using 2.6.0. Is there any plan to migrate to 2.8.0?

**Comment by plotka** [comment]
Is there any news regarding this?

**Comment by Pringels** [comment]
@cuongn265 @plotka This will be addressed as part of the Chart.js 3 release branch we're currently planning. This should be finalized early next year sometime.

Related: https://github.com/jerairrest/react-chartjs-2/issues/441

Closing for now
