### ISSUE TITLE
canvas-prebuilt dependency incompatible with Node 11, please upgrade 

### ISSUE THREAD

**Issue by tomclague** [jerairrest/react-chartjs-2#397]
I have been grappling with the problem described here https://github.com/node-gfx/node-canvas-prebuilt/issues/62 ; where earlier versions of canvas-prebuilt are incompatible with Node 11.

In my project, the dependency on "canvas-prebuilt": "^1.6.5-prerelease.1", comes from react-chartjs-2. Can you upgrade to use more recent please?

**Comment by Pringels** [comment]
@tomclague this will be done as part of the release that coincides with Chart.js 3.

Closing
