### ISSUE TITLE
Line Chart squishes to one line on re-render

### ISSUE THREAD

**Issue by nickjryan95** [jerairrest/react-chartjs-2#401]
I am using this to display data over time in an application, and there are times the chart seems to collapse when the page re-renders. The chart goes from [looking like this](https://puu.sh/Dp5pm/cdc176d26c.png) to [looking like this](https://puu.sh/Dp5sx/9ecaf57b2a.png). The data isn't changing at all between the two.

The data object looks like this (where the variables labels, pred, actual, upper, and lower are the appropriate arrays):
`const histogramData = {
        labels,
        datasets: [{
          pointBorderColor: '#3fa9f5',
          pointBackgroundColor: '#3fa9f5',
          data: pred,
          showLine: false,
        },
        {
          pointBorderColor: '#ff0001',
          pointBackgroundColor: '#ff0001',
          data: actual,
          showLine: false,
        },
        {
          borderColor: '#d0e6f5',
          backgroundColor: '#d0e6f5',
          data: upper,
          fill: '+1',
        },
        {
          borderColor: '#d0e6f5',
          backgroundColor: '#d0e6f5',
          data: lower,
          fill: '-1',
        }],
`

Where I am rendering the chart itself it looks like this:
`<Line
                  data={histogramData}
                  width={100}
                  height={200}
                  options={{
                    legend: {
                      display: false,
                    },
                    maintainAspectRatio: false,
                  }}
                />`

If anyone has any idea on how to fix this or make it not happen, it has been a thorn in my side for a while now. Thanks!

**Comment by waleedshkt** [comment]
When you say page re-renders do you mean updating the chart data?

By the way, are you wrapping the chart in its own react component or simply adding the `<Line ... />` in your page containing other components?

**Comment by waleedshkt** [comment]
I believe this your issue (_taken from offical docs_):

> **Working with Multiple Datasets**
> You will find that any event which causes the chart to re-render, such as hover tooltips, etc., will cause the first dataset to be copied over to other datasets, causing your lines and bars to merge together. This is because to track changes in the dataset series, the library needs a key to be specified - if none is found, it can't tell the difference between the datasets while updating. To get around this issue, you can take these two approaches:
> 
> Add a `label` property on each dataset. By default, this library uses the `label` property as the key to distinguish datasets.
> Specify a different property to be used as a key by passing a `datasetKeyProvider` prop to your chart component, which would return a unique string value for each dataset.

So try adding `label` in each of your datasets objects. It can be any value e.g 0, 1. They'll appear as legends in your plot. But since you have hidden the `legend`, it should be all good.

**Comment by Pringels** [comment]
Closing. Reason: older than 6 months and not enough or outdated information supplied. Please re-open this issue if the problem persists, but provide more information. (including a sandbox link if possible)
