### ISSUE TITLE
Width Keeps Growing

### ISSUE THREAD

**Issue by nugz1012** [jerairrest/react-chartjs-2#404]
Below is a test case I built using tabs from antd. The width goes on forever when switching to the chart tab. I want the chart to fill the column and not set an actual width. When loading in the sandbox, if the 1st tab is the default and you switch, the issue occurs. If you switch the default to be the chart tab and load it in, no issue occurs. Maybe I am not wrapping the chart correctly. Can anyone verify I'm not doing something incorrect?
https://codesandbox.io/embed/reverent-wind-h0ej6

**Comment by RoudyTarabay** [comment]
I think it's a bug when using maintainAspectRation:false. Keep it as true and it will work

**Comment by Pringels** [comment]
@nugz1012 try setting the responsive property to false - `responsive: false`

Closing as not relevant to wrapper
