### ISSUE TITLE
Deprecated warning on React 16.9.0-alpha.0

### ISSUE THREAD

**Issue by AskAlexSharov** [jerairrest/react-chartjs-2#405]
Next warning appeared: 

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
```

**Comment by zubhav** [comment]
Update on this -  React 16.9 stable has been released and the warning appears as follows:

<img width="1163" alt="Screen Shot 2019-08-09 at 10 55 29" src="https://user-images.githubusercontent.com/9058689/62771096-4e1d9b00-ba94-11e9-8813-704999adaf36.png">
