### ISSUE TITLE
Unable to use timeseries 

### ISSUE THREAD

**Issue by Nutties93** [jerairrest/react-chartjs-2#408]
Hi, it seems like the current react-chartjs2 doesn't support timeseries? my code doesn't seem to work.

                    <Line          
                        redraw={true}      
                                
                        data={{
                            // Labels should be Date objects
                            datasets: [{
                                label: 's1',
                                borderColor: 'blue',
                                data: [
                                  { x: '2017-01-06 18:39:30', y: 100 },
                                  { x: '2017-01-07 18:39:28', y: 101 },
                                ]
                              }, {
                                label: 's2',
                                borderColor: 'red',
                                data: [
                                  { x: '2017-01-07 18:00:00', y: 90 },
                                  { x: '2017-01-08 18:00:00', y: 105 },
                                ]
                              }]
                        }}
                        options={{
                            scales: {
                              xAxes: [{
                                type: 'time'
                              }]
                            }
                          }}
                    />

**Comment by zacherkkila** [comment]
I opened an issue (#409) for another reason but I was able to get the time series working by using the parser option, how I used the parser might give you some clues on how I was able to do it

**Comment by Pringels** [comment]
@Nutties93 Please provide a code sandbox example that replicates the issue you are experiencing.

**Comment by hanupratap** [comment]
Any update on this ?
