### ISSUE TITLE
Hide legend per dataset

### ISSUE THREAD

**Issue by dwade0o** [jerairrest/react-chartjs-2#412]
Is it possible to add an attribute called 'hiddenLegend' to the dataset level to determine whether the legend should be shown? My project uses python to generate the line chart json data and pass it to react chartjs. Using the filter function in python doesn't seem to be obvious.

**Comment by Pringels** [comment]
@dwade0o please see https://stackoverflow.com/questions/47084144/is-it-possible-in-chartjs-to-hide-certain-dataset-legends

Closing as not relevant to wrapper
