### ISSUE TITLE
Draggable: is there any builtin method which can allow drag on Bar and Pie 

### ISSUE THREAD

**Issue by reaganscofield** [jerairrest/react-chartjs-2#413]
Draggable: is there any builtin method which can allow drag on Bar and Pie to drag out a bar chart

**Comment by Pringels** [comment]
@reaganscofield do you mean something like this? https://github.com/chrispahm/chartjs-plugin-dragdata

I don't think `chart.js` supports this natively, which means the react wrapper doesn't either.

**Comment by Pringels** [comment]
Closing for now. If you would like to see draggable points as a feature in Chart.js please open a feature request issue here: https://github.com/chartjs/Chart.js/issues
