### ISSUE TITLE
Namespace '"ChartData"' no exported from 'chart.js' ????error

### ISSUE THREAD

**Issue by freedomhunter** [jerairrest/react-chartjs-2#415]
I got this error when i am trying to use "react-chartjs-2" in React typescript. There's a file in react-chartjs-2 in node modules called " index.d.ts ". Chartdata is present there and it is imported from chart.js file but its showing all red.........Can anyone help me out with this issue??
![error](https://user-images.githubusercontent.com/32976566/60431993-be780780-9c1e-11e9-82fa-f29be67f0c62.png)

**Comment by snerks** [comment]
Have you also installed the `chart.js` package?

e.g:
`npm i -S chart.js`

**Comment by Pringels** [comment]
@freedomhunter try install the `chart.js` library and try again.
If the problem persists please open an issue here: https://github.com/chartjs/Chart.js/issues
