### ISSUE TITLE
Can I set the range in radar chart?

### ISSUE THREAD

**Issue by RonenHong** [jerairrest/react-chartjs-2#416]
Dear,
radar chart show it from minimum value to maximum value in data 
for example, 
When I have data like data : [65, 59, 90, 81, 56, 55, 40]
I want to show them in range 0 to 100 not 40 to 90

Thanks you

**Comment by kaizerroll** [comment]
You can explicitly set the range using the options prop. It should look something like this:

```js
const data = {
  labels: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
  datasets: [{
    label: 'My results',
    data: [65, 59, 90, 81, 56, 55, 40]
  }]
}

const options = {
  scale: {
    ticks: {
      min: 0,
      max: 100,
      stepSize: 10
    }
  }
}

const RadarChart = <Radar data={data} options={options} />
```

Hope this helps!

Source: https://stackoverflow.com/questions/39249722/set-min-max-and-number-of-steps-in-radar-chart-js#_=

**Comment by RonenHong** [comment]
👍
