### ISSUE TITLE
Issue with bar and line chart.

### ISSUE THREAD

**Issue by holzfelix** [jerairrest/react-chartjs-2#423]
I tried this example to get working:

https://github.com/jerairrest/react-chartjs-2/blob/master/example/src/components/mix.js

but got this error: https://codesandbox.io/embed/friendly-zhukovsky-rvf4l

![image](https://user-images.githubusercontent.com/6866699/61954909-3802db80-afba-11e9-8b4e-23f792ba0446.png)

**Comment by Pringels** [comment]
Duplicate of #441
