### ISSUE TITLE
Box and Violin Plots

### ISSUE THREAD

**Issue by apierr** [jerairrest/react-chartjs-2#424]
There is **Chart.js Box Plot addons** available at this address https://github.com/datavisyn/chartjs-chart-box-and-violin-plot
I would like to use it via the following syntax:

```javascript
import { Violin, Box } from 'react-chartjs-2';

<Violin data={...} />
<Box data={...} />
```
Do you think that such an implementation is desirable and feasible?

**Comment by Pringels** [comment]
I don't see this as particularly desirable or feasible to be honest. 
Doing so would add`chart.js` as a transitive dependency, which is not ideal, as we rely on chart.js being a peer dependency. (see https://github.com/jerairrest/react-chartjs-2#update-to-2x)

It would rather create separate React wrapper components for those addons.
