### ISSUE TITLE
how to apply custom positioner to a chart?

### ISSUE THREAD

**Issue by bharatgupta99** [jerairrest/react-chartjs-2#427]
Basically, I want to access Chart.defaults.positioners to  make my custom tooltip to render on top left side. 
As mentioned in chart.js documentation, customer positioner can be used to make this happen.

**Comment by Pringels** [comment]
Relevant section in the docs:
https://www.chartjs.org/docs/latest/configuration/tooltip.html#position-modes

**Comment by Pringels** [comment]
@bharatgupta99 seeing as `chart.js` is a peer dependency, you could always import the constructor directly and add your custom positioner:

```js
import { Chart } from 'chart.js'

Chart.Tooltip.positioners.custom = function(elements, eventPosition) {...};
```

Closing this for now. Please re-open it of you discover that this approach does not work for you. (preferably with a code example)
