### ISSUE TITLE
Stacking Legend Bars

### ISSUE THREAD

**Issue by marycodes2** [jerairrest/react-chartjs-2#428]
Wondering if you're able to stack the legend bars for a chart, like in this screenshot:

![Screen Shot 2019-08-13 at 9 36 03 AM](https://user-images.githubusercontent.com/39474777/62946595-fee6ab80-bdae-11e9-8e18-8d5c536a8b71.png)

Let me know - thanks!!

**Comment by yash-thakur** [comment]
Yes you can easily do it.

I was able to do the following example using the same:
<img width="248" alt="Screenshot 2019-08-18 at 10 43 16 PM" src="https://user-images.githubusercontent.com/14192483/63227931-ac234e80-c209-11e9-970f-e7fb7c74d063.png">

**Comment by marycodes2** [comment]
@yash-thakur thanks! - how were you able to achieve this? Could you share a code snippet?

**Comment by yash-thakur** [comment]
Sorry for the late reply @marycodes2 . This was my approach to the above solution:
  
     const data = {
      labels: [
        'Reddit',
        'Facebook',
        'Twiiter'
      ],
      datasets: [{
        data: [1073111, 65551, 40020],
        backgroundColor: [
          '#416ab6',
          '#429ded',
          '#68efa6'
        ],
        hoverBackgroundColor: [
          '#416ab6',
          '#429ded',
          '#68efa6'
        ]
      }]
    };
    
    const options = {
      responsive: true,
      legend: {
        display: false,
      },
      animation: {
        animateScale: true,
        animateRotate: true,
      },
      legendCallback: (chart) => {
        const text = [];
        text.push('<table class="list-none w-full mt-16">');
        text.push('<tbody>');
        // eslint-disable-next-line
        for (let i = 0; i < _.first(chart.data.datasets).data.length; i++) {
          // console.log(chart);
          const meta = chart.chart.legend.legendItems[i];
          text.push('<tr>');
          text.push(`<td class="pr-8 pb-12"> ${meta.text}</td>`);
          text.push(`<td class="rounded-full inline-block align-middle pb-12" style="height: 12px; width: 12px; background-color: ${_.first(chart.data.datasets).backgroundColor[i]};"></td>`);
          text.push(`<td class="pl-8 font-bold pb-12"> ${_.first(chart.data.datasets).data[i].toLocaleString()}</td>`);
          text.push('</tr>');
        }
        text.push('</tbody>');
        text.push('</table>');
        return text.join('');
      },
    };
    return (
        <div className="w-full">
            <Doughnut
                data={data}
                options={options}
                ref="chart"
                height={100}
                width={90}
             />
             {
                // eslint-disable-next-line
                this.refs.chart &&
                // eslint-disable-next-line
                htmlToReactParser.parse(this.refs.chart.chartInstance.generateLegend())
             }
        </div>
    );

**Comment by GangadharG** [comment]
@yash-thakur, I tried exactly like above, legends are not displaying for me.

@marycodes2, Is it working for you?. If working, Please share your inputs on this.

**Comment by yash-thakur** [comment]
@GangadharG I have used Tailwind CSS classes to make it look like the screenshot. You can use the css that you are using in your template or else go with inline CSS.
