### ISSUE TITLE
Can we show only first and last label (Bar chart)

### ISSUE THREAD

**Issue by zahid49** [jerairrest/react-chartjs-2#431]
Is there any way, we can display only first and last label for Bar chart.
Something like:
![screenshot-app zeplin io-2019 08 19-13-51-18](https://user-images.githubusercontent.com/31693580/63253241-e41ea600-c28a-11e9-853e-c232dc660679.png)

Thanks in advance!

**Comment by Pringels** [comment]
@zahid49 Please take a look at the Chart.js documentation to see what's possible:
https://www.chartjs.org/docs/latest/

Closing as not relevant to wrapper
