### ISSUE TITLE
show the value of the last bar on top

### ISSUE THREAD

**Issue by zahid49** [jerairrest/react-chartjs-2#432]
Is there an option to show the value of the last bar on top, As in following the image 
![screenshot-app zeplin io-2019 08 19-13-51-18](https://user-images.githubusercontent.com/31693580/63253445-4e374b00-c28b-11e9-8f5c-d016d67d66bb.png)

**Comment by Pringels** [comment]
@zahid49 Please take a look at the Chart.js documentation to see what's possible:
https://www.chartjs.org/docs/latest/

Closing as not relevant to wrapper
