### ISSUE TITLE
unable to get the value of labels on click event

### ISSUE THREAD

**Issue by sumit09211** [jerairrest/react-chartjs-2#433]
I am facing a problem while getting the value of each label by clicking on it.
I have attached a screenshot in which I want to get the value(blue) on click of that point.

![issue](https://user-images.githubusercontent.com/21311043/63412370-42779000-c415-11e9-843f-a1f999ad9725.png)
![issue2](https://user-images.githubusercontent.com/21311043/63746912-7d6d3e00-c8c3-11e9-84e2-7ceb3fe1676c.png)

**Comment by reachtokish** [comment]
hey @sumit09211 could you share code snippet which you are using to get the value?

**Comment by sumit09211** [comment]
`<Radar
									data={radarData}
									options={{
										onClick: this.visitorsRadarDrilldownHandler,
										responsive: true,
									}}
								/>

visitorsRadarDrilldownHandler = (e, item) => {
		console.log(item)
};

radarData: {
    labels: ["blue", "green"],
    datasets: [
        {
            label: "blue",
            backgroundColor: "rgba(179,181,198,0)",
            data: [42, 10]
        },
        {
            label: "green",
            backgroundColor: "rgba(255,99,132,0)",
            data: [12, 28]
        }
    ]
}

`

**Comment by artinbajcinca** [comment]
For Radar Graph use
`onClick : (e, item) => {item[0]['_chart'].controller.config.data.labels[item[0]['_index']])}`

**Comment by Pringels** [comment]
Closing as not related to wrapper
