### ISSUE TITLE
IE11 destroyChart Object.values

### ISSUE THREAD

**Issue by 0chris** [jerairrest/react-chartjs-2#435]
I'm having issues in IE.
When I destroyChart is called and chartjs crashes due to Object.values incompatibility. 

` ChartComponent.prototype.destroyChart = function destroyChart() {
    this.saveCurrentDatasets();
    var datasets = Object.values(this.datasets);
    this.chartInstance.config.data.datasets = datasets;
    this.chartInstance.destroy();
  };
`

**Comment by Pringels** [comment]
@SolaialaguB Based on your description it seems that the error lies with Chart.js.
Please open an issue there: https://github.com/chartjs/Chart.js/issues

Closing as not relevant to wrapper
