### ISSUE TITLE
How to disable labels and Y axis data view?

### ISSUE THREAD

**Issue by peazz** [jerairrest/react-chartjs-2#445]
I looked through examples but couldnt find anything there at all.

I need to remove labels and the Y axis from a Linechart, how can I do this?

**Comment by Pringels** [comment]
@peazz This can be done by configuring chart-js itself. 

Take a look at these two links: 
https://www.chartjs.org/docs/latest/axes/styling.html#grid-line-configuration
https://www.chartjs.org/docs/latest/axes/labelling.html#scale-title-configuration

Closing as not applicable to wrapper library
