### ISSUE TITLE
How to rotate the chart

### ISSUE THREAD

**Issue by usama-asfar** [jerairrest/react-chartjs-2#446]
when browser resize to phone mode, I need to rotate the chart to stretch the whole screen, How can I able to that?
![Screenshot from 2019-10-13 19-13-04](https://user-images.githubusercontent.com/42825498/66716655-d8b0ac80-eded-11e9-8bb7-1b6082a9d3f6.png)

**Comment by AndriyMartynyshyn** [comment]
Try to use [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) and [CSS rotate](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate)

**Comment by Pringels** [comment]
Closing issue at it falls beyond the scope of this library
