### ISSUE TITLE
[Features] add padding properties side of legend label

### ISSUE THREAD

**Issue by consciousnessdev** [jerairrest/react-chartjs-2#447]
I work with version 2.7.6, and need padding only for top side label of legend, but on this version was for each side of label, so when i set padding of label legend padding it affects all sides then left and right sides expand each other, i mean need adding padding properties like layout padding, some like this:

```javascript
{
  ...
  legend: {
      labels: {
        padding: {
          top:35,
          right:0,
          bottom:0,
          left:0
        }
      },
    ...
  },
  ...
}
````

**Comment by Pringels** [comment]
@consciousnessdev the react wrapper is not responsible for the rendering of legend labels. It simply passes through your configuration to Chart.js itself. Please open a feature request there: https://github.com/chartjs/Chart.js/issues

**Comment by shreya-14-may** [comment]
<img width="804" alt="Screenshot 2021-05-18 at 4 46 06 PM" src="https://user-images.githubusercontent.com/69234158/118642070-8bca5e80-b7f8-11eb-9586-442f7f64b661.png">
After applying

$chart->options([
                    'stack'=> 'Stack 0',
                    **"height" => 640,**


                    "responsive" =>true,
                    "animateScale" =>true,
                    "legend" =>[
                        "show" => true,
                        "bottom" => -40,
                    ],
                    ]);
                    
                    THe charts are hidden
