### ISSUE TITLE
React 17 - deprecation warning

### ISSUE THREAD

**Issue by cipacda** [jerairrest/react-chartjs-2#448]
React 17 will deprecate componentWillMount. 

With React 16.8.6 I am getting the following warning: 

> backend.js:1 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ChartComponent

**Comment by JoeNyland** [comment]
You might want to make sure that you're using 2.8.0 of this package as the reference to `componentWillMount()` in `ChartComponent` has been removed in https://github.com/jerairrest/react-chartjs-2/pull/426.

**Comment by Pringels** [comment]
Closing for now. @cipacda please bump your version to > 2.8.0 and try again.
