### ISSUE TITLE
Chart.js 3.0

### ISSUE THREAD

**Issue by benmccann** [jerairrest/react-chartjs-2#457]
Hi, we're working on Chart.js 3.0. I've sent https://github.com/chartjs/Chart.js/pull/6778 in order to simplify the code for this project. Please try it out and let me know if it's sufficient or other changes would be required to avoid workarounds such as the one below:

https://github.com/jerairrest/react-chartjs-2/blob/d80f5881504460f94adb30b2813bcc67e328d2bb/src/index.js#L126

**Comment by jerairrest** [comment]
Hey Ben!

I'm curious what your thoughts are about making a "react-chartjs-3" instead of creating a major version bump of this package. This would allow the naming convention to continue.

**Comment by benmccann** [comment]
If it were me personally maintaining it I wouldn't want a version number in the name. I'm not sure I'd want to create a new repo everytime the version number changes nor would I want to be getting bug reports and pull requests for old versions of the library. I don't think we will maintain Chart.js 2.x separately once 3.x is released. But it's your project, so I don't have very strong feelings about it and am happy with whatever you decide

**Comment by Jareechang** [comment]
will there be a lot of deprecations coming in Chart.js 3.x ? 

I'd image there will be still a lot of the same features supported right ? 

What are you'll thoughts on moving this repo to use a mono-repo ? This will hopefully help reuse the boilerplate require for the new repo (testing, linting, storybook, build and deploy code)
- `packages/react-chartjs-common` // Common utilities mentioned above
- `libraries/react-chartjs-2`
- `libraries/react-chartjs-3`

**Comment by benmccann** [comment]
All the functionality and feature set is basically the same. However, there are pretty fair number of API changes in order to meet our goals for v3 such as improved performance. Here's the migration guide:
https://github.com/chartjs/Chart.js/blob/master/docs/getting-started/v3-migration.md

**Comment by benmccann** [comment]
Should I close this as a duplicate of https://github.com/jerairrest/react-chartjs-2/issues/480?

**Comment by jerairrest** [comment]
Let's close this one for now and deal with this in the other issue.
