### ISSUE TITLE
Error : Uncaught SyntaxError: Unexpected token '!'

### ISSUE THREAD

**Issue by landreaubis** [jerairrest/react-chartjs-2#460]
Hello,
I have a problem.

When i import "import { Pie } from "react-chartjs-2";" in my  file, i have this message error : 

> Uncaught SyntaxError: Unexpected token '!'

It's here : 0.chunk.js
```
this.chartInstance = new !(function webpackMissingModule() { var e = new Error("Cannot find module 'chart.js'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(node, {
      type: type,
      data: data,
      options: options,
      plugins: plugins
    });
```

I'm novice in react.

**Comment by Pringels** [comment]
@landreaubis did you install `chart.js` as a peer dependency?

This error suggests that it could not be resolved at build time:
`new Error("Cannot find module 'chart.js'")`

Please install it and try to build your project again:
`npm install --save chart.js`

Here is the relevant section in the README: https://github.com/jerairrest/react-chartjs-2#update-to-2x

**Comment by landreaubis** [comment]
It's good, i had already install with --save, but, i rebuild my docker and it's ok...

Thanks
