### ISSUE TITLE
Highlighting a particular point

### ISSUE THREAD

**Issue by guygrinberger** [jerairrest/react-chartjs-2#461]
Hi,

I am trying to highlight a particular point in the graph using its index as answered here:
https://stackoverflow.com/questions/55468483/highlight-a-particular-point-in-chart-js

my customRadius function:
```
function customRadius( context )
{
  let index = context.dataIndex;
  return index === 3 ?
         10 :
         2;
}
```
 my option variable:
```
    var options = {
      legend  : {
        display: false
      },
      elements: {
        point: {
          radius : customRadius,
          display: true
        }
      }
    };

```
and the chart:
```
            <Line 
              data={data}   
              options={options}
            />
```

I expected the 3rd index point will be highlighted.

What am I doing wrong?

p.s.
Thanks for your work! helped me a lot

**Comment by Pringels** [comment]
@guygrinberger what are you seeing instead? No highlighted point? Or the 4th index highlighted?

If you want to highlight the third point you should use the following: (as array indexes start at 0)
`return index === 2 ?`

If you are not seeing any highlighted points then please open an issue Chart.js directly: https://github.com/chartjs/Chart.js/issues

**Comment by guygrinberger** [comment]
@Pringels My bad. I copied a dataset which had pointRadius: 0 so I couldn't see it. Sorry
