### ISSUE TITLE
Deprecated warning, please update chart.js version.

### ISSUE THREAD

**Issue by goldenshooter** [jerairrest/react-chartjs-2#490]
Hi there, thank you for building this incredible library.

I just find out this deprecated warning recently. 
![image](https://user-images.githubusercontent.com/10394787/74076845-f4684e80-4a7f-11ea-8094-317edde47281.png)

And chart.js had this issue before, and fixed it from version **2.9.1**

![image](https://user-images.githubusercontent.com/10394787/74076867-1661d100-4a80-11ea-8622-1cddcb0f8551.png)
![image](https://user-images.githubusercontent.com/10394787/74076936-b586c880-4a80-11ea-873b-c940142df4ce.png)

Please update chart.js version to fix this warning. There are so much of them in console, really annoying.

Thanks!

**Comment by fcoouto** [comment]
Hello there... Any news about this issue?

**Comment by jhonnold** [comment]
`chart.js` is a peer dependency of this library. If you require it to be updated, that is something that would be done on your end.
