### ISSUE TITLE
Can not use with react-onsenui tabs

### ISSUE THREAD

**Issue by whizsid** [jerairrest/react-chartjs-2#503]
I am using the `Line` chart in a `react-onsenui` tab. I am getting below error when changing the tabs.
```

TypeError
_chart2.default.helpers.configMerge is not a function

```

## How to reproduce:-

This is a live demo:- https://codesandbox.io/s/react-typescript-mx2uj

1. Go to the Guide Tab
2. Come back to the Hello Tab.

**Comment by nicholasess** [comment]
@whizsid is error on chartjs, please, open the issue in the project official

**Comment by benmccann** [comment]
I don't think this is an error from Chart.js. @nicholasess can you explain why you think it is?

**Comment by nicholasess** [comment]
@benmccann I found the line that execute the **Chart.helpers.configMerge** and Chart was imported from chart.js

https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js#L190

**Comment by nicholasess** [comment]
@whizsid @benmccann I solved the problem, just put the redraw={true} in <Line />

https://codesandbox.io/s/react-typescript-6ulgu?file=/src/HelloPage.tsx

o/

**Comment by whizsid** [comment]
@nicholasess @benmccann Thank You!
