### ISSUE TITLE
How to change grid color?

### ISSUE THREAD

**Issue by zeroxthegrim** [jerairrest/react-chartjs-2#517]
Graphs by default have grey colored grid. How do I change it?

**Comment by donaldrshade** [comment]
@zeroxthegrim Check out /Repo/react-chartjs-2/index.d.ts
I would search in this file for grid. I was looking for grid ticking and I think I saw something about color.

**Comment by Ayobamigit** [comment]
Hi, Did you find a way to sort this out?

**Comment by Ayobamigit** [comment]
Just found something that might help. You can set individual colors for the horizontal and vertical gridlines by adding a scales configuration to your options:

options:{
scales: {
    yAxes: [{
        gridLines: {
            color: 'green'
        }
    }],
    xAxes: [{
        gridLines: {
            color: 'red'
        }  
    }]
}
}

**Comment by jhonnold** [comment]
The official `chart.js` documentation has styling options [here](https://www.chartjs.org/docs/latest/axes/styling.html).
