### ISSUE TITLE
React-chartjs-2 update height dynamically

### ISSUE THREAD

**Issue by Veda-cmd** [jerairrest/react-chartjs-2#528]
I am using react-chartjs-2 library. I have used HorizantalBar which will receive data through props dynamically from parent component. I have wrapped HorizantalBar inside a div to control its height according to data. The height is getting updated in div but not in chart unless the browser is refreshed/resized. I inspected and checked the element. The height of canvas element of chart is not getting updated on re-render. Can someone please help?
I have attached code snippets.

`<div className={classes.chart}  style={{ height: calculateHeight()}}>
        <HorizontalBar data={dataHorizontal}
        ref={(reference) => { chartReference = reference }}
        options={chartOptions}>
        </HorizontalBar>
    </div>`

   ` function calculateHeight() {
        let length = arrayData ? arrayData.length : 0
        switch (true) {
            case length >= 0 && length <= 7:
                // console.log("1");
                return 50 + length * 50;
            case length > 8:
                // console.log("2");
                return 450 + ((length - 8) * 50);
            default:
                // console.log("3");
                return 450
        }
    }`

**Comment by jj0e** [comment]
I am trying to do something similar. The best method that I could find is that you set a height value and then set
```js
responsive: true
``` 
and 
```js
maintainAspectRatio: true
```
in your chart options. It's a bit hackish and I'm trying to find a better way myself but this seems to be the only way right now. It would be nice if we could set a ``className`` or allow % values.

**Comment by jj0e** [comment]
> I am trying to do something similar. The best method that I could find is that you set a height value and then set
> 
> ```js
> responsive: true
> ```
> 
> and
> 
> ```js
> maintainAspectRatio: true
> ```
> 
> in your chart options. It's a bit hackish and I'm trying to find a better way myself but this seems to be the only way right now. It would be nice if we could set a `className` or allow % values.

Actually I just found this. It can be solved as stated in this [closed issue](https://github.com/jerairrest/react-chartjs-2/issues/362#issuecomment-497474386)

**Comment by Veda-cmd** [comment]
@jj0e Thanks for the suggestion. I tried but it did not work. I used the redraw property to update the chart since the data was dynamically received. I used state to control the redraw property's value.

`redraw={true}`

**Comment by muhammadahmad5149** [comment]
https://github.com/Veda-cmdhttps://github.com/Veda-cmd
