### ISSUE TITLE
Reference Area

### ISSUE THREAD

**Issue by charlesduc** [jerairrest/react-chartjs-2#544]
Hi
I am trying to do some reference area on graph (bar and scatter)
I want to know if its possible to do it or if it's something easy to do with a fork of the lib.

**Comment by jhonnold** [comment]
Could you clarify on:

> do some reference area

I'm not sure what you mean by that, do you mean highlight or emphasize a portion of the chart?

**Comment by charlesduc** [comment]
Yeah I want to highlight a portion of the chart with a rectangle for example.

**Comment by charlesduc** [comment]
An example of what i am trying to do
![captureIssu](https://user-images.githubusercontent.com/66686886/89016532-29f84100-d319-11ea-9cb0-97def29c3036.png)

**Comment by jhonnold** [comment]
This is something that is more related to `chart.js` itself, and has been probably done with plugins. 

I found potentially something for you here: [chartjs-plugin-annotation](https://github.com/chartjs/chartjs-plugin-annotation)

**Comment by charlesduc** [comment]
Thanks, that's was what i was looking for.
