### ISSUE TITLE
Using adapters

### ISSUE THREAD

**Issue by ayxos** [jerairrest/react-chartjs-2#559]
I have a react app that uses react-chartjs-2.

On production chart.js includes the whole moment library, and even without locales is still big; Chart.js has the chance to not use moment, and use date-fns instead, via adapters. but I have no idea how to implement it on react-chartjs-2 via webpack. 

Any idea?

**Comment by seikosantana** [comment]
Did you find any solutions?

**Comment by kevcenteno** [comment]
Do this: 

1. `npm install date-fns chartjs-adapter-date-fns --save`
2. Add `import 'chartjs-adapter-date-fns';` in whatever file you need to use it

Source: https://github.com/chartjs/chartjs-adapter-date-fns
