### ISSUE TITLE
chartjs showXLabels

### ISSUE THREAD

**Issue by emanpatricio** [jerairrest/react-chartjs-2#70]
Hi,

does react-chartjs-2 support showxlabels / skiplabels ?

Thanks

**Comment by jerairrest** [comment]
passing empty strings seems to work. How would you do this from within regular chart.js?

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
