### ISSUE TITLE
chart not updating

### ISSUE THREAD

**Issue by dmichel76** [jerairrest/react-chartjs-2#90]
I'm trying to get my chart to update dynamically as new data comes in (from socket.io)
so I have a method onChange(data) that is used as the callback function of setState called when the new data comes in.

The Chart however does not update itself... unless I refresh/resize the browser. If I set redraw={true}, then the chart updates but it seems to refresh the whole page (?) and kills the performance for the rest of the page...

Any idea what I'm doing wrong here? 

```
import React from 'react'
import ReactDOM from 'react-dom'

import {Line} from 'react-chartjs-2'

module.exports =  class MyChart extends React.Component {

  constructor(props)
  {
      super(props)
      this.buffersize

      this.data = {
        labels: [],
        datasets: [
          {/
            label: 'My Chart',
            data: []
          }
        ]
      }

  }

  onChange(newdata) {

    const size = this.data.datasets[0].data.length
    if (size >= this.buffersize)
    {
      this.data.datasets[0].data.shift()
      this.data.labels.shift()
    }

    this.data.labels.push(newdata.label)
    this.data.datasets[0].data.push(newdata.value)

  }

  render()
  {
    return (
      <Line data={this.data}/>
    )
  }

}
```

**Comment by gor181** [comment]
hey @dmichel76 ,

Try to force a refresh by setting the `key` dynamically to any value. This would be a quick fix (if it works).

I'll try to check your example during this week.

**Comment by jerairrest** [comment]
Is it because you're not passing a fresh object to the Line Component so it can't tell the data has been updated? Could you tie your updates through your component's lifecycle to see if that would help? I know I've used GraphQL and react-chartjs-2 and I've had to make another wrapper for my graph object so it could detect changes.

**Comment by dmichel76** [comment]
@gor181 What do you mean by setting the `key` ? Do you mean the `labels` array ? if yes, then I do do that already with a `this.data.labels.push()`

**Comment by dmichel76** [comment]
@jerairrest I've just moved from using react-chart.js (which is limited to using Chart.js v1.1.1) and the same code works just fine, so it would seem unnecessary to create a new object.

By component lifecyle, do you mean using `state` ? If so, then I'm doing that already (although I admit it's not clear in my code) as the `onChange()` method is called by the `setState()` method. Or do you mean something else?

**Comment by jerairrest** [comment]
Sorry, so you're going `this.setState(this.onChange(newData))`

**Comment by dmichel76** [comment]
@jerairrest yes, I'm actually using socket.io to get data from the server so I've got something like:

```
socket.on(message, data => {
    this.setState( lastupdated: data.timestamp, this.onChange(data))
})
```

Apologies that this not clear in my initial post. I didn't want to pollute the code with Socket.io stuff as I thought it would distract from the actual issue.

**Comment by nealoke** [comment]
@dmichel76 Don't you need to use the `redraw` prop like so?

`<Line data={this.data} redraw />`

**Comment by dmichel76** [comment]
@nealoke Yes, as I said in my original post, when adding`redraw={true}`, the update occurs but it seems to refresh the whole page (one can see the reloading icon of the browser constancy on) rather than just the widget, affecting the performance of the whole page....

**Comment by albert421** [comment]
Same here. My charts all blinks and redraws. Is there another way to update chart?

**Comment by pokemonmegaman** [comment]
After tinkering around, it seems that react-chartjs-2 "memoizes" properties of the chart, which creates an issue where chart.js is attempting to find a metadata value while updating the chart and throws an error:

`Uncaught TypeError: Cannot read property 'skip' of undefined`

Removing https://github.com/gor181/react-chartjs-2/blob/master/src/index.js#L157 seems to allow dynamic chart data updates without needing to use redraw.

**Comment by jerairrest** [comment]
So should we keep only the dataset to verify if we need to update the component?

**Comment by XidongHuang** [comment]
Hi @dmichel76, I think I had the same issue at the beginning - cannot redraw the chart when the new data coming. So I tried to reload the whole chart configuration, here is the my code:
```
...
updateChart(chartData) {

    this.setState(prevState => ({
      chartLabel: chartData.dateArray,
      volData: chartData.volTotalArray,
      tempData: chartData.tempArray,
      pressIn: chartData.PInArray,
      pressOut: chartData.POutArray
    }));
  }



 reloadChart() {
    return  {
            labels: this.state.chartLabel, 
            datasets: [{
                type: 'line',
                label: 'Temperature',
                data: this.state.tempData,
                fill: false,
                backgroundColor: '#f6d155',
                borderColor: '#f6d155',
                hoverBackgroundColor: '#20C80C',
                hoverBorderColor: 'red',
                yAxisID: 'y-axis-1'
              },{
                type: 'line',
                label: 'Pressure In',
                data: this.state.pressIn,
                fill: false,
                backgroundColor: '#f2552c',
                borderColor: '#f2552c',
                hoverBackgroundColor: '#20C80C',
                hoverBorderColor: 'red',
                yAxisID: 'y-axis-1'
              },{
                type: 'line',
                label: 'Pressure Out',
                data: this.state.pressOut,
                fill: false,
                backgroundColor: '#ce3175',
                borderColor: '#ce3175',
                hoverBackgroundColor: '#20C80C',
                hoverBorderColor: 'red',
                yAxisID: 'y-axis-1'
              },{
                label: 'Volume',
                type:'bar',
                data: this.state.volData,
                fill: false,
                borderColor: '#5484A4',
                backgroundColor: '#5484A4',
                pointBorderColor: '#00b377',
                pointBackgroundColor: '#EC932F',
                pointHoverBackgroundColor: '#EC932F',
                pointHoverBorderColor: '#EC932F',
                yAxisID: 'y-axis-2'
              }]
          }; 
  }

....

render() {
  return (
     <div>
         <Bar
                data={this.reloadChart()}
                options={options}
                getElemmentAtEvent={clickedData => this.getClickData(clickedData)}
           />
     </div>
   )
}

```
I don't use `socket.io` here, but maybe you can try 
```
socket.on(message, data => {
    updateChart(data);
})
```
Hope this can be helpful for you.

**Comment by ludiofines** [comment]
@pokemonmegaman L155 seems to be empty line in current master branch. Could you update your answer please?

I got a similar issue where `currentDatasets` is copied from `chart_instance.config.data` which contains invalid `_meta.controller.index`. It's probably due to splice() which changes elements indexes but _meta is not updated ... Any ideas?

**Comment by jalilahmed** [comment]
I m having the same issue. I have made, datasets.data = this.state.data. but Updating state does not update chartjs

**Comment by desirelabs** [comment]
Same problem : If I'm using `redraw` then the whole page is updating and I have a blink before changes appear. If I don't use `reraw`, there is an error showing in console from chartjs core.controller.js : `TypeError: Cannot set property 'options' of undefined` 
Has anyone figured this out ?
Thanks

**Comment by FredGr** [comment]
Same problem, I managed to trick the update by adding a state.change boolean that I change inside setState every time the data get updated. Using the chrome React extension I saw that there is clearly a problem in passing the update of the data between the Line component (in react-chartjs-2.js) and the ChartComponent  in lib/index.js. Hope it helps to have a definitive fix soon.

**Comment by JeffLoo-ong** [comment]
@ludiofines 
 [Here's](https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js#L155)
 the updated location for the post @pokemonmegaman put.

This did not fix my issue with the graph redrawing though :(

**Comment by desirelabs** [comment]
Hello, as far as I got: usine redraw and shouldComponeneUpdate allows chart to redraw, once data updated. And only one time. Hope it will help.

**Comment by tudro** [comment]
Hello, this should do the trick https://stackoverflow.com/questions/49316914/react-chartjs-2-not-updating-graph-when-state-updates You don't need redraw or anything else, just make sure you do a copy of the labels and datasets. It worked for me.

**Comment by Xero-0** [comment]
@gor181 Thanks! 

just using `key={Math.random()}` in my chartjs component did the trick.

**Comment by francisngo** [comment]
The `key={Math.random()}` gives the same effect as the `redraw` property.

**Comment by nejcr** [comment]
I solved it using lodash  [_.cloneDeep](https://lodash.com/docs/4.17.15#cloneDeep) function when switching from one dataset to another.

**Comment by bmakan** [comment]
I update the chartsjs instance directly. The data comes in via websocket. Inspired by: [chartsjs-plugin-streaming](https://github.com/nagix/chartjs-plugin-streaming#push-model-listening-based).

```js
componentDidMount() {
    this.socket = io(window.location.origin, { path: `${window.location.pathname}/ws`, transports: ['websocket'] });
    this.socket.on('value_update', ({ a, b }) => {
        this.chartsjs.chartInstance.data.datasets[0].data.push({ x: Date.now(), y: a });
        this.chartsjs.chartInstance.data.datasets[1].data.push({ x: Date.now(), y: b });

        this.chartsjs.chartInstance.update({
            preservation: true,
        });
    }
}

<Line
    ref={(chartsjs) => { this.chartsjs = chartsjs; }}
    // Set datasets
/>
```

Not sure if it's correct way to do it performance wise.

**Comment by theshashiverma** [comment]
@nealoke thanks, redraw helped me, I was just about to use recharts(Echarts)

**Comment by zackster** [comment]
@bmakan Thank you, was extremely helpful for me to get it working.

In my functional component, I declare

`const myChart = createRef();`

Then I return

```
	return (

		<Line

                 ref={myChart}
		data={config.data}


		options={{
			scales: {
				xAxes: [{
					type: 'realtime',
					realtime: {
						duration: 60 * 1000,
						ttl: 60 * 1000,
						refresh: 500,
						delay: 500 
					}
				}]
			}
		}}

		/>

	);
```

And inside my websocket I do:

`myChart.current.chartInstance.data.datasets[0].data.push({ x: Date.now(), y: dataPoint });`

**Comment by marano** [comment]
@francisngo 
> The `key={Math.random()}` gives the same effect as the `redraw` property.

No it isn't, using `redraw` for me didn't work properly when the graph height had changed.

**Comment by altaga** [comment]
> @dmichel76 Don't you need to use the `redraw` prop like so? (This did it for me)
> 
> `<Line data={this.data} redraw />`

This works for me!!!

**Comment by GemsGame** [comment]
> @gor181 Thanks!
> 
> just using `key={Math.random()}` in my chartjs component did the trick.

thanks , this best solution:)

**Comment by negebauer** [comment]
But `key={Math.random()}` makes it so that every time the component re renders the chart is deleted and created again (since `key` is used by React as an instance identifier).
Doesn't sound like a solution performance wise 😕

**Comment by ambr89** [comment]
@negebauer I've the same problem.

Do you have found a solution?

**Comment by negebauer** [comment]
We keep the data in state, so that when it changes the component that shows the chart renders again.
We don't modify the data object itself directly.

**Comment by mahbub-hussain** [comment]
```
useEffect(()=>{
let mychart=new Chart(ctx,data)
//do cleanup
return()=>mychart.destroy()
},[])
```

**Comment by mahbub-hussain** [comment]
`
useEffect(()=>{
let mychart=new Chart(ctx,data)
//do cleanup
return()=>mychart.destroy()
},[])
`

**Comment by abdullahrafione** [comment]
> redraw

just add redraw before closing tag and it would work fine

**Comment by G-kodes** [comment]
I have just implemented a React Chartjs 2 instance and can confirm this is still an issue, at least for me. I am in an ElectronJS dev setup and have double checked that this seems to be a non-ElectronJS issue as far as I can tell.

```JavaScript
const [chartData, setChartData] = useState(null);

// Data Fetch
useEffect(() => {
//...Async fetch my data from file and update state
});

// Attempt at triggering update whenever datasets change:
useEffect(() => {
    if (chartData !== null) {
      chartRef.current.chartInstance.update({
        preservation: true,
      });
    }
  }, [chartData]);

// Nested component to trigger rerender of only the graph for performance
const Graph = () => {
    return (
      <>
        {chartData ? (
          <Line data={chartData} options={options} title="Pressure over ticks" ref={chartRef} redraw />
        ) : null}
      </>
    );
  };

return (
    <Graph />
)
```

Unfortunately, the `.update()` function does not seem to be doing anything and the chart does not render the chart data unless I resize the application window. I have tried both `redraw` and without and neither does anything. I have attempted to mix and match to get it to trigger but nothing is doing the trick here? Any ideas?

**Comment by abdullahrafione** [comment]
I just added and redraw/> at the end of Component and the state should update as well in the local Component

**Comment by parminpatel28** [comment]
@abdullahrafione for me it isn't updating even when I include redraw. Do you know any work arounds for this issue?

**Comment by perryraskin** [comment]
Ok so I just had this issue and spent a ton of time on it, until I finally realized what I was doing wrong. I hope this helps anyone on this thread and anyone who also runs into this issue!

Originally I had the `chartData` set up as a state variable. I realized later that the state was never getting updated so I changed it to a regular variable that gets updated whenever new data is fetched and passed to my custom Chart component. See my Chart component below:

```typescript
import type { NextPage } from "next"
import React from "react"
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js"
import { Line } from "react-chartjs-2"

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
)

interface Props {
  labels: string[]
  history: number[]
}

const Chart: NextPage<Props> = ({ labels, history }) => {
  const chartData = {
    labels: labels as never,
    datasets: [
      {
        label: "Last 10 Minutes",
        backgroundColor: "#4F1894",
        borderColor: "#4F1894",
        data: history,
      },
    ],
  }

  return (
    <div className="mt-6 shadow rounded bg-white p-4 sm:p-10">
      <Line data={chartData} />
    </div>
  )
}

export default Chart
```

The chart gets refreshed any time new data is fetched and passed to this component! 😄

**Comment by dannypk** [comment]
> The `key={Math.random()}` gives the same effect as the `redraw` property.

For me the `redraw` property ain't working but the key does it's job. Such a silly solution though :(

**Comment by flogaribal** [comment]
> @gor181 Thanks!
> 
> just using `key={Math.random()}` in my chartjs component did the trick.

Same for me, `redraw` isn't working but above solution is. Indeed, a good workaround but not a viable solution :(

My problem was a bit different but related to data update. On first render, chart did not have any data and once fetch was done, the chart was not rendered with the fetched data...

Any better solution welcome :)

**Comment by dangreen** [comment]
@dannypk @flogaribal Hi

1) Do you use immutable data?
2) Did you try [this](https://react-chartjs-2.js.org/docs/working-with-datasets) ?

**Comment by flogaribal** [comment]
Here is the code I just tested following your link
```
const initialData = {
    labels: [],
    datasets: [
      {
        id: 0,
        data: [],
        backgroundColor: chartColors,
        color: chartColors,
        borderWidth: 0,
      },
    ],
  };
  
  const DoughnutChart = (props) => {
    const [data, setData] = useState(initialData);
  
    useEffect(() => {
      initialData.datasets[0].data = props.data;
      initialData.labels = props.labels || [];
      setData(initialData)
    }, [props.data, props.labels])
  
      const chartOptions = _.merge({
        cutout: '80%',
        plugins: {
          legend: false
        }
      }, props.options);

      return  <Doughnut 
        datasetIdKey='id'
        data={data} 
        options={chartOptions}
    />
    }
```

**Comment by dangreen** [comment]
@flogaribal like everywhere in react you should change data by immutable way.

**Comment by aleksbobic** [comment]
Did this get any updates or further attention from the authors? I attempted the same (i.e. deep copy and randomising the key) and only randomising the key seems to work for me too.
