### ISSUE TITLE
Tooltip is cropped on Bar chart if value is bigger than axis max

### ISSUE THREAD

**Issue by roboslone** [jerairrest/react-chartjs-2#92]
If `max` is defined for `yAxis`, tooltips for items which values exceed that `max` are not shown. On the picture below arrow indicate hovered bars. Item in the middle has value much higher than bar's `max` value and tooltip is not displayed.
<img width="798" alt="1" src="https://cloud.githubusercontent.com/assets/1941275/21751148/48d0f140-d5d3-11e6-972b-f8efca87e288.png">

Is there a way to make tooltips appear at the cursor position or at the bottom of hovered bar?

**Comment by gioele-antoci** [comment]
This is more a question related to chartjs but nonetheless I'll give my 2 cents.
[Here](http://www.chartjs.org/docs/#chart-configuration-tooltip-configuration) you could find some answers. Tooltips being cutoff is a long standing issue (since the port to v.2 I believe), you can read more [HERE](https://github.com/chartjs/Chart.js/issues/622).
The short fix is to reduce the text inside the tooltip.
The longer fix is to override default tooltips with custom ones (more [HERE](http://www.chartjs.org/docs/#advanced-usage-external-tooltips)

**Comment by roboslone** [comment]
@gioele-antoci , there's no problem with text _inside_ tooltip, the problem is _tooltip itself_ is  cut. So short fix is not applicable, unfortunately. I'm not sure, but I think overriding tooltips will not change their position.

**Comment by gioele-antoci** [comment]
> ![](https://cloud.githubusercontent.com/assets/5332920/4226100/72321160-3934-11e4-9b65-58ba2a55e9da.png)

You are having this issue, right?

Overriding the tooltips will allow you to have full control over their positioning. This may be overkill though. There are lots of workaround here: https://github.com/chartjs/Chart.js/issues/622

**Comment by roboslone** [comment]
@gioele-antoci , no, my tooltip is cropped at the top of the graph (y-axis max is defined, so bars themselves are cut too, but that's fine).

**Comment by gioele-antoci** [comment]
Oh, I see. If you remove max tooltips are not cutoff? Anyway, the official chartjs rep is a better place for this convo.

**Comment by roboslone** [comment]
@gioele-antoci , well, at least they aren't cut at the top of the graph. Not sure about sides. I'll ask about this in official repo, thanks.

**Comment by gioele-antoci** [comment]
If they are cut off on the right edge even after the "max" option has been taken out than it's quite likely the underlying bug is causing both issues and you could fix it in the meanwhile by applying one of those hacks proposed in the issue thread I linked :)

**Comment by Pringels** [comment]
Closing for now. Please refer to the Chart.js documentation for questions around configuration and/or usage of the library. If you have a bug or enhancement related directly to Chart.js, please open an issue on their Github.
